wordpress-mobile/AztecEditor-iOS

Classes/Private/NSAttributedString/Converters/HTMLNodeToNSAttributedString.swift, Classes/Public/Constants/HTMLConstants.swift, Example/WordPress-Aztec-iOS/SampleContent/content.html
When loading HTML data, the editor demo now renders:
- Bold Text
- Italic Text
- Underlined Text
- Striked-through text
- Links
**To test:**
Launch the app, go to the editor demo and make sure the styles mentioned above are being rendered properly.
=> Load HTML in Style!

Classes/Private/Libxml2/Converters/Out/OutHTMLConverter.swift, Example/Tests/Data/content.html
Fixes the HTML output conversion.
The best way to test this is to integrate it into `feature/19-html-mode`.  The conversion is not perfect due to other issues we'll need to tackle, but it should be enough to keep making progress.
=> Fixes the HTML output conversion.

Classes/Public/Extensions/UITextView+Helpers.swift, Classes/Public/TextKit/AztecVisualEditor.swift, Example/WordPress-Aztec-iOS/EditorDemoController.swift
@diegoreymendez + @aerych mind taking a quick look?
I've simplified `EditorDemoController` a little bit: nuked setters that weren't being used anywhere.
Suggestions would be very welcome!
=> Feature: HTML Mode

Classes/Private/Converter/ArrayConverter.swift, Classes/Private/Libxml2/Converters/In/InHTMLConverter.swift, Classes/Private/Libxml2/Converters/In/InNodeConverter.swift, Classes/Private/Libxml2/Converters/Out/OutHTMLConverter.swift, Classes/Private/Libxml2/Converters/Out/OutHTMLNodeConverter.swift, Classes/Private/Libxml2/Data/Attribute.swift, Classes/Private/NSAttributedString/Converters/HTMLNodeToNSAttributedString.swift, Classes/Public/Extensions/UITextView+Helpers.swift, Classes/Public/TextKit/AztecAttachmentManager.swift, Classes/Public/TextKit/AztecVisualEditor.swift
Some warnings are not showing in the details pane, and are showing in the build results instead.  Since I'm having trouble with one of my branches I decided to start fixing these just in case.
1. Make sure the code builds.
2. Make sure the unit tests run properly.
3. Make sure the demos still work.
=> Fixes all warnings.

Classes/Public/Extensions/UITextView+Helpers.swift, Classes/Public/TextKit/AztecAttachmentManager.swift, Classes/Public/TextKit/AztecVisualEditor.swift, Example/WordPress-Aztec-iOS/EditorDemoController.swift
Sergio, mind taking a look at this one?. Media Picker + Image Insertion.
Needs Review: @SergioEstevao
=> Media Picker: Inserting Images

Classes/Public/TextKit/AztecTextStorage.swift, Classes/Public/TextKit/AztecVisualEditor.swift
Fixes #43 and #44.
The same testing procedure and limitations as #42 applies.
=> Adds underline and strikethrough support.

Classes/Private/Libxml2/Data/CommentNode.swift, Classes/Private/Libxml2/Data/EditableNode.swift, Classes/Private/Libxml2/Data/ElementNode.swift, Classes/Private/Libxml2/Data/Node.swift, Classes/Private/Libxml2/Data/TextNode.swift, Classes/Public/TextKit/AztecTextStorage.swift, Classes/Public/TextKit/AztecVisualEditor.swift, Example/Tests/HTML/ElementNodeTests.swift
@SergioEstevao - Added a few more changes for you to review.  These could be added to your PR.
We probably need to discuss this on monday.
=> Adds several improvements for comment nodes.

Classes/Public/TextKit/TextView.swift, Example/Tests/AztecVisualEditorTests.swift, Example/WordPress-Aztec-iOS/EditorDemoController.swift
Implements the editor as a subclass of UITextView, so that we can use it in Interface Builder.
1. Run the demo app.
2. Edit some styles.
3. Edit some text.
4. Attach images.
5. Make sure everything works as in `develop`.
6. Run the unit tests.
=> Implements the editor as a subclass of UITextView

Aztec.xcodeproj/project.pbxproj, Aztec/Classes/Private/Libxml2/Converters/Out/OutHTMLNodeConverter.swift, Aztec/Classes/Private/Libxml2/Data/CommentNode.swift, Aztec/Classes/Private/Libxml2/Data/EditableNode.swift, Aztec/Classes/Private/Libxml2/Data/ElementNode.swift, Aztec/Classes/Private/Libxml2/Data/LeafNode.swift, Aztec/Classes/Private/Libxml2/Data/Node.swift, Aztec/Classes/Private/Libxml2/Data/TextNode.swift, Aztec/Classes/Private/NSAttributedString/Converters/HTMLNodeToNSAttributedString.swift, Aztec/Classes/Public/TextKit/TextStorage.swift, Aztec/Classes/Public/TextKit/TextView.swift, AztecTests/HTML/ElementNodeTests.swift, AztecTests/Importer/HTMLToAttributedStringTests.swift, AztecTests/Importer/InHTMLConverterTests.swift, AztecTests/Importer/InNodeConverterTests.swift
This PR adds some unit tests to avoid regressions with the latest link fixes.  It also adds some code to aid in debugging (Node inspection).
Also adds the concept of `leaf` nodes to group `TextNode` and `CommentNode`.
1. Run the unit tests and make sure they work fine.
2. Try adding / removing links and make sure they work right.
=> Adds unit tests, adds methods to aid in debugging.

Aztec/Classes/Private/Libxml2/Data/ElementNode.swift, Aztec/Classes/Public/TextKit/TextStorage.swift, Aztec/Classes/Public/TextKit/TextView.swift
This PR offers some modifications on top of the target PR.
Image insertion works slightly better - there are still some synch issues.
=> Improvements for image insertion.

Aztec/Classes/Private/Libxml2/Data/ElementNode.swift
Cleans up the code a bit by simplifying a method, and fixing another method's documentation.
Make sure the editor behaviour is the same as in `develop`, when applying styles to ranges.
=> Cleans up the code a bit.

Aztec.xcworkspace/contents.xcworkspacedata
Please, verify that the `Aztec.xcworkspace` opens the subproject without further issues.
Thanks!!
=> Nukes Subject's absolute path

Example/AztecExample.xcodeproj/project.pbxproj, Example/Cartfile, Example/Cartfile.resolved, Example/Example/EditorDemoController.swift
How to test:
- Check if the images on the preloaded html data, display correctly
- Insert some images from the media library and see if they work correctly.
=> Replace alamofire for vanilla NSURLsession

Aztec.xcodeproj/project.pbxproj, Aztec/Classes/Private/NSAttributedString/Converters/HTMLNodeToNSAttributedString.swift, Aztec/Classes/Public/Extensions/NSAttributedString+Attachments.swift, Aztec/Classes/Public/Extensions/NSLayoutManager+Attachments.swift, Aztec/Classes/Public/TextKit/TextAttachment.swift, Aztec/Classes/Public/TextKit/TextStorage.swift, Aztec/Classes/Public/TextKit/TextView.swift
Just a first stab on implementing loading of attachment directly on the attachment instead of storage.
This PR is still not complete it's just a first refactor in order to evaluate if it's a good idea.
Still needs to implement code for image with missing URL reference.
@diegoreymendez do you mind to have a look at the code.
=> Refactor image attachment

Aztec/Classes/Public/TextKit/TextAttachment.swift
Closes #126 
How to test:
- Add image to editor
- Long press in the image
- Change the alignment and/or size properties
- Make sure they are updated in the visual editor
=> Update attachment image after properties change

Aztec.xcodeproj/project.pbxproj, Aztec/Classes/Private/Libxml2/DocumentObjectModel.swift, Aztec/Classes/Public/TextKit/TextStorage.swift
Introduces a DOM object to represent the HTML document object model.
The DOM object represents the HTML document object model to the eyes of the rest of the code.  `DocumentObjectModel` is the class that will handle all interaction with the HTML structure.
It also takes care of managing the HTML editing queue (which was previously handled by `TextStorage`).
It also improves styles-handling so that styles don't need to be set explicitly anymore, other than through these methods which replicate `NSTextStorage`'s default editing methods (and in fact must be forwarded directly).
```swift
func replaceCharacters(inRange range: NSRange, withString string: String, inheritStyle: Bool)
func replaceCharacters(inRange range: NSRange, withAttributedString attributedString: NSAttributedString, …
```
=> Introduces the DOM object.

Aztec/Classes/Private/Libxml2/Data/ElementNode.swift, Aztec/Classes/Public/TextKit/TextStorage.swift
Fixes an issue with duplicated tags (Closed #131).
Removes some old, commente-out code.
Just follow the steps shown in [this video](https://cloudup.com/cqd4bHg4vJo) and make sure the issue is fixed.
=> Fixes duplicated tags.

Aztec/Classes/Libxml2/DOM/ElementNode.swift
Fixes some crashing bugs.
1. Open the editor
2. Press CMD + A to select all.
3. Tap the Bold button.
The app shouldn't crash anymore.
=> Fixes some crashing bugs.

Aztec/Classes/TextKit/LayoutManager.swift
Break the layout manager code in smaller methods and create some variable for block quotes colors and allow customisation.
=> Refactor layout manager code 

Aztec.xcodeproj/project.pbxproj, Example/AztecExample.xcodeproj/project.pbxproj
Please, install the latest Xcode build, and verify that the project can be built (in this branch!).
Thanks!
=> Fixing Xcode 8.2 Warnings

Aztec/Classes/TextKit/TextView.swift
Added missing methods documentation, and minor changes.
=> TextView: Adds missing method documentation

Aztec/Classes/TextKit/TextView.swift
1. Launch the Empty Demo App
2. Press the background, and release after two seconds
Verify that the demo app doesn't crash anymore.
Closes #198
=> TextView: Patching Bounds Check

Aztec/Classes/TextKit/TextView.swift
How to test:
- Start the editor demo 
- Go to a line toggle blockquote/list on a paragraph
- Check if the format bar is being updated correctly.
=> Make sure typing attributes are correct after applying styles.

Aztec/Classes/TextKit/TextView.swift
Just a method name refactor, check if project compiles and tests are all green.
=> Rename XXXFfNeeded methods to ensureXXX methods.

Aztec/Classes/Libxml2/DOM/ElementNode.swift, AztecTests/HTML/ElementNodeTests.swift
Fixes a bug in the code.  Adds a unit test that will fail if you roll back to the previous code.
Run the unit tests
If you want to see the previous failure, copy the unit test to `develop` and run.
=> Fixes a bug in the code.

Aztec.xcodeproj/project.pbxproj, Aztec/Classes/Formatters/BlockquoteFormatter.swift, Aztec/Classes/Formatters/TextListFormatter.swift, Aztec/Classes/TextKit/Blockquote.swift
This PR just make sure all our formatters are classes and have separate file for extra attributes.
How to Review:
- Just run the tests on the app and check everything is green.
=> Make all formatter classes, and create separate file for blockquote.

Aztec/Classes/Formatters/FontFormatter.swift, Aztec/Classes/Formatters/StandardAttributeFormatter.swift, Aztec/Classes/Libxml2/DOM/StandardElementType.swift, Aztec/Classes/Libxml2/DOMString.swift
How to test:
- Apply bold style to text and see if strong is applied
- Apply italic style to text and see if em is applied
- Apply strikethrough style to test and see if <del> is applied.
=> Use styles strong em and del by default for formatters.

Aztec/Classes/TextKit/TextView.swift, Example/Example/EditorDemoController.swift
Refactor update of progress and message to single method that marks attachment for  relayout.
=> Refactor update of attachment.

Aztec/Classes/TextKit/TextAttachment.swift
=> Make alignment property writeable from the outside.

Example/Example/EditorDemoController.swift
Unifies some extra duplicated code.
=> Unifies some duplicated code.

Aztec.xcodeproj/project.pbxproj, CONTRIBUTING.md, WordPress-Aztec-iOS.podspec
PR to test new release on the build server.
=> Release 0.5a2

Aztec.xcodeproj/project.pbxproj, Aztec/Classes/Converters/HTMLNodeToNSAttributedString.swift, Aztec/Classes/Formatters/StandardAttributeFormatter.swift, Aztec/Classes/Libxml2/DOM/StandardElementType.swift, Aztec/Classes/TextKit/LineAttachment.swift, Example/Example/SampleContent/content.html
Fix #279 
How to test:
- Load the demo app
- Check the sample content and see if the HR tag shows properly
- Delete it visually
- Switch back to code html mode and see if tag disappears
- Add some hr manually in html and see if they show in visual mode.
=> Implements the HR tag

Aztec/Classes/Libxml2/DOMString.swift, Aztec/Classes/TextKit/TextStorage.swift, AztecTests/TextStorageTests.swift
How to test:
- Open the empty demo
- Write a line with some text
- Tap on the blockquote option
- check if blockquote is applied visually
- switch to html mode
- Check that blockquote tag is present
- switch to visual mode
- Tap on the blockquote option
- Check the blockquote is removed visually
- Switch to html mode
- Check that the html doesn't have a blockquote
=> Fix blockquote formatting

Aztec/Classes/Converters/HTMLNodeToNSAttributedString.swift, Aztec/Classes/Libxml2/DOMString.swift, Aztec/Classes/TextKit/TextStorage.swift, Aztec/Classes/TextKit/TextView.swift, AztecTests/TextStorageTests.swift, Example/Example/EditorDemoController.swift
How to test:
- Open demo app
- Check if link is being parsed correctly from sample contentn
- Tap on link
- Check if URL and text of the link is correct
- Change url and text and tap update link
- Check if visual changes are correct
- Switch to HTML and see if html is correct.
- Switch to visual mode again
- Tap on the link
- Choose remove link
- Check if visual mode is correct
- Switch to html mode and check if html is correct.
=> Fix link formatting

Aztec/Classes/Libxml2/DOM/ElementNode.swift
This PR is just a precaution, I didn't find a scenario where this happen, but just in case.
=> Add HR to the list of elements that cannot have children.

Aztec/Classes/TextKit/TextView.swift
=> Set the typing attributes to whatever is on the selection range when the html is set.

Aztec.xcodeproj/project.pbxproj, Aztec/Classes/Extensions/String+RangeConversion.swift, Aztec/Classes/Libxml2/DOM/CommentNode.swift, Aztec/Classes/Libxml2/DOM/ElementNode.swift, Aztec/Classes/Libxml2/DOM/TextNode.swift, Aztec/Classes/Libxml2/DOMString.swift, Aztec/Classes/TextKit/TextStorage.swift, AztecTests/StringRangeConversionTests.swift
This is a WIP to fix the emoji issues.
First step is just to fix the display of the emoji on the TextView
=> Fix emoji issues

Aztec/Classes/TextKit/TextStorage.swift
Small change that I believe provides a fix to the real issue behind #347
=> Proposes a different solution to a style problem.

Aztec/Classes/TextKit/TextStorage.swift, AztecTests/TextStorageTests.swift
How to test:
- Use the empty editor demo
- Insert one image
- then just after the first insert a second image.
- Switch to html and check both img tag are there.
=> Fix attachment difference processing.

Aztec.xcodeproj/project.pbxproj, Aztec/Classes/GUI/FormatBar/FormattingIdentifier.swift, Aztec/Classes/Libxml2/DOM/Data/StandardElementType.swift, Aztec/Classes/Libxml2/DOMString.swift, Aztec/Classes/TextKit/TextStorage.swift, Aztec/Classes/TextKit/TextView.swift, AztecTests/TextStorageTests.swift, Example/Example/EditorDemoController.swift
Closes #360
This PR adds the possibility of adding HR elements using the toolbar and by a function call on RichTextView.
- How to test:
- Insert the Horizontal Ruler using the toolbar icon
- Check if the ruler is inserted visually and in code.
- Remove the ruler visually and check if html code is updated correctly.
=> Implement insertion of HR elements.

Aztec.xcodeproj/project.pbxproj, Aztec/Classes/Libxml2/DOM/Data/ElementNode.swift, Aztec/Classes/Libxml2/DOMString.swift, Aztec/Classes/Libxml2/Descriptors/CommentNodeDescriptor.swift, Aztec/Classes/Libxml2/Descriptors/ElementNodeDescriptor.swift, Aztec/Classes/Libxml2/Descriptors/NodeDescriptor.swift, AztecTests/HTML/ElementNodeTests.swift
- We've implemented a new NodeDescriptor base class, inherited by both, ElementNodeDescriptor and CommentNodeDescriptor
- Updated ElementNode's API
- And of course, patched the unit tests!
- Please, run the unit tests!
- Perform a smoke test, and check that nothing too obvious breaks down.
=> Supporting Comement Node Descriptors

Aztec/Classes/TextKit/TextView.swift
How to test:
- Launch the demo app
- Add a new line using header 4, 5, or 6.
- Tap Enter
- Check that style is not passed for the next line.
=> Add missing header levels for detection when newline is inserted.

Aztec/Classes/TextKit/TextStorage.swift, AztecTests/TextViewTests.swift
Fixes the crash reported in #350.
=> Fixes a crash.

Aztec.xcodeproj/project.pbxproj, Aztec/Classes/Converters/HTMLNodeToNSAttributedString.swift, Aztec/Classes/Extensions/UIColor+Parsers.swift, Aztec/Classes/Formatters/StandardAttributeFormatter.swift, Aztec/Classes/Libxml2/DOM/Data/StandardElementType.swift, AztecTests/Extensions/UIColorHexParserTests.swift, Example/Example/SampleContent/content.html
Closes #375 
This PR adds support for parsing of span elements with the color attribute.
=> Add the possibility to parse and create spans for colors.

Aztec/Classes/Formatters/AttributeFormatter.swift, Aztec/Classes/TextKit/TextStorage.swift, Aztec/Classes/TextKit/TextView.swift
While working on another issue I found out that the range propagation where changes where done, was not working correctly, while this didn't affect any code it's better to have it fixed.
=> Fix propagation of application ranges in formatters

Aztec/Classes/Constants/Metrics.swift, Aztec/Classes/Formatters/TextListFormatter.swift, Aztec/Classes/TextKit/LayoutManager.swift, Aztec/Classes/TextKit/TextList.swift
- Markers are now Right-Aligned
- Added left padding to the List Entries
Closes #388
2. Add a Bulleted / Ordered list
3. Verify that the numbres get right aligned
4. Verify that the List Items get left padding
=> Adjusting Lists Indentation

Example/Example/EditorDemoController.swift
This PR allows the scrolling up and down of the title view with the scrolling of the content.
How to test:
- Check if the scrolling occurs correctly on both Visual and HTML mode
=> Move title up down has content view scrolls.

Aztec/Classes/Libxml2/EditContext.swift
Adding support for the `<del>` tag. Please, verify it does not show up as "Unknown HTML" (`[DEL]`).
=> EditContext: Updatting supported tags

Aztec/Classes/TextKit/TextView.swift, AztecTests/TextViewTests.swift
2. Toggle H1 Style
3. Type `Heading`
4. Switch to HTML mode
5. Verify that the HTML looks as expected
6. Run the Unit Tests and verify everything is okay!
Needs Review: @SergioEstevao  
Closes #404
=> Bugfix: Lost Content

Aztec/Classes/TextKit/HTMLStorage.swift
2. Add regular HTML (`<b>Test</b>`) and verify it gets colorized
3. Add a comment (``) and verify it gets a different color (light gray!)
Needs review: @SergioEstevao 
=> Specific style for HTML Comments

Aztec/Classes/Converters/NSAttributedStringToNodes.swift
Refs #492 
This PR add backs support for video tags on the new structure.
To test:
- Launch the app
- See if video are rendered properly
- Switch to HTML see if video tags show up properly
- Switch back to visual and see if they show up properly
=> Reimplement video tag support

Aztec/Classes/Converters/NSAttributedStringToNodes.swift, Aztec/Classes/TextKit/TextStorage.swift
Ref. #492
Run the Unit Tests, and verify that nothing breaks when comparing `<img src...` strings!
Thanks!!
=> Fixing Image Conversion Tests

Aztec/Classes/Converters/NSAttributedStringToNodes.swift, Aztec/Classes/Libxml2/DOM/Data/ElementNode.swift, AztecTests/Converters/NSAttributedStringToNodesTests.swift
Ref. #492
- Verify that the Unit Tests are okay
- Review the `merge(left:, right:)` logic please!
- Play with the empty editor, and verify that:
- Last Mergeable item should never get merged
- Last LI item is never merged
=> NSAttributedString >> Nodes: Updating Merge Logic

Aztec/Classes/Converters/NSAttributedStringToNodes.swift
Just pushing Diego's beautiful Merge Algorithm!
Ref #492
- Verify the Unit Tests Pass
- Open the Demo App. Verify that the Nested Lists get properly serialized back and forth
=> Nested Lists Support

Aztec/Classes/Converters/NSAttributedStringToNodes.swift
This PR fixes the only unit test that is breaking.
To test:
- Run the app
- See if the demo content shows up correctly
- Run the unit test and see if all pass.
=> Output the extra attributes on a video.

Aztec/Classes/Converters/NSAttributedStringToNodes.swift
=> Wiring HTML Representations during Export

Aztec/Classes/TextKit/TextStorage.swift, Aztec/Classes/TextKit/TextView.swift
Now that we no longer have the DOM tree we no longer need to trigger a DOM change so we can just trigger an update of the layout.
To test:
- Check if unit tests are passing.
=> Stop updating video storage attachment with new one.

Aztec/Classes/TextKit/TextView.swift, Example/Example/EditorDemoController.swift
=> Simplifies undo support and adds redo support.

Aztec/Classes/TextKit/TextView.swift
Fixes #60 
To test:
- Do action on the demo app involving the format toolbar (Bold, italic, insert Image, etc..)
- Check if redo works correctly.
=> Implement undo action for toolbar actions

Aztec/Classes/Converters/HTMLNodeToNSAttributedString.swift, Aztec/Classes/Converters/NSAttributedStringToNodes.swift, Aztec/Classes/Libxml2/DOM/Data/ElementNode.swift, Aztec/Classes/Libxml2/DOM/Data/TextNode.swift, AztecTests/Converters/NSAttributedStringToNodesTests.swift
In this PR we're fixing a glitch in the newlines handling logic, plus, adding a new test, to cover the actual expected behavior.
1. Verify the new unit test is green
2. Enter: `\n\n HELLO \n\n WORLD`, and verify the HTML looks as expected
=> Newlines Kung Fu

Aztec/Classes/TextKit/TextStorage.swift
Title has it
To test:
- Make sure the unit tests run and not fail
- Double check if for some reason we will need this code.
=> Remove unused toggleAttributes method.

Aztec/Classes/Converters/NSAttributedStringToNodes.swift, Aztec/Classes/Formatters/Implementations/VideoFormatter.swift, AztecTests/TextViewTests.swift, Example/Tests/ShortcodeProcessorTests.swift
Fixes #539 
To test:
- Make sure the unit tests are running and passing.
=> Video extra properties are now read and write

Aztec/Classes/TextKit/TextStorage.swift
=> Fix comment that appears to be out of date

Aztec/Classes/Converters/NSAttributedStringToNodes.swift
=> NSAttributedStringToNodes: Removes Inline Element Name

Aztec/Classes/Extensions/Character+Name.swift, Aztec/Classes/Formatters/Implementations/TextListFormatter.swift, Aztec/Classes/TextKit/TextView.swift
1. Launch an Empty Document
2. Add an Ordered / Unordered List
3. Hit `Tab` and verify a new indentation level is added
4. Repeat and verify up to `7` indentation levels are added
5. Try `Shift Tab` and verify an indentation level is removed
6. Try the Shake gesture, and verify the Undo OP works as expected
=> Support for Tab + Shift Tab

Aztec/Classes/TextKit/TextView.swift
- Nuked a dead helper
- Updated private extension method(s) visibility
- Updated several method docs here and there
- No logic was altered at all!
In order to test: please, verify the unit tests work smoothly!
=> TextView: Cleanup

Aztec/Classes/TextKit/TextView.swift
Fixes #443
To test:
1. Enter several empty new lines
2. Toggle a Paragraph Style (Blockquote OR Ordered List OR Unordered List)
3. Hit Backspace
Verify that the Paragraph Style is no longer carried over to the previous line.
=> TextView: Nuking paragraph styles after hitting backspace

AztecTests/TextViewTests.swift
Adds a test for #594.
**To test:**
=> Adds a unit test for shift + enter in lists.

AztecTests/TextViewTests.swift
Adds a unit test for #443.
Run the unit tests, and make sure all succeed.
=> Adds a unit test to prevent regressions on issue 443.

README.md
Fixes #606 
To test:
In GitHub, switch to branch `issue/606-document-carthage-update` and make sure the updated `README.md` file looks good.
=> Document carthage update

Aztec/Classes/TextKit/TextView.swift
(Just by chance) found a dead method. Keeping the house clean!
=> TextView: Nukes dead method

Aztec/Classes/TextKit/TextView.swift, AztecTests/TextViewTests.swift, Example/Example/EditorDemoController.swift
Cleans up a method's declaration and its comments.
**To test:**
Simply run the unit tests.
=> Cleans up a method's declaration.

Aztec/Classes/Converters/NSAttributedStringToNodes.swift, AztecTests/TextViewTests.swift
Fixes #613 
To test: 
- Open the empty demo app
- Add an image to the post
- Switch to html mode
- Add the following attribute to the img tag: class="test"
- Switch to Visual and then back to HTML
- See that class attribute are not duplicated
=> Make sure class attributes are not duplicated.

Aztec/Classes/TextKit/TextView.swift
Fixes #568 
To test:
- Start the demo app with content
- See if links are underlined
- Create new links or edit the existing ones and check if the underlines are draw properly
=> Make link present with underlines.

Aztec.xcodeproj/project.pbxproj, Aztec/Classes/Extensions/NSAttributedString+Strip.swift, Aztec/Classes/TextKit/ImageAttachment.swift, Aztec/Classes/TextKit/MediaAttachment.swift, Aztec/Classes/TextKit/TextView.swift, Aztec/Classes/TextKit/VideoAttachment.swift, AztecTests/TextViewTests.swift
- Run the Unit Tests and make sure everything is green
- Please review the **NSAttributedString+Strip** extension, since that one had to be patched!
=> Merging release 8.1 into develop

.travis.yml, Scripts/build.sh
With so many unit tests, it's a pity we are not running them on a CI system to detect issues early.
To test:
- Push a PR see if travis is triggered.
=> Setup Travis

Aztec/Classes/TextKit/TextView.swift
This PR enables the Prettifier by default.
Fixes #680
Make sure the unit tests remain green!
=> TextView: Pretty Print enabled by default

Aztec/Classes/TextKit/ImageAttachment.swift, Aztec/Classes/TextKit/MediaAttachment.swift, Aztec/Classes/TextKit/TextView.swift, Aztec/Classes/TextKit/VideoAttachment.swift, Example/Example/EditorDemoController.swift
This PR moves several MediaAttachment instance variables over to an *Appearance* instance. No logic has been changed, just shrinking a bit the codebase!
Note: This PR should be reviewed **after** #683 gets merged!
Ref. #7648
- Verify that the unit tests are green
- Try opening a sample post with media. Verify everything looks as expected
- Try pressing over an Image / Video. Verify that the overlay gets properly displayed
- Try adding a new asset. Verify the overlay + progress bar shows up, and gets removed once "the upload" completes.
=> MediaAttachment: Nuking Instance Ivars

AztecTests/TextKit/TextViewTests.swift
Please, verify that the unit tests are (now) green!
Thanks!!
=> TextViewTests: Disabling Pretty Print

Aztec/Classes/Libxml2/DOM/Data/Node.swift
Removes a few lines of ancient code.
Make sure the code compiles.
=> Removes old code.

Aztec/Classes/Libxml2/Converters/In/InNodeConverter.swift, AztecTests/Importer/HTMLToAttributedStringTests.swift
Merges the fixes from [this PR](https://github.com/wordpress-mobile/AztecEditor-iOS/pull/687) into 1.0.0 Beta 10.1
=> Merges some CData fixes into 1.0.0 Beta 10.1

Aztec/Classes/Libxml2/DOM/Data/Node.swift, Aztec/Classes/Libxml2/DOM/Data/TextNode.swift, Aztec/Classes/TextKit/TextView.swift
Fixes several memory leaks and retain cycles in Aztec.
Please feel free to discuss the fixes as much as necessary.
1. Run `develop` with the Leaks instrument.
2. Type into a post a few words, using blockquotes, lists, styles, etc.
3. Switch to HTML mode and back repeatedly.
4. Notice the big amount of leaks and retain cycles reported.
5. Repeat the same process in my branch and notice many of them are gone.
=> Fixes several memory leaks and retain cycles in Aztec.

Aztec/Classes/TextKit/TextStorage.swift
Fixes a retain cycle.
This is the last retain cycle I could find testing the app with instruments.
=> Fixes a retain cycle.

Example/Example/EditorDemoController.swift
Refs #728 
This PR just fixes the layout issues for the editor (html and visual) and title views work on iPhoneX, it not fixes the toolbar issues that will be addressed on a separate PR
To test:
- open the demo editor
- check the layout of the several text components.
- test on iPhoneX and other devices on portrait and landscape.
=> Fix margins on editor.

Aztec.xcodeproj/project.pbxproj, Aztec/Classes/Extensions/UIFont+Traits.swift
Fixes #737 apply bold trait
To test:
1. Type any Chinese characters like `你好`
2. Select them
3. Toggle Bold
=> Fixed Chinese characters bold issue #738

Example/Example/EditorDemoController.swift
Refs #728 
@jleandroperez On the previous PR I missed an update to sync the html view to the visual view.
I also fixed an incorrect inset for the top margin.
To test:
- Run the demo app and check that the layout margins are correct for the right text mode and html mode.
=> Fix some layout issues on the text.

Aztec/Classes/TextKit/TextView.swift, AztecTests/TextKit/TextViewTests.swift
This PR simply adds an extra unit test. The original bug itself is fixed, as a side effect, via #752.
I'm sending this in it's own PR, just to keep things tidy.
Closes #747
Verify that unit tests are green!
=> Zombie H1 Style: Unit Tests!

Aztec/Classes/TextKit/TextView.swift
Fixes #768
To test:
1. Open Editor Demo
2. Delete all contents in TextView (Skip this step if no contents)
3. Continue press backspace key
=> Fix bug #768

Aztec/Classes/TextKit/TextView.swift
=> TextView: Make blockquote border width customizable

Example/AztecUITests/Pages/BlogsPage.swift, Example/AztecUITests/Pages/EditorPage.swift
This PR adds a (required!!) extra delay in a UI test that's breaking in develop.
Zero code from the main app is affected. Just verify that Travis CI is now green.
cc @diegoreymendez @brbrr
=> Fixing UI Tests

Aztec.xcodeproj/project.pbxproj, Aztec/Classes/ElementConverters/Base/AttachmentElementConverter.swift, Aztec/Classes/ElementConverters/Base/ElementConverter.swift, Aztec/Classes/ElementConverters/Implementations/BRElementConverter.swift, Aztec/Classes/ElementConverters/Implementations/FigureElementConverter.swift, Aztec/Classes/ElementConverters/Implementations/GenericElementConverter.swift, Aztec/Classes/ElementConverters/Implementations/HRElementConverter.swift, Aztec/Classes/ElementConverters/Implementations/ImageElementConverter.swift, Aztec/Classes/ElementConverters/Implementations/VideoElementConverter.swift, Aztec/Classes/Extensions/Character+Name.swift, Aztec/Classes/Extensions/NSAttributedString+Attachments.swift, Aztec/Classes/NSAttributedString/Conversions/AttributedStringSerializer.swift
This PR is an attempt at simplifying element conversion to make it easier to maintain and customize (for different purposes).
=> Simplifying element conversion.

Aztec/Classes/ElementConverters/Implementations/FigureElementConverter.swift
Fixes #868
1. Launch Aztec Demo
2. Open the `Editor Demo`
Verify there's order, again, in the universe.
cc @elibud (Thanks in advance!!!)
=> FigureElementConverter: Fixing init recursive loop

Example/AztecUITests/AztecUITests.swift, Example/AztecUITests/FormattingTests.swift, Example/AztecUITests/HighPriorityIssuesTests.swift, Example/AztecUITests/ImagesTests.swift, Example/AztecUITests/LinkTests.swift
Attempt to actually speed up the tests. Before this - App was re-launched for every test(sick!)
Some stats: full suite local run took ~12min
=> Stop re-launching app after each UI test

Aztec/Classes/ElementConverters/Implementations/GenericElementConverter.swift, Aztec/Classes/NSAttributedString/Conversions/AttributedStringSerializer.swift, Example/Example/EditorDemoController.swift
=> Fix a memory leak issue

Example/Example/AttachmentDetailsViewController.storyboard, Example/Example/AttachmentDetailsViewController.swift, Example/Example/EditorDemoController.swift
In this PR we're bringing together Figcaption Edition Support.
Closes #867
1. Launch the AztecExample.App
2. Open **Captions Demo** Sample
3. Double tap over any of the images, and open the **Media Details**
4. Scroll all the way down and edit the Caption Text
5. Press **done** when you're ready
Verify that the Caption onscreen reflects the edited text.
=> Figcaption Edition Support

Example/AztecUITests/AztecUITests.swift, Example/AztecUITests/FormattingTests.swift, Example/AztecUITests/HighPriorityIssuesTests.swift, Example/AztecUITests/ImagesTests.swift, Example/AztecUITests/LinkTests.swift, Example/AztecUITests/Pages/BasePage.swift, Example/AztecUITests/Pages/BlogsPage.swift, Example/AztecUITests/Pages/EditLinkPage.swift, Example/AztecUITests/Pages/EditorPage.swift, Example/AztecUITests/XCTest+Extensions.swift
=> WIP: Fixing UI Tests

Aztec/Classes/NSAttributedString/Conversions/AttributedStringParser.swift
Title has it.
A hotfix for beta 17 will be released once this is in.
=> A bad condition was causing eventual crashes when using header styles.

Aztec/Classes/TextKit/TextView.swift, Example/Example/AttachmentDetailsViewController.swift, Example/Example/EditorDemoController.swift
Fixes undo for captions.
To test:
Just edit a caption in the captions demo and make sure you can undo your edit.
=> Fixes undo for captions.

Aztec/Classes/TextKit/TextView.swift
Adds some notifications that are necessary for attachment captions to trigger save operation in clients.
=> Adds some missing notifications.

Example/Example/SampleContent/gutenberg.html
This PR just updates the sample content for Gutenberg to use the content from [this page](https://testgutenberg.com).
To test:
- Open the demo Gutenberg with content
- See if content displays.
=> Update sample content for gutenberg.

Example/Cartfile.private, Example/Cartfile.resolved
=> Updated Gridicons to 0.16.

Aztec/Classes/Extensions/NSTextingResult+Helpers.swift, Aztec/Classes/Processor/RegexProcessor.swift
Fixes #1048 
To test:
1. Ente Demo -> Video Shortcode Demo
2. Input any emoji before Shortcode
3. Switch to code mode and switch back
=> fixed regular expression range issue

README.md
Improves our documentation:
- Explains the difference between `Aztec` and `WordPressEditor`.
- Updates the minimum system to iOS 10.
- Makes the licensing information about `WordPressEditor` more explicit.
- Make sure this looks right when rendered.
- Make sure there are no typos.
- Make sure the description is accurate and complete.
- Let me know if anything is odd or missing.
=> Updatest README.md for v1.0.

Aztec/Classes/TextKit/MediaAttachment.swift
In https://github.com/wordpress-mobile/WordPress-iOS/issues/10090, we're adding support for importing animated gifs from Giphy to posts. However, Aztec doesn't animate gifs, which results in a slightly odd user experience where it may look like you've just imported a static image. To help with this, this PR adds an optional badge which can be displayed on media attachments. We'll use it in https://github.com/wordpress-mobile/WordPress-iOS/pull/10276 to show a "GIF" badge on gifs.
The badge is intended to closely match `WPBadgeView`, which is used in the media library (as seen in the media picker in the screenshot below).
**To test:**
* In `EditorDemoController,` edit `insertImage(_:)` and add `attachment.badgeTitle = "GIF"` after the attachment is created.
* Build and run
* Insert an …
=> Add optional badge to media attachments

WordPress-Aztec-iOS.podspec, WordPress-Editor-iOS.podspec
Merges release/1.2 back into develop.
=> Merges release/1.2 back into develop.

Aztec.xcodeproj/project.pbxproj, Aztec/Classes/Extensions/String+RangeConversion.swift, Aztec/Classes/TextKit/TextView.swift, AztecTests/Extensions/StringRangeConversionTests.swift, AztecTests/Extensions/StringRangeMultibyteConversionTests.swift
Fixes #1098 
**To test:**
Run the unit tests, before and after!
=> Don’t create ranges intersecting grapheme clusters

Example/Example/EditorDemoController.swift, WordPress-Aztec-iOS.podspec, WordPress-Editor-iOS.podspec, WordPressEditor/WordPressEditor/Classes/ViewControllers/OptionsTableViewController/OptionsTablePresenter.swift, WordPressEditor/WordPressEditor/Classes/ViewControllers/OptionsTableViewController/OptionsTableViewController.swift
Introduces some changes to aid with the transition in WPiOS.
To test this PR make sure to use WPiOS branch: `aztec/integrate-1.3`.
=> Improves the options API to help WPiOS compile.

WordPress-Aztec-iOS.podspec, WordPress-Editor-iOS.podspec
=> Merges release/1.3.2 back into develop.

Aztec/Classes/Formatters/Base/AttributeFormatter.swift, Aztec/Classes/Formatters/Base/FontFormatter.swift, Aztec/Classes/Formatters/Base/ParagraphAttributeFormatter.swift, Aztec/Classes/Formatters/Base/StandardAttributeFormatter.swift, Aztec/Classes/Formatters/Implementations/CodeFormatter.swift, Aztec/Classes/TextKit/TextStorage.swift
Title has it.  This is a small cleanup PR.
1. Launch the editor.
2. Without typing anything enable a blockquote or a list.
Make sure it works.
1. Launch the editor.
2. Without typing anything enable bold / italic / underline.
Make sure it works.
=> Removes a verification that's no longer needed.

WordPress-Aztec-iOS.podspec, WordPress-Editor-iOS.podspec, WordPressEditor/WordPressEditor/Classes/Plugins/WordPressPlugin/Gutenberg/GutenbergOutputHTMLTreeProcessor.swift, WordPressEditor/WordPressEditorTests/WordPressPlugin/Gutenberg/GutenbergInputHTMLTreeProcessorTests.swift, WordPressEditor/WordPressEditorTests/WordPressPlugin/Gutenberg/GutenbergOutputHTMLTreeProcessorTests.swift
Reverts wordpress-mobile/AztecEditor-iOS#1113
=> Revert "Merge Release/1.3.3 into develop"

WordPress-Aztec-iOS.podspec, WordPress-Editor-iOS.podspec
Increases podspec versions to 1.4.2
**To test**
gutenberg-mobile PR https://github.com/wordpress-mobile/gutenberg-mobile/pull/525
WPiOS PR https://github.com/wordpress-mobile/WordPress-iOS/pull/10912
=> Merge 1.4.2 release branch into develop

.travis.yml
Removes `.travis.yml` since we no longer use Travis CI.
=> Removes .travis.yml file.

Aztec/Classes/TextKit/TextView.swift
Fixes #1140 
Fix the update of typing attributes the moment selection is changed.
To test:
- Open the demo app
- Move the cursor/caret position along different styles (bold, italic, link, underlines) etc.
- Check if the update of style on the format bar happens the moment you the cursors moves to a new style position.
@diegoreymendez do you mind to review this? Feel free to do any changes you feel are adequate to it.
=> Fix update of typing attributes when moving range.

WordPress-Aztec-iOS.podspec, WordPress-Editor-iOS.podspec
Just a small improvement to inline documentation.
=> Improve inline podspec documentation

Example/Example/Base.lproj/Main.storyboard, Example/Example/EditorDemoController.swift, Example/Example/ViewController.swift, WordPressEditor/WordPressEditor/Classes/ViewControllers/OptionsTableViewController/OptionsTableViewController.swift
This PR just makes the demo app compatible with dark mode to make it easier to test things while in dark mode.
To test:
- Put the device or simulator in dark mode
- Check if things look ok
- Test the app in light mode to see if nothing was broken too.
=> Update demo for dark mode

Aztec/Classes/TextKit/LayoutManager.swift, CHANGELOG.md, Example/AztecExample.xcodeproj/project.pbxproj, Example/Example/SampleContent/content.html, Example/Example/SampleContent/underline.html, Example/Example/ViewController.swift, WordPress-Aztec-iOS.podspec, WordPress-Editor-iOS.podspec
This is a simple PR to merge the release v1.170 back into develop.
cc @marecar3
=> Merge master back to develop

Aztec/Classes/Extensions/UITextView+Delegate.swift, Aztec/Classes/TextKit/TextViewPasteboardDelegate.swift, Example/Example/EditorDemoController.swift, WordPressEditor/WordPressEditor/Classes/Plugins/WordPressPlugin/Calypso/Embeds/WordPressPasteboardDelegate.swift
Fixes #1189
To test:
- Put a breakpoint on t`extView(_ textView: UITextView, shouldChangeTextIn range: NSRange, replacementText text: String)` on `EditorDemoController`.
- Check if the delegate method is invoked when pastes are done.
=> Check with the delegate if changes are allowed when custom pastes happens.
