- Classes/Public/GUI/FormatBar/FormatBar.swift
- Classes/Public/GUI/FormatBar/FormatBarDelegate.swift
- Classes/Public/GUI/FormatBar/FormatBarItem.swift
- Classes/Public/GUI/FormatBar/FormattingIdentifier.swift
- Classes/Public/TextKit/AztecVisualEditor.swift
- Example/WordPress-Aztec-iOS/EditorDemoController.swift
Removes the Aztec prefix from some classes, since they're already inside the module `Aztec`.
**To test:**
1. Make sure the app builds
2. Make sure the unit tests run properly.
3. Make sure the demo app hasn't lost any functionality.
> Removed the Aztec prefix from some classes.

- Classes/Public/TextKit/AztecVisualEditor.swift
Changes the code a bit to remove an IUO.  The property was only an IUO due to an initialization limitation - the property was trully non-optional and this change helps to better reflect that.
> Changes the code a bit to remove an IUO.

- Example/WordPress-Aztec-iOS/EditorDemoController.swift
Sir, adding few minor touches to the way the enum is used.
Needs Review: @aerych 
P.s.: No need for `break` in Swift enums (behaviour by default)
> EditorDemoController: Updating FormattingIdentifier Enum Usage

- Classes/Public/TextKit/AztecTextStorage.swift
Cleans up trait toggling.  This PR introduces changes to avoid accessing `rawValue` where possible.
Toggle bold, italic, underline, etc... for a range of text.
Make sure that the style is applied if any section of the range does not have the style.
Make sure that the style is removed if the full range has the selected style.
> Cleans up trait toggling.

- Classes/Private/Libxml2/Converters/In/InNodeConverter.swift
- Classes/Private/Libxml2/Data/Node.swift
- Classes/Private/NSAttributedString/Converters/NSAttributedStringToHTMLNode.swift
- Example/Tests/Exporter/OutNodeConverterTests.swift
- Example/Tests/Importer/InNodeConverterTests.swift
Text nodes no longer support attributes, since they really should never have. 😄 
This PR cleans up text nodes to only accept their text content in their initializer.
Build the app.
Run the unit tests and make sure they succeed.
> Text nodes no longer support attributes.

- Classes/Private/Libxml2/Data/Node.swift
- Classes/Public/TextKit/AztecTextStorage.swift
There was an error with the bold editing logic that was causing a crash.
Brings us closer to closing #18.
**How to reproduce the original error:**
1. Launch the editor from `develop`.
2. Select the word "post" from the second line.
3. Make it bold.
4. Now select the full line, including the word "post".
5. Make it bold again.
6. Crash!
Same steps as above, but they should no longer crash and the text should be made bold.
> Fixed an error in the bold-editing-logic.

- Classes/Private/Libxml2/Data/ElementNode.swift
- Classes/Private/Libxml2/Data/Node.swift
- Classes/Private/Libxml2/Data/TextNode.swift
- Classes/Public/TextKit/AztecTextStorage.swift
- Example/Tests/HTML/ElementNodeTests.swift
This PR implements several logical instruments we'll need to update the DOM.
- Block-level node finding basically means we can find all lowest (hierarchy-wise) block-level nodes intercepting a range.
- Splitting nodes and their children using a range.
- Since this PR is mostly non-hooked logical methods, there's not much that can be tested from the GUI yet.
- Run the unit tests and make sure they succeed.
> Implements block-level node finding, and node splitting.

- Classes/Private/Libxml2/Data/ElementNode.swift
- Classes/Private/Libxml2/Data/Node.swift
- Classes/Public/TextKit/AztecTextStorage.swift
- Example/Tests/HTML/ElementNodeTests.swift
It's now possible to apply bold-style to text runs.  It's also smart about how it wraps existing nodes, and how it inserts and breaks the bold styling (where necessary).
Related to #18.
**Known limitations:**
1. It doesn't check for pre-existing bold styling, so it's possible to end up having HTML such as `<strong><b>hello</b></strong>`.
2. Removing bold doesn't affect HTML.
1. Run the editor demo.
2. Select any range of text.
3. Make it bold.  Make sure the HTML is affected by switching to HTML mode.
4. Make sure to run the unit tests too.
> Apply bold style

- Classes/Private/Libxml2/Data/ElementNode.swift
- Classes/Private/Libxml2/Libxml2.swift
- Classes/Public/TextKit/AztecTextStorage.swift
- Classes/Public/TextKit/AztecVisualEditor.swift
- Example/Tests/AztecVisualEditorTests.swift
- Example/Tests/HTML/ElementNodeTests.swift
Implements bold and italic style editing.  This means you should be able to toggle bold and italics on and off, following the editing logic of our previous editor.
Fixes: #18 and #41.
**Known issues:**
- There's an issue related to our HTML importer not ignoring some characters that can cause node duplication if you switch back and forth several times between visual and HTML mode while editing styles.  This will be fixed separately.
> Implements bold and italic styles.

- Classes/Private/Libxml2/Data/ElementNode.swift
- Classes/Private/Libxml2/Data/Node.swift
- Classes/Private/Libxml2/Data/TextNode.swift
- Classes/Public/TextKit/AztecTextStorage.swift
- Example/Tests/HTML/ElementNodeTests.swift
Fixes #46.
Adds text editing support which is reflected in the HTML output.
1. Launch the editor.
2. Edit some text (no styles for the scope of this PR, just text)
3. Switch to HTML mode and make sure the output is as expected.
> Text editing support

- Classes/Private/Libxml2/Converters/Out/OutHTMLAttributeConverter.swift
- Classes/Private/Libxml2/Converters/Out/OutHTMLNodeConverter.swift
Fixes our attributes conversion logic.
When going back to HTML-mode, all attributes were being removed.
1. Launch the demo editor.
2. Go to HTML mode.
3. Make sure all the HTML attributes from the original HTML are showing up.
Props to @SergioEstevao for spotting this issue.
> Fixes attributes conversion.

- Classes/Private/NSAttributedString/Converters/HTMLNodeToNSAttributedString.swift
We were initially storing some custom attributes representing HTML tags in our editor's final visual string.
These are no longer needed as its not through this attributes that we're editing HTML tags.
1. Make sure that when loading a post the styles are still working.
2. Make some simple editions to a post, and make sure when switching to HTML-mode that they still work as they do in `develop`.
3. Make sure the unit tests still run correctly.
> Removes some unused custom attribute information.

- Classes/Private/Libxml2/Data/ElementNode.swift
- Classes/Public/Converters/HTMLToAttributedString.swift
- Classes/Public/TextKit/AztecTextStorage.swift
- Example/Tests/HTML/ElementNodeTests.swift
- Example/WordPress-Aztec-iOS/EditorDemoController.swift
- Example/WordPress-Aztec-iOS/ViewController.swift
Fixes #53.
The editor was breaking bad when trying to start it up without an initial sample content.  This PR fixes it.
This PR also fixes some layout issues - the title field is now visible in both visual and HTML modes.
1. Launch the demo app.
2. There's a new "Empty Editor Demo" option in the main menu.  Pick it.
3. A blank editor window will open up, edit the content.
4. Switch to HTML mode and make sure the HTML is what you'd expect.
> Fixes the editor with no sample HTML

- Classes/Public/TextKit/AztecVisualEditor.swift
- Example/Tests/AztecVisualEditorTests.swift
- Example/WordPress-Aztec-iOS/EditorDemoController.swift
Fixes #58.
1. Run the app.
2. Open the editor with sample content.
3. Select an italic or bold range of text.
4. Switch to HTML mode.
5. Switch back to visual mode and make sure the default font wasn't changed.
> Fixes an issue with the default font being changed.

- Classes/Public/Extensions/NSTextStorage+Helpers.swift
- Classes/Public/Extensions/UITextView+Helpers.swift
- Classes/Public/TextKit/AztecAttachmentManager.swift
- Classes/Public/TextKit/AztecTextAttachment.swift
- Classes/Public/TextKit/TextView.swift
In this PR we're implementing support for:
- Attachment Alignment
- Attachment Resizing
- Dynamic Resize upon Rotation
We're updating the mechanism used by the TextAttachments. Reasoning is as follows:
- At least initially, we'll support **Inline Attachments** and **Above and Below** attachments (say, on its own "Block", replicating Apple Pages's behavior)
- We should be able to delete attachments by means of the *backspace* button
- The Exclusion Paths mechanism is a way of indicating the TextView not to allow text in specific regions. Since the Attachments live within the text itself, and not as an external entity, it's a good idea to deal with this by means of the 'Attachment Bounds'.
For all of the above, in this PR we're shifting from the **Exclusion Paths** mechanism, to something …
> Attachments: Alignment Support Mark II

- Aztec.xcodeproj/project.pbxproj
- Aztec/Classes/Private/NSAttributedString/Converters/HTMLNodeToNSAttributedString.swift
- Aztec/Classes/Public/TextKit/TextAttachment.swift
- Aztec/Classes/Public/TextKit/TextStorage.swift
- Aztec/Classes/Public/TextKit/TextView.swift
- AztecTests/AztecVisualEditorTests.swift
- AztecTests/TextStorageTests.swift
- Example/Example/AttachmentDetailsViewController.swift
- Example/Example/DraggableDemoController.swift
- Example/Example/EditorDemoController.swift
Removes the Aztec prefix from several classes, since we already have the module prefix if we want to use it.
1. Just make sure the app builds and the tests succeed.
> Removes the Aztec prefix from several classes.

- Aztec/Classes/Public/TextKit/TextStorage.swift
- Aztec/Classes/Public/TextKit/TextView.swift
This PR makes some base changes for copy / paste support.
We're replacing:
```switf
override public func replaceCharactersInRange(range: NSRange, withString str: String)
```
with its NSAttributedString counterpart:
```
override public func replaceCharactersInRange(range: NSRange, withAttributedString attrString: NSAttributedString)
```
We're also adding support in the rich text view for pasting styled text (which still doesn't affect HTML).
1. Try pasting styled text in the text view and make sure it works (doesn't update the DOM yet).
2. Edit regular text and make sure everything works as expected.
> Base work for copy / paste support.

- Aztec/Classes/Public/TextKit/TextStorage.swift
Refactored the code to use an enum instead of static type arrays.
> Use enum instead of static arrays for element names and equivalents.

- Aztec.xcodeproj/project.pbxproj
- Aztec/Classes/Public/Extensions/NSRange+Comparison.swift
- AztecTests/Extensions/NSRange_ComparisonTests.swift
Adds a method to compare ranges, that will be used in the upcoming copy / paste support PR.
Since it's not hooked up, please review the unit tests with documentation.
Also run them to make sure they're working as expected.
> Adds a method to compare ranges.

- Aztec.xcodeproj/project.pbxproj
- Aztec/Classes/Private/Libxml2/Data/EditableNode.swift
- Aztec/Classes/Private/Libxml2/Data/ElementNode.swift
- Aztec/Classes/Private/Libxml2/Data/TextNode.swift
- Aztec/Classes/Public/Extensions/NSRange+Comparison.swift
- Aztec/Classes/Public/TextKit/TextStorage.swift
- AztecTests/AztecVisualEditorTests.swift
- AztecTests/HTML/ElementNodeTests.swift
- AztecTests/HTML/TextNodeTests.swift
- AztecTests/TextStorageTests.swift
Related to #75.
Adds initial copy / paste support.  This PR is a bit large but at least half of the added lines are unit tests.
**Known limitations:**
When copy-pasting styles, there's some HTML node duplication (example: `<b>hello</b><b> there</b>`).  This'll be addressed in an upcoming PR, so please ignore for now.
Run the unit tests... then:
1. Launch the example app.
2. Copy styled text.
3. Paste it into the editor.
4. Switch to HTML mode and make sure the tags are there (the supported ones are: bold, strike, underline, italic).
> Adds initial copy / paste support.

- Aztec/Classes/Public/Extensions/NSAttributedString+Lists.swift
- Aztec/Classes/Public/TextKit/TextList.swift
- AztecTests/Extensions/NSAttributedStringListsTests.swift
Super quick rename. Figured out.. `Style` is more appropriate than `Kind`!
Please, verify that Aztec builds, and the unit tests run properly.
Ref. #34
> Renames TextList.Kind > TextList.Style

- AztecTests/HTML/ElementNodeTests.swift
Fixes #90, which was actually fixed by #84. This just adds a unit test
Needs Review: @diegoreymendez
> Add test for crash on newline after div

- Aztec/Classes/Public/TextKit/TextAttachment.swift
- Aztec/Classes/Public/TextKit/TextStorage.swift
- Aztec/Classes/Public/TextKit/TextView.swift
- Example/AztecExample.xcodeproj/project.pbxproj
- Example/Example/EditorDemoController.swift
This PR refactor some code around attachment:
- Refactor the code to insertImage to storage, where it makes more sense.
- Caches the glyph images to improve perfomance while scrolling.
- Refactor method names to be more Swift 3.0 and clear.
- Add support for iPad on the Demo app.
> Improve image handling

- Aztec/Classes/Private/Libxml2/Data/ElementNode.swift
Fixes #112.
Supersedes #104.
**Information:**
When we introduced [this change](https://github.com/wordpress-mobile/WordPress-Aztec-iOS/pull/96/commits/3a9d89b8ac65d97aa8077d2c7aad524a5e2e5e07) we lost some of the logic in the process.  The change was fine, but there was an unintentional change in the logic too.
I reintroduced the lost logic in this PR.
I renamed the condition check parameter to make it clear what it's supposed to do.
Add two images in HTML mode.
Switch to visual mode, and try adding a character between them.
Make sure the app doesn't crash, and editing works.
> Fixes a crash when editing between img nodes.

- Aztec/Classes/Public/TextKit/TextStorage.swift
- Aztec/Classes/Public/TextKit/TextView.swift
- Example/Example/Info.plist
Fixes #110.
Also reduces the amount of code in `setHTML(...)` that is executed inside the dom queue.
**Test 1:**
Repeat the exact steps from [this video](try/fix-image-loading-problem) and make sure the app doesn't crash.
**Test 2:**
Try adding images normally and make sure they're still showing up fine.
> Fixes a bug with the layout code.

- Aztec/Classes/Public/TextKit/TextStorage.swift
Adds copy paste support for links.  Closes #105.
Copy a link and paste it at a different position.
Make sure the link is not lost.
Switch to HTML mode and back to check it.  Also try editing the pasted link.
> Adds copy / paste support for links.

- Aztec/Classes/Public/Extensions/NSAttributedString+Lists.swift
- Aztec/Classes/Public/Extensions/NSRange+Helpers.swift
- Aztec/Classes/Public/Formatters/TextListFormatter.swift
- AztecTests/Formatters/TextListFormatterTests.swift
I've updated Issue #34's **Toolbar** section's Test Cases. You can find Unit Tests for each one of those in `TextListFormatterTests` (each test has a comment referencing to the matching scenario).
Lists should, effectively, behave the same was as Calypso does, as of now.
- Verify that the Unit Tests run correctly
- Manually verify Scenarios 1-7
- Be happy!!
cc @aerych
> Lists: Matching Calypso's Behavior

- Aztec/Classes/Public/TextKit/TextStorage.swift
Inserting images was broken as a result of [this PR](https://github.com/wordpress-mobile/WordPress-Aztec-iOS/pull/123).
This PR fixes it.
Just insert an image and make sure the app doesn't crash.
> Fixes a crashing bug when inserting images.

- Aztec/Classes/Public/TextKit/TextView.swift
- Example/Example/EditorDemoController.swift
Refs #34 
Implements the cursor requirements:
> If the current selection intersects a list marker, adjust the selection so it does not intersect the marker. Move the cursor forward or backward depending on the previous cursor location.
Note: It still allows deletion of part of the markers that will be tackled next.
> Make list markers non selectable

- Aztec/Classes/TextKit/TextView.swift
The cursor caret was disappearing when it was moved to the end of the text on a text view. This PR fix this issue.
How to text:
- Open the demo app
- Select the editor demo
- Move the cursor to the end of the text
- Check if the cursor is visible and on the right position.
> Fix cursor caret on end of text

- Aztec/Classes/Extensions/NSAttributedString+Lists.swift
- Aztec/Classes/Formatters/TextListFormatter.swift
- Aztec/Classes/TextKit/TextStorage.swift
- Aztec/Classes/TextKit/TextView.swift
Refs #146 and #147 
This PR implement support for updating/removing lists while editing text inside the list, specially when deleting around markers and entering new lines.
How to test:
- Start the editor demo
- Create a new ordered list spreading across several lines
- Try the following:
- Break lines in middle and see if the markers are update correctly
- Try Delete marker using the delete key or cutting a selection and see if markers are updated correctly
- Enter two new empty lines in the end of the list and see if the list is interrupted.
- Enter two new empty new lines in a go in the middle of a list and see if the list is split int half
> Update of markers when editing text

- Aztec.xcodeproj/project.pbxproj
- Aztec/Classes/Libxml2/DOM/EditableNode.swift
- Aztec/Classes/Libxml2/DOM/ElementNode.swift
- Aztec/Classes/Libxml2/DOM/Node.swift
- Aztec/Classes/Libxml2/DOM/TextNode.swift
- Aztec/Classes/Libxml2/Descriptors/ElementNodeDescriptor.swift
- Aztec/Classes/Libxml2/DocumentObjectModel.swift
- AztecTests/HTML/ElementNodeTests.swift
This is part of my cleanup work before I start implementing undo/redo.  The reason I'm tackling this is that I want to make sure our methods don't pass an enormous amount of parameters around.
This PR introduces the concept of node descriptors to simplify `ElementNode` searching and creation, while simplifying our calls.
**Known issues:**
While implementing this feature I noticed an issue with styles not being properly removed from the HTML source anymore.  This issue however was not introduced by this PR, so I opened a separate issue to fix it.
I uploaded a video of the problem [here](https://cloudup.com/cngEAn9uNba).
Test the editor normally.  Try to come up with edge scenarios and make sure nothing breaks.
> Adds node descriptors.

- Aztec/Classes/Libxml2/DocumentObjectModel.swift
- Aztec/Classes/TextKit/TextStorage.swift
Fixes the removal of attributes, which was broken in [this PR](https://github.com/wordpress-mobile/WordPress-Aztec-iOS/pull/130).
1. Add and remove styles.
2. Make sure to user partial selection ranges in the tests too.
3. Switch to HTML mode and make sure styles are removing accordingly.
> Fixes attributes removal.

- Aztec/Classes/TextKit/TextView.swift
The code in `refreshListIfNewLinesOn` would crash if you typed return at the
end of the text, as it tried to check for the next character which was out of
bounds.
Needs Review: @SergioEstevao
> Fix crash when typing return

- Aztec/Classes/Libxml2/DOM/ElementNode.swift
Some zero length ranges were causing crashes.
1. Change content.html to have: `<p>123</p>`
2. Select the range (loc: 2, len: 1)... the range for "3"
3. Apply bold
4. Remove bold
Make sure it doesn't crash.
> Fixes a crash with some zero-length ranges.

- Aztec/Classes/TextKit/TextStorage.swift
When trying to remove underline and strikethrough the app was crashing and / or not responding.
1. Run the app in develop, apply underline or strikethrough, remove it.  The app should not respond, or crash.
2. Run the app in this PR, apply underline or strikethrough, remove it.  It should work fine and not crash.
> Fixes a crash with underline and strikethrough.

- Aztec/Classes/Converters/HTMLNodeToNSAttributedString.swift
- Aztec/Classes/Libxml2/Converters/In/InNodeConverter.swift
- Aztec/Classes/Libxml2/DOM/ElementNode.swift
- Aztec/Classes/Libxml2/DOM/StandardElementType.swift
- AztecTests/HTML/ElementNodeTests.swift
- Example/Example/SampleContent/content.html
This PR makes the following changes on the parsing of HTML:
- Removes any extra whitespace ( space, newlines, tabs) between nodes in HTML
- Implicit adds new lines on the visual representation of block elements
How to test:
- Run the demo project and check if the html is properly parsed.
> Improved parsing of html

- Aztec/Classes/Converters/HTMLNodeToNSAttributedString.swift
- Aztec/Classes/Libxml2/Converters/In/InHTMLConverter.swift
- Aztec/Classes/Libxml2/DOM/ElementNode.swift
- Aztec/Classes/Libxml2/DOM/StandardElementType.swift
- Aztec/Classes/TextKit/TextList.swift
#149 
This PR implements the parsing of ol, ul  and li element from HTML to attributed string.
How to test:
- Using the sample content check if the OL and UL shows correctly in the attributed strings
- Try to change the HTML to other valid OL and UL and see if they are parsed correctly
- Switch from visual to HTML and see if list are represented back correctly
Note: This PR doesn't implement DOM interactions on list while using visual mode, so if lists are changed in visual mode they are not reflected to HTML mode.
> Lists: HTML to NSAttributedString support

- Aztec/Classes/Converters/HTMLNodeToNSAttributedString.swift
- Aztec/Classes/Extensions/NSAttributedString+Lists.swift
- Aztec/Classes/Extensions/NSParagraphStyle+Helpers.swift
- Aztec/Classes/Formatters/TextListFormatter.swift
- Aztec/Classes/Libxml2/DOM/StandardElementType.swift
- Aztec/Classes/TextKit/LayoutManager.swift
- Aztec/Classes/TextKit/TextList.swift
- Aztec/Classes/TextKit/TextView.swift
- AztecTests/Extensions/NSAttributedStringListsTests.swift
This PR reimplement the display of list markers using our custom layout manager.
This avoid a lot of special code to handle markers in the content.
How to test:
- Load the demo app
- Try to edit lists of all type and see if the handling is done correctly
- Check if the initial transformation from HTML to AttributedString is correct.
Note: this still doesn't update the DOM when edits happens to the attributed string. So list changes made there will not be reflected to the DOM.
> Reimplement list markers using layout manager

- Aztec.xcodeproj/project.pbxproj
- Aztec/Classes/Extensions/NSAttributedString+Archive.swift
- Aztec/Classes/Extensions/NSAttributedString+Encoding.swift
- Aztec/Classes/Formatters/BlockquoteFormatter.swift
- Aztec/Classes/Libxml2/DocumentObjectModel.swift
- Aztec/Classes/TextKit/ParagraphStyle.swift
- Aztec/Classes/TextKit/TextAttachment.swift
- Aztec/Classes/TextKit/TextList.swift
- Aztec/Classes/TextKit/TextStorage.swift
- Aztec/Classes/TextKit/TextView.swift
Fix #107 and #108
This PR implements support for NSCoding in all our custom attributes to allow them to be copy pasted, inside the editor.
It keeps the original pasteboard in place in order to allow other applications to work correctly when pasting in or copy out.
How to test:
- Copy paste segments of text inside the editor from one place to another and check if the behaviour is correct.
Note: Lists and Blockquotes are still not updating the DOM so changes made are not reflected in the HTML view.
> Fix copy paste for lists, block quotes and images

- Aztec.xcodeproj/project.pbxproj
- Aztec/Classes/Formatters/AttributeFormatter.swift
- Aztec/Classes/Formatters/BlockquoteFormatter.swift
- Aztec/Classes/TextKit/LayoutManager.swift
- Aztec/Classes/TextKit/ParagraphStyle.swift
- Aztec/Classes/TextKit/TextView.swift
- AztecTests/Formatters/BlockquoteFormatterTests.swift
Fix #76 #145 
This PR implements blockquotes using a custom paragraph style
How to test:
- Add and remove block quote styles to ranges of text
- Play around by adding or removing lines
- Test the case where two new lines are inserted in a row and see if block quote is close
Notes:
- Still not implements updates of the DOM nodes
- At the moment it's not possible to combine block quotes and list it's one or the other.
> Implement blockquotes with paragraph style

- Aztec/Classes/Constants/Metrics.swift
- Aztec/Classes/Converters/HTMLNodeToNSAttributedString.swift
- Aztec/Classes/Extensions/NSAttributedString+Lists.swift
- Aztec/Classes/Formatters/AttributeFormatter.swift
- Aztec/Classes/Formatters/TextListFormatter.swift
- Aztec/Classes/TextKit/ParagraphStyle.swift
- Aztec/Classes/TextKit/TextView.swift
- AztecTests/Extensions/NSAttributedStringListsTests.swift
- AztecTests/Formatters/TextListFormatterTests.swift
This PR consolidates our formatters to use the same set of protocols allows to get less code and a more consistent approach to paragraph attributes.
How to test:
- Apply list attributes to paragraph and check if the behaviour is correct.
Note:
This changes some of the requirements of lists defined on #34 :
- Scenario 5: all paragraphs get the style applied
- Scenario 6: all paragraphs get the style applied
- Scenario 7: all paragraphs get the style applied
I actually think this is more consistent behaviour, but lets evaluate. If we really need that behaviour we can add it to the standard attributes protocol.
> Implement the list attributes using the same protocols has block quotes.

- Aztec/Classes/TextKit/TextView.swift
This PR fixes an issue introduced in #171, which caused the Format Bar not to properly reflect the typing attributes, whenever the cursor is within a Blockquote / List / Link.
- Place the cursor over a Blockquote / List / Link.
- Verify that the Format Bar lights up as expected.
Thanks for spotting this Sergio!
> Fixing Format Bar

- Aztec/Classes/TextKit/TextView.swift
This PR adds the ability to Paste and Match the surrounding text's style. What we're doing here is:
- Adding a new `UIMenuController` item
- Simply grabbing the `UIPasteboard`'s string property, if any
- If there's no string property to be found, we'll fallback to the default behavior
1. Launch the Demo App
2. Switch over to Safari / Notes / Reminders
3. Copy some random text
4. Switch back to Aztec's Demo
5. Try the new `Paste and Match Style` action
Note that the original string's style should be striped out.
Needs Review: @diegoreymendez
> Paste and Match Style

- Aztec/Classes/TextKit/TextView.swift
How to test:
- Move the cursor to the end of the text
- Check if the cursor shows up correctly
- Check if the following warnings on the console stop showing up.
```2016-12-12 15:03:16.803 AztecExample[65536:2235645] !!! _NSLayoutTreeLineFragmentUsedRectForGlyphAtIndex invalid glyph index 2146
2016-12-12 15:03:17.211 AztecExample[65536:2235645] !!! _NSLayoutTreeLineFragmentUsedRectForGlyphAtIndex invalid glyph index 2146
2016-12-12 15:03:17.217 AztecExample[65536:2235645] !!! _NSLayoutTreeLineFragmentUsedRectForGlyphAtIndex invalid glyph index 2146
2016-12-12 15:03:17.220 AztecExample[65536:2235645] !!! _NSLayoutTreeLineFragmentUsedRectForGlyphAtIndex invalid glyph index 2146
2016-12-12 15:03:17.220 AztecExample[65536:2235645] !!! …
```
> Check for valid glyph index before trying to access it.

- Aztec.xcodeproj/project.pbxproj
- Aztec/Classes/Extensions/NSAttributedString+Attachments.swift
- Aztec/Classes/Extensions/UIPasteboard+Helpers.swift
- Aztec/Classes/TextKit/TextView.swift
This PR adds support for Image Attachments, when running **Paste and Match Style**.
Closes #172
1. Copy text from Reminders.app
2. Run **Paste and Match Style** in Aztec
3. Verify that the style looks as expected. Compare it with a regular **Paste** OP
1. Copy text from Safari.app. Make sure to include an image asset
2. Run **Paste and Match Style** in Aztec
3. Verify that the style looks as expected. Compare it with a regular **Paste** OP
Needs Review: @diegoreymendez
> Paste and Match: Supporting Images

- Aztec.xcodeproj/project.pbxproj
- Aztec/Classes/Converters/HTMLToAttributedString.swift
- Aztec/Classes/Libxml2/Converters/In/InHTMLConverter.swift
- Aztec/Classes/Libxml2/Converters/In/InNodeConverter.swift
- Aztec/Classes/Libxml2/Converters/In/InNodesConverter.swift
- Aztec/Classes/Libxml2/Converters/Out/OutHTMLConverter.swift
- Aztec/Classes/Libxml2/DOM/CommentNode.swift
- Aztec/Classes/Libxml2/DOM/EditableNode.swift
- Aztec/Classes/Libxml2/DOM/ElementNode.swift
- Aztec/Classes/Libxml2/DOM/Node.swift
- Aztec/Classes/Libxml2/DOM/TextNode.swift
- Aztec/Classes/Libxml2/DOMString.swift
- Aztec/Classes/Libxml2/UndoStack.swift
- AztecTests/Exporter/OutHTMLConverterTests.swift
- AztecTests/Exporter/OutNodeConverterTests.swift
- AztecTests/HTML/ElementNodeTests.swift
- AztecTests/HTML/NodeTests.swift
- AztecTests/HTML/TextNodeTests.swift
- AztecTests/Importer/HTMLToAttributedStringTests.swift
- AztecTests/Importer/InHTMLConverterTests.swift
- AztecTests/Importer/InNodeConverterTests.swift
Relates to #60 
Improves the undo management code to avoid having to propagate `UndoManager` to every single node in the DOM tree.
Unit tests have to provide an empty block, since nodes are not supposed to exist without an undo block (by design, at least in this v1 of undo management - we can review this later on).
- Delete text from single node.
- Move the caret around and repeat.
- Shake to undo any times you deem necessary.
- Check the HTML is as expected.
- Shake to redo any times you deem necessary.
- Check the HTML is as expected.
> Improves the undo manager code.

- Aztec/Classes/Formatters/AttributeFormatter.swift
- Aztec/Classes/TextKit/TextView.swift
1. Launch the editor, and pick the editor demo with content.
2. Select all.
3. Delete (so that the editor is empty).
4. Type a word.
5. Press backspace once.
6. Make sure nothing crashes
@diegoreymendez i've simplified things, and will be introducing further changes in the AttributesFormatter class, so that it's decoupled from the view, in another PR.
Mind taking a look?
Fixes #185
> Fix: Blockquote Crash

- Aztec/Classes/Extensions/NSAttributedString+Lists.swift
- Aztec/Classes/Libxml2/DOM/ElementNode.swift
- Aztec/Classes/Libxml2/DOM/TextNode.swift
- AztecTests/HTML/TextNodeTests.swift
<h3>Details:</h3>
Adds support for undo / redo of text input in single nodes.
Additionally, adds unit tests covering all operations that currently support undo operations.
**Test 1:**
Run the unit tests and make sure none fails.
**Test 2:**
1. Open the editor with content.
2. Insert text in any single node (you can insert in several but the range must not intersect more than one node).
3. Undo.
4. Check against the HTML to make sure everything is synchronized.
> Undo / redo for text input in single nodes.

- Aztec/Classes/Formatters/AttributeFormatter.swift
1. Launch the demo app
2. Open the `Empty Editor Demo` controller
3. Press the **Blockquote** format bar action
Please, verify that there is no selection onscreen.
Closes #189
@diegoreymendez may i bug you with a quick review?
Thanks!
> AttributeFormatter: Removing Blockquote Selection

- Aztec/Classes/TextKit/LayoutManager.swift
1. Launch Aztec's Demo
2. Open the `Empty Editor Demo`
3. Open the Keyboard and press the **Blockquote** action
4. Type a random word
5. Press the **Intro** Key
Verify that the Blockquote effectively grows!
1. Launch Aztec's Demo
2. Open the `Empty Editor Demo`
3. Open the Keyboard and press the **Blockquote** action
4. Type some random text (`Hello`)
5. Delete the text you've just enteded, using Backspace
Verify that the blockquote remains onscreen, even when the last entered character is removed.
Closes #190 
Closes #191
@diegoreymendez **Thank you** for fixing this one!!!. Just pushing your patch, in this PR
> LayoutManager: Blockquote End of Document Fix

- WordPress-Aztec-iOS.podspec
Need 0.4 for shared dependencies on WPiOS. Maybe give this a couple weeks or so:
We can merge this once Swift 3 is fully merged into WPiOS and current working branches are updated. Otherwise, current Swift 2.3 branches of WPiOS will fail to install as they are linking Aztec’s develop branch, which conflicts if Gridicons is updated to 0.4 in develop.
> Bumps Gridicons dependency up to 0.4 for Swift 3.

- Example/Example/EditorDemoController.swift
1. Launch the `Editor Demo` / `Empty Editor`
2. Make sure there's Vertical Scroll (if needed, enter text!)
3. Swipe downwards, over the keyboard
Verify that the Keyboard's Window gets dismissed interactively.
Needs Review: @diegoreymendez
> EditorDemoController: Interactive Dismissal

- Aztec/Classes/Formatters/AttributeFormatter.swift
- AztecTests/Formatters/BlockquoteFormatterTests.swift
- AztecTests/Formatters/TextListFormatterTests.swift
Issue #195 is actually a side effect of #187's patch. Apologies about that, everything was caused by a faulty boundaries check!.
1. Launch the Empty Editor Demo
2. Press the **Blockquote** Format bar button
3. Verify that the blockqute style is onscreen
4. Press **new line**
5. Verify that the blockquote is gone
6. Press **new line** again
Verify that the Blockquote does not show up again.
**Plus:** Run the (new) Unit Tests, and verify they pass!
Closes #195
Thanks Diego!
> AttributeFormatter: Fixing Boundaries Check

- Aztec/Classes/TextKit/TextView.swift
We've got several flows (adding a blockquote // newline while in a blockquote) that cause the "Cursor Missing in Action" scenario.
In this PR we're adding a workaround to, at least, temporarily prevent this bug, until a proper fix is found (OR the SDK gets patched). It's not a fancy snippet, still, gets the job done.
@diegoreymendez May i bug you, yet again? (Thanks!!)
Closes #144
2. Press the Blockquote button
Verify that the cursor is visible and blinking
2. Press the Blockquote button
3. Hit return. The blockquote should expand
Verify that the cursor is, still, visible
2. Press the Blockquote button, and enter a couple lines of text (or empty lines!)
3. Hit backspace to delete one of the new lines
Verify …
> TextView: Missing Cursor Workaround

- Aztec/Classes/Extensions/NSAttributedString+Lists.swift
- Aztec/Classes/Formatters/AttributeFormatter.swift
- Aztec/Classes/TextKit/LayoutManager.swift
- AztecTests/Formatters/BlockquoteFormatterTests.swift
- AztecTests/Formatters/TextListFormatterTests.swift
1. Launch the empty editor demo
2. Hit the `Lists` Format Bar Action
3. Hit `Return`
Verify that the "New Line"'s list marker gets displayed immediately.
Closes #203
Thanks in advance Diego!
> Lists: Rendering Marker at the EOF

- Aztec/Classes/Converters/HTMLNodeToNSAttributedString.swift
- Aztec/Classes/Formatters/AttributeFormatter.swift
- Aztec/Classes/Formatters/BlockquoteFormatter.swift
- Aztec/Classes/Formatters/TextListFormatter.swift
- Aztec/Classes/TextKit/TextView.swift
- AztecTests/Formatters/BlockquoteFormatterTests.swift
- AztecTests/Formatters/TextListFormatterTests.swift
- AttributeFormatter's API has been updated, with Swift 3 in mind
- UITextView is nowhere to be seen, within any of the formatters
- Added some extra method documentation here and there
- Unit Tests updated accordingly
Please, try out `Lists (Ordered / Unordered)` and `Blockquotes`, in any possible scenarios:
- Empty Documents
- At the beginning / middle / bototm of a document
We're aware of several Lists / Blockquote glitches (all of them are filed, to the best of my knowledge).
We'll be addressing them ASAP.
> Decoupling AttributeFormatters from UITextView

- Aztec.xcodeproj/project.pbxproj
- Aztec/Classes/Converters/HTMLToAttributedString.swift
- Aztec/Classes/Libxml2/Converters/In/InHTMLConverter.swift
- Aztec/Classes/Libxml2/Converters/In/InNodeConverter.swift
- Aztec/Classes/Libxml2/Converters/In/InNodesConverter.swift
- Aztec/Classes/Libxml2/Converters/Out/OutHTMLConverter.swift
- Aztec/Classes/Libxml2/DOM/CommentNode.swift
- Aztec/Classes/Libxml2/DOM/ElementNode.swift
- Aztec/Classes/Libxml2/DOM/Node.swift
- Aztec/Classes/Libxml2/DOM/TextNode.swift
- Aztec/Classes/Libxml2/DOMString.swift
- Aztec/Classes/Libxml2/EditContext.swift
- Aztec/Classes/Libxml2/UndoStack.swift
- AztecTests/AztecVisualEditorTests.swift
- AztecTests/Exporter/OutHTMLConverterTests.swift
- AztecTests/Exporter/OutNodeConverterTests.swift
- AztecTests/HTML/ElementNodeTests.swift
- AztecTests/HTML/NodeTests.swift
- AztecTests/HTML/TextNodeTests.swift
- AztecTests/Importer/HTMLToAttributedStringTests.swift
- AztecTests/Importer/InHTMLConverterTests.swift
- AztecTests/Importer/InNodeConverterTests.swift
<h3>Details</h3>
This PR introduces several small improvements to undo / redo.
Improvements:
- We're no longer passing around a closure, but an `EditContext` object which provides access to the undo manager.  This is better because we now have access, from almost anywhere, to the methods [`enableUndoRegistration()`](enableUndoRegistration) and [`disableUndoRegistration()`](https://developer.apple.com/reference/foundation/undomanager/1412239-disableundoregistration).
- I'm expecting the edit context will contain more state information eventually.  If it turns out it doesn't, we can reconsider the architecture.
<h3>Testing</h3>
**Test:**
- Make sure there are no big crashes caused by this PR by randomly testing the editor.
- Not all operations support undo operations, so testing in the …
> Undo / redo improvements

- Aztec.xcodeproj/project.pbxproj
- Aztec/Classes/Constants/HTMLConstants.swift
- Aztec/Classes/Constants/Metrics.swift
- Aztec/Classes/Constants/StringConstants.swift
- Aztec/Classes/Formatters/AttributeFormatter.swift
- Aztec/Classes/Formatters/BlockquoteFormatter.swift
- Aztec/Classes/Formatters/TextListFormatter.swift
- Aztec/Classes/TextKit/TextView.swift
This PR fixes two issues:
- Lists / Blockquotes now can be removed, whenever you're at the end of the document.
- Indentation is being effectively restored, whenever a list / blockquote is removed.
- For readability / consistency's reasons, i've removed few **AttributeFormatter**'s helpers, and implemented custom logic in `CharacterAttributeFormatter` / `ParagraphAttributeFormatter`
- Paragraph Formatters now have a tailored down "Toggle" logic:
- Before anything, we determine if the format should be applied or removed
- We, then, proceed to insert (if needed) a **Zero Width** placeholder. See the `ParagraphFormatter`'s **toggle** method documentation, for more details.
- At last, we return the "Selection Range", if needed.
Please, note that i'll be nuking the entire "Selection Range" …
> Updating ParagraphFormatter(s) Toggle Logic

- Aztec/Classes/Libxml2/DOM/ElementNode.swift
- Aztec/Classes/Libxml2/DOM/Node.swift
- AztecTests/HTML/ElementNodeTests.swift
Adds support for undoing child removal.
Unfortunately testing this straight in the editor is prone to errors.  So the best way to make sure this works as expected is to review the provided unit test and make sure the logic is correct.
> Undo support for removing child nodes.

- Aztec/Classes/Extensions/NSRange+Helpers.swift
- Aztec/Classes/Libxml2/DOM/ElementNode.swift
- Aztec/Classes/Libxml2/DOMString.swift
- Aztec/Classes/TextKit/TextStorage.swift
- Aztec/Classes/TextKit/TextView.swift
Changes made to block quotes update the DOM structure.
@diegoreymendez this is a first stab on updating the DOM when applying block quotes, this is still not final but I would like to have some feedback from you of the changes I made.
My main questions are:
- Should we move the formatters inside the TextStorage class instead of having on the view.
- I'm not very happy with the way we are removing elements from the DOM, you have some comments around about using TextStorage.setAttributes: 
> We should be calculating what attributes to remove in 
>     `TextStorage.setAttributes()` but since that may take a while to implement, we need this workaround until it's ready.
What was your idea there?
> Blockquotes changes update DOM

- Aztec/Classes/TextKit/TextView.swift
In this PR we're updating the mechanism that handles `newline's` (as they are typed by the user!).
Closes #206 
Closes #207 
1. Launch the Empty Editor Demo
2. Press the `Blockquote` / `List` format bar action
3. Press **Return** twice
4. Verify that the Blockquote / List gets closed. 
Note that there's no new line below the cursor. (#207 should be fixed!).
1. Launch the Empty Editor Demo
2. Hit the **Numbered List** Format Bar Action
3. Hit **Return** times *four*
4. Again, press the **Numbered List** action
Verify that a single new item shows up, and that there's no extra new items below the cursor (#206 should be fixed!).
--
Needs Review: @SergioEstevao @diegoreymendez 
Gentlemen, i know you're gonna be refactoring how newlines are being handled. If possible, i'd super appreciate if …
> Formatters: Updating Newline Handling

- Aztec.xcodeproj/project.pbxproj
- Aztec/Classes/Formatters/AttributeFormatter.swift
- Aztec/Classes/Formatters/BlockquoteFormatter.swift
- Aztec/Classes/Formatters/FontFormatter.swift
- Aztec/Classes/Formatters/TextListFormatter.swift
- Aztec/Classes/Libxml2/DOMString.swift
- Aztec/Classes/TextKit/TextStorage.swift
- Aztec/Classes/TextKit/TextView.swift
- AztecTests/Formatters/FontFormatterTests.swift
This PR changes the way we apply bold and italic to the storage, by using CharacterFormatters instead of specific code in the TextView and TextStorage classes.
How to test:
- Apply bold and/or italic to sections of test and see if everything works ok.
- Check if the HTML is updated correctly also.
> Implement bold italic with formatters

- Aztec.xcodeproj/project.pbxproj
- Aztec/Classes/Formatters/AttributeFormatter.swift
- Aztec/Classes/Formatters/StandardAttributeFormatter.swift
- Aztec/Classes/TextKit/TextStorage.swift
- Aztec/Classes/TextKit/TextView.swift
- AztecTests/Formatters/BlockquoteFormatterTests.swift
- AztecTests/Formatters/TextListFormatterTests.swift
- Example/Example/EditorDemoController.swift
This PR implements strike trough and underline using formatters.
It also fix some bugs where applying one character formatter make all the characters in range getting the attributes at the start of the range.
How to test:
- Apply/Remove underline and/or strike trough to sections of text:
- Places without the attribute
- Places where the attribute is partial applied
- Places with the attribute
> Implement striketrough and underline using formatters

- Aztec/Classes/Formatters/AttributeFormatter.swift
- Aztec/Classes/TextKit/TextStorage.swift
- Aztec/Classes/TextKit/TextView.swift
This fix a crash when trying to apply one of the character attributes (bold, italic, ...) to an empty string.
The fix consist on adding back a test for the application range but with using an extra check to see if the formatter allows it. Paragraph Formatters normally allow it because they will add an empty/invisile string.
How to test:
- Start the demo app using the empty option
- Immediately apply one of the character attributes (bold, italic, ..) and see if the app doesn't crash
- Do the same but now with paragraph attributes (blockquote, lists) and see if the app doesn't crash and the attributes are applied (marker on lists, background on block quotes)
> Add property to see if formatter can be applied to empty range.

- Aztec/Classes/Formatters/StandardAttributeFormatter.swift
- Aztec/Classes/TextKit/TextView.swift
- AztecTests/AztecVisualEditorTests.swift
Instead of using multiple methods to check for formatters active, this PR switch the approach to use a data driven approach where the mapping of formatters and typing attributes is done using a dictionary.
How to test:
- Navigate around and see if the toolbar is updated correctly.
- Apply style to new ranges and location and see if the toolbar updates correctly.
> Standardize check for formatting

- Aztec/Classes/TextKit/TextView.swift
1. Launch the Aztec Empty Editor
2. Hit the **Insert Link** button
3. Verify that the app doesn't crash anymore
4. Run the Unit Tests and verify that nothing breaks
> Fixing Insert Link Crash

- Aztec/Classes/Converters/HTMLNodeToNSAttributedString.swift
- Aztec/Classes/TextKit/TextAttachment.swift
- Aztec/Classes/TextKit/TextStorage.swift
- Aztec/Classes/TextKit/TextView.swift
- Example/Example/EditorDemoController.swift
This PR make the definition of the attachment id explicit in order to make it easier to interact and to fix a bug in Swift where the init() method of the base object was being called instead of the Swift init.
It also change a the interface of insertImage to return the attachment object instead of the ID. This is to avoid callbacks to return the attachment.
How to test:
- Launch the demo app
- Check if images are loaded
- Check if images that are inserted load ok.
> Fix some issues around attachment

- Aztec/Classes/TextKit/TextAttachment.swift
The glyph for the attachment was not being marked has invalid when the message changed.
I also found that if a message was set but no progress was set the translucid background was not being set.
How to test:
- On the EditorDemoController.swift change the property value mediaErrorMode = true
- The insert a image to the demo
- Check if the progress and message show correctly.
> Update attachment glyph when message changes

- Aztec/Classes/Libxml2/DOM/ElementNode.swift
**Description:**
Fixes a problem that was causing the editor to crash after inserting an image, removing it, and typing some text.
Fixes #236.
**How to verify:**
1. Launch the empty editor demo.
2. Insert an image.
3. Remove it.
4. Type anything.  The demo should not crash.
**Known issues:**
After following the testing steps, the font is smaller for some reason.  I'm planning to fix this separately since it may be related to other issues I'm dealing with.
> Fixes a crashing bug.

- Aztec/Classes/Libxml2/DOM/ElementNode.swift
- Aztec/Classes/TextKit/TextStorage.swift
- Aztec/Classes/TextKit/TextView.swift
- AztecTests/HTML/ElementNodeTests.swift
This PR fixes a crashing bug that was triggered under certain conditions, when applying combined styles in a text run.
I also took the chance to eliminate some code redundancy and to improve readability.
Fixes #240.
**Test 1:**
**Test 2:**
This test is taken from issue #240 .
- Launch the empty editor
- Type <strong>a<em>a<strike>a</strike></em></strong> (first is bold, second adds italic, third adds strikethrough)
- Swith to HTML Mode.
- Ensure the app doesn't crash (styles can be oddly organized, though).
> Fixes a crashing bug when combining styles.

- Aztec/Classes/Libxml2/DOM/ElementNode.swift
- AztecTests/HTML/ElementNodeTests.swift
<h3>Description</h3>
Fixes a problem that was causing HTML to become excessively fragmented when applying styles.
Fixes #242.
**Test 1:**
1. Run an empty editor.
2. Apply any two styles simultaneously and type: 123
3. Switch to HTML mode and make sure there's almost no HTML fragmentation.
**Test 2:**
1. Run the empty editor
2. Apply styles and write anything you want, randomly.
3. Switch to HTML mode and make sure the HTML has little if any fragmentation.
PS: for all tests keep in mind HTML node fragmentation can still exist in Aztec.  This PR only reduces some very noticeable fragmentation issues we were having.
> Improves readability, fixes a bug.

- Aztec/Classes/TextKit/TextView.swift
This PR fix the issue that after inserting an image to the AztecTextView the style are not followed up after the image.
How to Test:
- On the editor
- Insert the image on a location where styling exists, like bold or italic.
- See if the style continues after the image.
> Apply the typing attributes to the image range.

- Aztec/Classes/TextKit/TextStorage.swift
- Aztec/Classes/TextKit/TextView.swift
- AztecTests/TextStorageTests.swift
- Example/Example/EditorDemoController.swift
This PR adds new callback to the TextView and TextStorage attachments delegates in order to report that attachments are removed.
This is to allow things like cancelation of attachment upload to server.
How to test:
- Insert an image on the post
- Remove the image using the delete on the keyboard.
- check if a callback message is printed on the console saying: "Attachment XXXX removed."
> Add callback to storage notify when attachments are removed.

- Aztec/Classes/TextKit/TextStorage.swift
- Aztec/Classes/TextKit/TextView.swift
- AztecTests/TextStorageTests.swift
- Example/Example/EditorDemoController.swift
This PR add methods to allow removal attachment trough direct method calls.
How to test:
- Open the editor demo
- Tap on an existing image
- On the Action Sheet tap on the Remove Media option
- Check if media is removed.
- Try the same after inserting a media directly
- Check on the html if image was removed.
> Add option to remove attachment trough code.

- Aztec/Classes/TextKit/TextView.swift
- Example/Example/EditorDemoController.swift
<h3>Description</h3>
Updates the tooblar properly when CMD+i, CMD+b, CMD+u are pressed, even if there's no selection.
Fixes #244.
**Test 1:**
1. Open the empty editor.
2. Without typing anything press CMD + b.
3. Make sure the toolbar is updated properly.
**Further tests:**
Try the same as test 1 with CMD + i and CMD + u.
Also try the same as test 1 in the editor with sample content.
> Updates the format bar with keyboard commands.

- Aztec/Classes/Libxml2/Converters/Out/OutHTMLConverter.swift
Since libxml2 is behaving in a not-very-consistent way when formatting HTML, I've disabled its formatter in this PR.
We can work in an HTML beautifier later on, either by figuring out how the libxml2 beautifier works, or by implementing our own.
Switch back and forth between visual and HTML in the editor demo with content, and make sure the HTML representation doesn't change or add newlines.
<h3>Related issues:</h3>
This PR is related to issue #239
> Disable libxml2 formatting of HTML.

- Aztec/Classes/GUI/FormatBar/FormatBar.swift
This (brief!) PR simply marks the Format Bar's delegate as **weak**, in order to patch a retain cycle that's affecting WPiOS.
> FormatBar: Marking Formatter as weak

- Aztec/Classes/NSAttributedString/VisualOnlyElementFactory.swift
This make the visual attributes value to be added has a string in order to be saved and loaded properly on copy paste operations.
> Make the Visual attributes being saved to be string in order to copy/paste to work.

- Example/Example/EditorDemoController.swift
Fixes #250 
How to test:
- Open Safari and open a site
- Tap on share icon on Safary and select the option Copy
- Jump to the Aztec demo app
- tap on the link button in a area where a link doesn't exist
- check that the link URL is pre-filled with the link copied from Safari
> Copy/Paste link from pasteboard to link editor if available.

- Aztec/Classes/Libxml2/DOMString.swift
- Aztec/Classes/TextKit/TextStorage.swift
Fixes #121 
How to test:
- Tap on the image and change its attributes
- Switch to HTML mode
- Go to the img check if the attributes where applied
- On the class attribute add some extra random attributes
- Go to visual mode
- Change the image attributes again using the details view
- Go back to html and check if the changes are there and your custom attributes are still there.
> Fix attachment html attributes set

- Aztec/Classes/Converters/HTMLNodeToNSAttributedString.swift
- Aztec/Classes/Formatters/StandardAttributeFormatter.swift
This PR refactor the HTML parsing code to use formatters for all the HTML elements.
How to test:
- Check that all the HTML was correctly parsed to the Visual mode
- Run the unit tests.
> Refactor HTML parsing to NSAttributedString to use formatters.

- Aztec/Classes/TextKit/TextAttachment.swift
- Example/Example/EditorDemoController.swift
How to test:
- Scroll to an image or insert one
- tap on it and see if the new Pencil icon shows correctly
- Tap out and see if it goes away
> Add possibility to add an overlay icon on top of attachments.

- Aztec/Classes/Libxml2/Converters/In/InNodeConverter.swift
This PR adds checks for empty space on the start of text block.
How to text:
Insert this text on the source code view:
```It has <strong>bold text</strong> and <em>italic text</em> and <del>strikethrough text</del> and <span style="text-decoration: underline;">underlined text</span>.```
Then switch to visual mode and see if the space between bold and italic and strikethrough text are all correct.
> Check for space on start of the text when doing sanitise.

- Aztec/Classes/TextKit/TextStorage.swift
This PR fixes the removal of underline and strikethrough using the keyboard.
Fixes #254.
**Test 1:**
1. Run the unit tests.
**Test 2:**
1. Apply and remove the style for any range of text using CMD + U.
Note: There's still no keyboard shortcut for strikethrough, but the change is the same as in the underline style.
> Fixes keyboard style removal for underline and strikethrough.

- Aztec/Classes/Libxml2/DOM/ElementNode.swift
- Aztec/Classes/TextKit/TextStorage.swift
- AztecTests/HTML/ElementNodeTests.swift
Fixes the DOM synchronization when editing text around the "more" tag.
Fixes #293.
1. Run the app.
2. Place the cursor right before of after the "more" tag.
3. Insert text.
4. Switch to HTML and back.
5. Make sure everything's ok (styles can be slightly off but that's unrelated).
> Fixes editing around the more tag.

- Aztec/Classes/TextKit/TextView.swift
- Example/Example/EditorDemoController.swift
Make sure that all call on text view that change content programmatically trigger a didChange callback of the textview.
How to test:
- Use all the format bar actions on the toolbar
- Confirm that the text Changed Content is printed on the console to confirm that the change happened.
- Test it also by removing an image using the action sheet
- And also test when pressing enter/newlines inside lists or block quotes.
> Trigger textviewDidChange on programmatically content changes

- Aztec/Classes/Libxml2/DOMString.swift
- Aztec/Classes/TextKit/TextStorage.swift
- AztecTests/TextStorageTests.swift
This PR adds code to detect image attachments and applies/insert img elements to the DOM
- Tap on the insert image button
- Wait for image to be inserted
- Switch to HTML mode
- Check that the img tag is present
> Check for attachment and insert image if needed in DOM.

- Aztec/Classes/Libxml2/DOM/ElementNode.swift
- Aztec/Classes/Libxml2/DOM/Node.swift
- Aztec/Classes/Libxml2/DOMString.swift
- Aztec/Classes/TextKit/TextStorage.swift
Fixes adding images to the DOM so that only differences will be applied.  Also removes some weird issues that were causing images to be duplicated.
Fixes #305 
**How to test the previous issue:**
1. Launch the editor in 0.5a4.
2. Open the empty editor demo.
3. Insert and image and type just "a".
4. Switch to HTML mode.
You'll notice the image tag is duplicated.
> Fixes addition of images.

- Aztec/Classes/TextKit/TextView.swift
- AztecTests/AztecVisualEditorTests.swift
Makes sure an empty TextView doesn't crash when inserting a link.  Includes a unit test to make sure there's no regression on this issue.
Fixes #308 
<h3>How to test:</h3>
**Test 1:** Run the unit tests.
**Test 2:**
1. Launch the empty editor demo.
2. Insert a link while the editor is empty.
3. Make sure it doesn't crash.
**Test 3:**
1. Launch the editor demo with content.
2. Select a range of text with a style.
3. Tap the link button and insert a link.
4. Make sure the first stile in the range is kept.  (Other ranges are not kept but that issue was not introduced by this PR).
> Fixes empty TextView crash when inserting a link.

- Aztec/Classes/Libxml2/DOM/ElementNode.swift
- AztecTests/HTML/ElementNodeTests.swift
Fixes some issues that were causing `TextNode` fragmentation.
1. Open the empty editor demo.
2. Type in "Abcdef"
3. In Xcode, place a breakpoint in `ElementNode:1289`
4. In the editor, type 1 last character "g".
Xcode should break.  Type:
`po self`
Make sure the whole text (minus the last "g") is in a single text node.
> Fixes some issues with text fragmentation.

- Aztec/Classes/Converters/HTMLNodeToNSAttributedString.swift
- Aztec/Classes/TextKit/MoreAttachment.swift
- Example/Example/SampleContent/content.html
According to this [documentation](https://en.support.wordpress.com/more-tag/) a more tag only need to start with the ```more``` comment text. All the text after is to be used has the label of the more tag when presenting in the final page.
This PR fix the parsing of the more comment and stores the text after for future editing.
How to test:
- Open the demo app with content
- Check if the more tag is parsed correctly
> Improve more parsing

- Aztec/Classes/TextKit/TextView.swift
This removes some no longer needed code, that was used to keep track off selection when list markers where done using strings directly on the storage instead of using the layout manager.
How to test:
- Compile the project
- Make sure the unit test run correctly
> Remove no longer needed marker selection code.

- Aztec/Classes/TextKit/TextStorage.swift
- Aztec/Classes/TextKit/TextView.swift
- AztecTests/TextStorageTests.swift
- Example/Example/EditorDemoController.swift
This PR changes the attachment interface when doing copy/paste to allows integration on the main WP app and other apps.
For details of why the change check this [PR](https://github.com/wordpress-mobile/WordPress-iOS/pull/6758) on the main WordPress app.
How to test:
- Use the empty demo
- Switch to the Photos a[[
- Copy an image on the Photos app
- Switch to the Aztec demo
- Paste the image
- Check if the integration worked.
> Change attachment interface.

- Aztec/Classes/TextKit/TextView.swift
Fixes #301
To test:
Just paste something and make sure the caret position is moved to the end of the pasted content.
> Updates the caret position after pasting into the editor.

- Aztec/Classes/Formatters/AttributeFormatter.swift
- Aztec/Classes/Formatters/BlockquoteFormatter.swift
- Aztec/Classes/Formatters/HeaderFormatter.swift
- Aztec/Classes/TextKit/TextStorage.swift
- Aztec/Classes/TextKit/TextView.swift
This PR improves and cleanups the AttributeFormatter interface by allowing the following:
- Allows apply and remove of formatters attributes directly, not only by toggling
- Shares more common code between character formatters and paragraph formatters
- Cleans up the code on TextView that was using toggles instead of direct apply and remove of attributes.
How to test:
- Interact with different styles and check if they update correctly
- Try applying and remove newlines inside and around paragraph styles (list, block quotes, headers)
- Check if unit tests pass
> Improve attributes formatter interface

- Aztec/Classes/TextKit/TextAttachment.swift
- Example/Example/EditorDemoController.swift
The position of the text on top of media, was being calculated wrongly when a image overlay was applied.
How to test:
- Start Aztec 
- Insert a media image on the post.
- Tap on the image and see if message and icon overlay show correctly.
> Correct position of message when overlay image is provided

- Aztec/Classes/Extensions/String+RangeConversion.swift
- Aztec/Classes/Libxml2/Converters/In/InNodeConverter.swift
- Aztec/Classes/Libxml2/DOM/ElementNode.swift
- Aztec/Classes/Libxml2/DOM/TextNode.swift
- Aztec/Classes/TextKit/TextStorage.swift
- AztecTests/HTML/ElementNodeTests.swift
- AztecTests/StringRangeConversionTests.swift
This PR adds some more conversion methods between location on NSString and index on String.
How to test:
- Run the unit tests.
- Add and remove emoji:
-  On the end start of styles, 
- On the end/start of lists and blockquotes
- On the end of lines.
- Check if no crashes occur
> More unicode fixing

- Aztec/Classes/TextKit/TextAttachment.swift
- Aztec/Classes/TextKit/TextView.swift
- Example/Example/EditorDemoController.swift
Fixes: #331 
This PR adds the possibility to have padding between images/attachments and other content. This is mainly to avoid that images inserted one after the other are "stitched" together.
This PR also improves interaction when tapping in between the images to allow the cursor to stay in the middle of two images.
How to test:
- Start the empty demo app
- Insert three images one after the other.
- Check if they have margin between them vertically.
- Tap in the middle empty area between the images and check if the caret position is made between the two images.
> Padding between images

- Aztec/Classes/TextKit/TextStorage.swift
- AztecTests/TextViewTests.swift
Fixes a crash that is triggered by entering a newline in an empty editor view.
Fixes #352 
<h3>How to test:</h3>
I added a unit test that triggers the crash.  You can copy the test into develop to see it working.
Run the unit tests and make sure the crash isn't triggered in this branch.
> Fixes a crash with newlines on an empty editor.

- Example/AztecExample.xcodeproj/project.pbxproj
Since we're using the new Xcode's Provisioning Profile setting (matching by name), i'm cleaning up the old school **hash** setting.
Just clean and run the sample app in the device.
Thanks!!
> Nukes Old School Provisioning Profile's Hash

- Aztec/Classes/Extensions/String+RangeConversion.swift
- Aztec/Classes/Formatters/HeaderFormatter.swift
- Aztec/Classes/GUI/FormatBar/FormattingIdentifier.swift
- Aztec/Classes/Libxml2/DOMString.swift
- Aztec/Classes/TextKit/TextView.swift
- Example/AztecExample.xcodeproj/project.pbxproj
- Example/Example/EditorDemoController.swift
- Example/Example/OptionsTableView.swift
Related to #324 
This PR adds support for selection of the header type to apply when using the format toolbar.
It uses a custom input view that allows to choose what header the user wants to apply.
How to test:
- Start the editor with content
- Tap on one of the paragraphs with header
- Tap on the Header button on the toolbar
- Check if the selection made on the input view is correct
- Change the style and see if the style is correct.
> Improve headers toolbar

- Aztec.xcodeproj/project.pbxproj
- Aztec/Classes/Extensions/UIStackView+Helpers.swift
- Aztec/Classes/GUI/FormatBar/FormatBar.swift
- Aztec/Classes/GUI/FormatBar/FormatBarDelegate.swift
- Aztec/Classes/GUI/FormatBar/FormatBarItem.swift
- Aztec/Classes/GUI/FormatBar/FormattingIdentifier.swift
- Example/Cartfile
- Example/Example/EditorDemoController.swift
In this PR we're matching Android's Format Bar behavior:
**[ Scrollable Items ]** < **[ Fixed Items]**
We'll be adding new Format Bar actions in (upcoming) issues. Few notes:
- **Aztec.FormatBar** no longer inherits from **UIToolbar**.
- **Aztec.FormatBarItem** no longer inherits from **UIBarButtonItem**
Needs Review: @diegoreymendez @SergioEstevao 
Thanks in advance gentlemen!!
1. Launch Aztec on an iPhone SE device
2. Verify that the format bar animates, as soon as it becomes visible
3. Verify that the "Scrollable Items" work as expected
4. Rotate the device and verify everything looks right
Re-test on an iPhone 7 // 7 Plus // iPad (Multitasking). Note that whenever the horizontal sizeClass is regular (7 Plus in landscape, iPad fullscreen), the "Scrollable Items" spacing should be …
> Aztec: Format Bar

- Aztec/Classes/TextKit/TextView.swift
Fixes #345 
How to test:
- Tap on insert link button
- Write some link description ( extra points for use emoji on the linked text)
- Check that the cursor moves to the end of the link.
- Try the same with an range selected
- Check if the range stays the same
> Move caret position after inserting a link.

- Aztec/Classes/TextKit/TextStorage.swift
- Aztec/Classes/TextKit/TextView.swift
- AztecTests/TextStorageTests.swift
This PR implements a new API, that would nuke all of the TextAttachments. This is required in order to address [this WordPress iOS Issue](https://github.com/wordpress-mobile/WordPress-iOS/issues/6827).
Please, just run the unit tests, and verify everything looks smooth.
@SergioEstevao although we've discussed about only removing the links tied up to the `Old Selected Site`, since WordPress.com uses links that look like... `lanteanartest.files.wordpress.com`, i'm afraid we can't really match by domain.
For Mark I, let's replicate the old behavior, and build on top of that!
> Remove all Attachments API

- Aztec/Classes/TextKit/TextView.swift
- Example/Example/EditorDemoController.swift
This PR refactors the attachment touch detection to use delegate callback from the UITextView instead of relaying on the client to do that detection. 
This avoid code duplication in users of the library, it also hides implementation details from users of the library ( no need to know about margin, moving cursor and other implementation details).
How to test:
- Start a new post
- Insert multiple images
- Tap on the image and the text outside and see if the interaction works correctly
- Tap on the white space between images and check if the cursor/caret moves to the correct position.
@diegoreymendez mind to have a look on this? The only main architecture question I have is if the new new delegate methods should be part of the current media delegate or I should create a new one. What do you …
> Refactor attachment touch/selection to be part of the text view.

- Example/Cartfile.resolved
- WordPress-Aztec-iOS.podspec
This PR just updates to the latest version of gridicons. No change in terms off icons for Aztec in there but just better to be on the latest.
> Update gridicon to version 0.5

- Aztec/Classes/Converters/HTMLNodeToNSAttributedString.swift
- Aztec/Classes/Extensions/NSAttributedString+Attachments.swift
- Aztec/Classes/GUI/FormatBar/FormattingIdentifier.swift
- Aztec/Classes/Libxml2/DOM/Data/CommentNode.swift
- Aztec/Classes/Libxml2/DOMString.swift
- Aztec/Classes/TextKit/MoreAttachment.swift
- Aztec/Classes/TextKit/TextStorage.swift
- Aztec/Classes/TextKit/TextView.swift
- AztecTests/TextStorageTests.swift
- Example/Example/EditorDemoController.swift
In this PR we're implementing a public API to support the insertion of the More Attachment.
Please, note that (since we're updating the exact same spot), we've patched the `HR` tag "diffing" snippet, since HR tags can be only inserted, not removed, by means of string diffing.
Closes #361
- Verify that all of the unit tests pass
- Verify that pressing the `More` format bar button effectively inserts the more section
- Verify the generated HTML
- Verify that inserting `` in html mode (case insensitive) renders as an attachment, in rich mode
Needs Review: @diegoreymendez + @SergioEstevao
> More: Public API + Format Bar Support

- Aztec/Classes/Converters/HTMLNodeToNSAttributedString.swift
- Aztec/Classes/TextKit/MoreAttachment.swift
- Aztec/Classes/TextKit/TextStorage.swift
- AztecTests/TextStorageTests.swift
We're switching the **more** attachment to lowercase, in order to match Calypso's behavior.
1. Insert a More Tag
2. Verify that the HTML generated is a lowercase `more` comment
3. Toggle back to Rich Mode
4. Verify that the More Tag gets properly displayed
Thanks!
> More: Lowercase Tag

- Aztec/Classes/Libxml2/DOM/Data/ElementNode.swift
- Aztec/Classes/Libxml2/DOM/Logic/DOMEditor.swift
- Aztec/Classes/Libxml2/DOMString.swift
- AztecTests/TextViewTests.swift
Takes care of handling the deletion of newlines that have a list at their right-hand.
Part of #216.
**Test 1:**
Run the unit tests.  I added a specific one for this scenario.
**Test 2:**
1. Use an initial HTML such as: `<p>Hello</p><ol><li>1</li><li>2</li><li>3</li></ol>`
2. Delete the newline between "Hello" and "1"
3. Switch to HTML mode and make sure the output is as expected.
4. Repeat from step 2 for the other list items.
> Deleting visual newlines: right-hand lists.

- Aztec/Classes/TextKit/ParagraphStyle.swift
How to test:
- Just build the project and see if no warning show up.
> Remove compiler warning on Xcode 8.3

- Aztec/Classes/Formatters/BlockquoteFormatter.swift
- Aztec/Classes/Formatters/FontFormatter.swift
- Aztec/Classes/Formatters/StandardAttributeFormatter.swift
- Aztec/Classes/Formatters/TextListFormatter.swift
This property is no longer needed so we can safely remove it from the code.
How to test:
- Run unit test and check that everything is working properly.
- Open the demo app on the mode with content and see if all works ok.
> Remove elementType from Formatters.

- Aztec.xcodeproj/project.pbxproj
- Aztec/Classes/Converters/HTMLNodeToNSAttributedString.swift
- Aztec/Classes/Libxml2/DOM/Data/ElementNode.swift
- Aztec/Classes/Libxml2/DOMString.swift
- Aztec/Classes/Libxml2/EditContext.swift
- Aztec/Classes/TextKit/CommentAttachment.swift
- Aztec/Classes/TextKit/HTMLAttachment.swift
- Aztec/Classes/TextKit/LineAttachment.swift
- Aztec/Classes/TextKit/RenderableAttachmentDelegate.swift
- Aztec/Classes/TextKit/TextStorage.swift
- Aztec/Classes/TextKit/TextView.swift
- AztecTests/HTML/DOMStringTests.swift
- AztecTests/HTML/ElementNodeTests.swift
- AztecTests/TextStorageTests.swift
- Example/AztecExample.xcodeproj/project.pbxproj
- Example/Example/CommentAttachmentRenderer.swift
- Example/Example/EditorDemoController.swift
- Example/Example/HTMLAttachmentRenderer.swift
- Example/Example/MoreAttachmentRenderer.swift
- Example/Example/SampleContent/content.html
This PR implements **Unknown HTML** Support: tags not recognized by Aztec (defined in **EditContext**'s `knownElements` property) will be rendered, in visual mode, as `[HTML]`.
The way "Unknown HTML" attachments get displayed is 100% customizable. We've also revamped the mechanism used to render "Comment Attachments" + "More Attachment". In order to keep the Delegate's fingerprint low, a new protocol was introduced: `TextAttachmentImageProvider`.
Host Application gets to register "Attachment Image Providers", and customize the way attachments will be displayed.
Please, verify the following test scenarios pass, along with the new Unit Tests.
Closes #369 
Needs Review: @diegoreymendez  @SergioEstevao 
🔥 
1. Switch to Raw Edition Mode
2. Enter the following snippet: …
> Unknown HTML Support

- Aztec/Classes/TextKit/CommentAttachment.swift
1. Insert a comment: ``
2. Switch to graphic mode
3. Copy + paste the comment
Verify that the HTML looks a expected.
Closes #406
> CommentAttachment: Fixing Paste

- Aztec/Classes/TextKit/TextView.swift
1. Insert a Horizontal Line
2. Insert a `More` separator
3. Switch to HTML Edition. Insert `<unknown/>`
4. Switch back to Rich Edition mode
5. Select all of the contents
6. Cut the contents + Paste
Verify that everything looks as expected!
Closes #408
Thanks in advance Diego!
> Fix: Cutting Attachments

- Aztec/Classes/Extensions/String+RangeConversion.swift
- Aztec/Classes/Libxml2/DOM/Data/ElementNode.swift
- Aztec/Classes/Libxml2/DOM/Data/TextNode.swift
- AztecTests/StringRangeConversionTests.swift
This PR:
- Adds the method `nsRange(from range: Range<String.Index>)` (closes #412).
- Renames `rangeFromNSRange(_ range: NSRange)` to `range(from range: NSRange)`.
- Separates some previously written unit tests to make them more atomic, and easier to maintain.
- Adds unit tests to tests to make sure the newly added method works correctly.
Running the unit tests should be enough to make sure this PR works as expected.
Make sure to thoroughly review the code changes.
> Conversion of Range<String.Index> to NSRange.

- Aztec/Classes/Formatters/AttributeFormatter.swift
- Aztec/Classes/Formatters/HeaderFormatter.swift
- Aztec/Classes/TextKit/TextView.swift
- AztecTests/TextViewTests.swift
1. Type `Heading`
2. Select the new word and toggle H1
3. Press return
4. Type a two characters
5. Delete one of the two characters
Verify that the HTML generated looks as follows:
`<h1>Heading<br></h1>A`
2. Toggle H1
3. Enter some text. Hit return
4. Enter some text
Verify that the second line is, effectively, in `Paragraph` style
Nukes Zero Width Characters Usage in HeaderFormatter (Ref. #414)
Closes #407
Closes #415
Thanks in advance gentlemen!
:bowtie:
> Bugfix: Broken HTML after H1

- Aztec.xcodeproj/project.pbxproj
- Aztec/Classes/Formatters/PreFormatter.swift
- AztecTests/Formatters/BlockquoteFormatterTests.swift
- AztecTests/Formatters/PreFormaterTests.swift
- AztecTests/Formatters/TextListFormatterTests.swift
2. Switch to HTML Edition
3. Enter `<unknown/>`
4. Switch to Rich Edition
5. With the cursor at the initial position (no need to change anything!) hit backspace
Verify that the `[Unknown]` Attachment does not get removed. Please, repeat all of the steps with `` and `<hr>`.
Closes #410
Thanks gentlemen!
> Fixing PreFormatter Removal

- Aztec/Classes/Extensions/NSAttributedString+Analyzers.swift
- Aztec/Classes/Formatters/AttributeFormatter.swift
- Aztec/Classes/Formatters/TextListFormatter.swift
- Aztec/Classes/TextKit/LayoutManager.swift
- Aztec/Classes/TextKit/TextStorage.swift
- Aztec/Classes/TextKit/TextView.swift
- AztecTests/Extensions/NSAttributedStringAnalyzerTests.swift
- AztecTests/TextViewTests.swift
In this PR we're nuking Zero Width Spaces from the TextLists Formatter.
**All of the Testing Scenarios** are backed up by a unit test. Ain't that cool?
Needs Review: @diegoreymendez @SergioEstevao 
**Diego:** Thanks for the infinite help on this one!!
Closes #421
Ref.: #414
- Yes. We're removing the Zero Width Spaces from the TextLists's inner working. Whenever a bullet must be rendered, and there's no text, we'll be inserting a `\n` character.  
Hook points for this behavior are **insertText** and the formatter's toggle themselves.
- And yes. We're overriding **typingAttributes**, because the `didSet` observer of both, **selectedRange** and **selectedTextRange** is not being always triggered (ie. user touch).
- **TextListFormatter** got a new helper to verify if lists of any kind are …
> Lists: Nuking Zero Width Spaces

- Example/AztecExample.xcodeproj/project.pbxproj
- Example/AztecUITests/AztecUITests.swift
- Example/AztecUITests/Info.plist
- Example/AztecUITests/XCTest+Extensions.swift
- Example/Example/EditorDemoController.swift
This PR adds a suite of UI tests for simple text formatting in the Aztec demo app.
They test each of the text formatting buttons in the toolbar (including the hr and more tags). The tests for lists are currently disabled, pending lists being fully implemented in Aztec.
Pinging @hoverduck and @catehstn for a review. :)
> Add UI tests for simple text formatting

- Aztec.xcodeproj/project.pbxproj
- Aztec/Classes/Converters/HTMLNodeToNSAttributedString.swift
- Aztec/Classes/Formatters/StandardAttributeFormatter.swift
- Aztec/Classes/Libxml2/DOM/Data/StandardElementType.swift
- Aztec/Classes/Libxml2/EditContext.swift
- Aztec/Classes/TextKit/TextStorage.swift
- Aztec/Classes/TextKit/TextView.swift
- Aztec/Classes/TextKit/VideoAttachment.swift
- AztecTests/TextStorageTests.swift
- Example/Example/EditorDemoController.swift
- Example/Example/SampleContent/content.html
Refs #165 
This PR is the first phase of implementing support for videos in the editor, at the moment it only implements the following:
* Parsing of HTML `video` elements. NO support for WP shortcodes `[video] and [wpvideo]`
* Display of videos in the visual editor with inline image with overlay icon
* When tapped on the video image it displays a full screen video player
* Then it can switch back do the editor by tapping on done
How to test:
- Launch the demo app with pre filled content
- Check the if the new video content shows in the visual editor
- Tap on the video and see if the full screen preview shows correctly.
This PR still doesn't implement:
- Insertion of videos through the toolbar
- Allow changes in the visual to be reflected to the HTML
> Video attachments

- Aztec/Classes/Extensions/String+RangeConversion.swift
- Aztec/Classes/Formatters/BlockquoteFormatter.swift
- Aztec/Classes/TextKit/LayoutManager.swift
- Aztec/Classes/TextKit/TextView.swift
- AztecTests/StringRangeConversionTests.swift
- AztecTests/TextViewTests.swift
In this PR we're nuking the Zero Width Character from the Blockquote Formatter's innerworking.
Closes #422
--
2. Toggle the Blockquote format
3. Enter any random text
4. Hit backspace
Verify that the blockquote style is still present.
2. Toggle the Blockquote format
3. Enter any random text
4. Select the end of the document
5. Hit backspace
Verify that the Blockquote gets effectively removed.
2. Toggle the Blockquote format
Verify that a newline is inserted below the blockquote.
2. Toggle the Blockquote format
3. Enter any random text
4. Select the end of the document
5. Hit backspace
6. Hit `\n` and enter any random text
Verify …
> Blockquotes: Nuking Zero Width Spaces

- Aztec/Classes/Formatters/AttributeFormatter.swift
- Aztec/Classes/Formatters/BlockquoteFormatter.swift
- Aztec/Classes/Formatters/HeaderFormatter.swift
- Aztec/Classes/Formatters/PreFormatter.swift
- Aztec/Classes/Formatters/TextListFormatter.swift
- Aztec/Classes/TextKit/TextView.swift
- AztecTests/TextViewTests.swift
This is the (last) PR in the series "Let's stop using the Zero Width Spacing" character. We're replicating the exact same mechanisms (+ battle of unit tests) we've already got for Lists and Blockquotes.
Thaaanks!!!
Closes #420
Closes #414
Verifying this PR is gonna be a bit tricky, since we don't really have (yet) a way to toggle `Pre` blocks. Parsing from HTML is supported, but visual edition hasn't been shipped yet.
In this PR i've added a `togglePre` method, analog to `toggleList` and `toggleBlockquote`. In order to verify this PR, please:
- Make sure the unit tests pass
- Whenever the test scenario indicates "Toggle Pre", please:
A. Switch to HTML
B. Insert `<pre>Payload</pre>`
C. Switch back!
Apologies about this inconvenience. We don't really have a …
> PreFormatter: Nukes Zero Width Spacing character

- Aztec.xcodeproj/project.pbxproj
- Aztec/Classes/Converters/HTMLNodeToNSAttributedString.swift
- Aztec/Classes/Formatters/StandardAttributeFormatter.swift
- Aztec/Classes/Libxml2/DOMString.swift
- Aztec/Classes/TextKit/ImageAttachment.swift
- Aztec/Classes/TextKit/MediaAttachment.swift
- Aztec/Classes/TextKit/TextStorage.swift
- Aztec/Classes/TextKit/TextView.swift
- Aztec/Classes/TextKit/VideoAttachment.swift
- AztecTests/TextStorageTests.swift
- Example/Example/AttachmentDetailsViewController.swift
- Example/Example/EditorDemoController.swift
Refs #165 
This PR refactor TextAttachment to be MediaAttachment. It then creates a ImageAttachment to replace the uses of the previous TextAttachment and it also implements VideoAttachment as a subclass of MediaAttachment.
This change allow sharing of a lot of layout and delegate code between the Image and Video implementations and make simples in the future do changes to both systems.
How to test:
* Run the Demo app
* Check that the image and video of the demo show up correctly
* Test the interactions with the image ( add image, remove image, tap for details)
* Test the interactions with videos ( tap to play, remove)
> Refactor TextAttachment to be MediaAttachment.

- Aztec/Classes/TextKit/TextView.swift
In this PR we're addressing (part of the) "Nuking Zero Width Space" workarounds that had to be implemented, in order to force the LayoutManager to render empty lines, in which there's no actual text.
Please: Verify that the unit tests still pass, and re-verify the Blockquote Test cases (pasting them below for convenience!).
You, sir, are a genius.
Ref. #430
--
2. Toggle the Blockquote format
3. Enter any random text
4. Hit backspace
Verify that the blockquote style is still present.
2. Toggle the Blockquote format
3. Select the end of the document
4. Hit backspace
Verify that the Blockquote gets effectively removed.
2. Toggle the Blockquote format
Verify that …
> Technical Debt: Zero Width Spacing Workarounds-Cleanup

- Aztec/Classes/TextKit/LayoutManager.swift
We were getting a 1px separator between blockquote lines, due to drawing positions not being integer(s).
Thanks in advance Sergio!
Fixes #442
1. Toggle Blockquote
2. Enter several lines of text
Verify that there are no white lines showing up between the Blockquote's Lines.
> Blockquote: Fixing unwanted 1px white separator

- Aztec/Classes/Libxml2/DOM/Data/ElementNode.swift
- Aztec/Classes/TextKit/TextStorage.swift
- AztecTests/TextViewTests.swift
Fixes #457 and another bug with ranges that went unnoticed so far, but could've caused crashes.
To test:
Just run the unit tests, since the case that was breaking is being caught by the provided test.
> Fixes two bugs.

- Aztec/Classes/Converters/HTMLNodeToNSAttributedString.swift
- Aztec/Classes/Extensions/NSMutableAttributedString+ReplaceOcurrences.swift
- Aztec/Classes/Formatters/AttributeFormatter.swift
- Aztec/Classes/Libxml2/Converters/Out/OutHTMLConverter.swift
- Aztec/Classes/Libxml2/DOM/Data/ElementNode.swift
- Aztec/Classes/Libxml2/DOM/Data/Node.swift
- Aztec/Classes/Libxml2/DOM/Data/TextNode.swift
- Aztec/Classes/Libxml2/DOM/Logic/DOMEditor.swift
- Aztec/Classes/Libxml2/DOMString.swift
- Aztec/Classes/Libxml2/Descriptors/ElementNodeDescriptor.swift
- Aztec/Classes/TextKit/TextStorage.swift
- Aztec/Classes/TextKit/TextView.swift
- AztecTests/Formatters/BlockquoteFormatterTests.swift
- AztecTests/TextStorageTests.swift
- AztecTests/TextViewTests.swift
This PR fixes #456.
Lists were losing some of their formatting when combined with multi-line selection and newlines in general.
This PR solves those issues.
**Test 1:**
1. Launch the empty editor.
2. Add an ordered list with 3 lines of text or more.
3. Select part of the list.
4. Convert to unordered list.
5. Switch to HTML and back.  Make sure everything is OK.
**Additional testing:**
Play with lists and try to break them in visual mode.
> Fixes some issues with lists.

- Aztec/Classes/TextKit/TextView.swift
Fixes #462 
To test:
Do some random editing in the editor, involving attachments.
> Removes the attachment attribute style from typingAttributes.

- Aztec/Classes/Extensions/Character+Name.swift
- Aztec/Classes/Libxml2/DOM/Data/ElementNode.swift
- Aztec/Classes/Libxml2/DOMString.swift
- Aztec/Classes/TextKit/TextView.swift
Fixes a crash that was triggered by editing after an unknown tag, at EoF.
Fixes 465 - I can't REF the issue (there seem to be GitHub Issues)
**Test 1:**
Run the unit tests and make sure none was broken.
**Test 2:**
2. Switch to HTML mode, and type: `<asd>`
3. Switch to Visual mode, move the care to the End-of-file position.
4. Type anything.
Make sure the app doesn't crash.
> Fixes a crashing bug related to unknown HTML.

- Aztec/Classes/Converters/HTMLNodeToNSAttributedString.swift
- Aztec/Classes/Extensions/NSAttributedString+Lists.swift
- Aztec/Classes/Formatters/TextListFormatter.swift
- Aztec/Classes/TextKit/LayoutManager.swift
- Aztec/Classes/TextKit/ParagraphStyle.swift
- Aztec/Classes/TextKit/TextStorage.swift
- AztecTests/Extensions/NSAttributedStringListsTests.swift
- Example/Example/SampleContent/content.html
Fixes #448
This PR adds support for nested lists only.
It's still not 100% but I wanted @diegoreymendez and @jleandroperez  have a look on the code until now, and play around to see if they see any major issues.
I will continue to work in fixing the failing unit tests.
To test:
- Run the sample app and check if the content shows correctly
- Interact around the nested lists and see if all is working correctly
- Interact on regular lists and see if all things are still working.
> Support for Nested Lists

- Aztec/Classes/TextKit/TextView.swift
- AztecTests/TextViewTests.swift
Fixes #466
1. Launch the Sample Demo (w/text)
2. With the caret at the initial position (0, 0), hit return
3. Verify that the h1 style is not lost anymore
> TextView: Updates Style Removal Logic

- Aztec/Classes/Extensions/String+RangeConversion.swift
- Example/AztecExample.xcodeproj/project.pbxproj
- Example/AztecExample.xcodeproj/xcshareddata/xcschemes/AztecExample.xcscheme
- Example/Example/EditorDemoController.swift
- Example/Example/SampleContent/content.html
- Example/Example/WordPressShortcode.swift
- Example/Tests/ShortCodeParserTests.swift
Refs #115
This PR is part I of tackling the parsing of shortcodes. 
At the moment it only tackles the parsing and pre-processing of shortcode and the transformation to html. It not tackles the issue of going back from the html to shortcode, that will probably be easier to implement after we have our DOM serializer.
On the example code you can see example of processing of the `[wpvideo]` and `[video]` shortcodes, but the infrastructure is one in a way that any WordPress shortcode can be now implemented.
I have plans to make this architecture more generic and support any kind of pre-processing not limited to shortcodes. So for example we can match URL from youtube,vimeo or and replace it with the corresponding video player code.
But it was already big PR and with enough functionality that …
> Adds a pre-processor for shortcodes

- Aztec/Classes/TextKit/TextStorage.swift
- Aztec/Classes/TextKit/TextView.swift
- AztecTests/TextStorageTests.swift
- Example/Example/EditorDemoController.swift
- Renamed `TextViewMediaDelegate` > `TextViewAttachmentDelegate`
- Renamed textView's `mediaDelegate` > `textAttachmentDelegate`
- Updated `TextViewAttachmentDelegate` method signatures to be Swift 3 compliant
- Updated few `TextStorageAttachmentsDelegate` methods
1. Verify that the unit tests run correctly
2. Run a smoke test over the sample app
> Renaming TextViewMediaDelegate > TextViewAttachmentDelegate

- README.md
Since Aztec is written in Swift, it's a bit different using it in Obj-C land than a traditional Obj-C view. In particular, you have to load in the compatibility headers, which are actually quite a pain to find in the official documentation.
To improve this experience a bit, it'd be nice to add basic usage documentation to the readme. That's what this PR does. :)
Potentially, adding an example Obj-C project (or even just one view) might be useful as well?
> Add basic usage documentation

- Aztec/Classes/Libxml2/Converters/Out/OutHTMLConverter.swift
- Aztec/Classes/Libxml2/DOM/Data/Node.swift
- AztecTests/Exporter/OutHTMLConverterTests.swift
Fixes #479
1. Enter the following HTML: `<h1>Header</h1>Tail`
2. Switch to Rich Mode
3. Switch back to HTML
As a result, you should see the following onscreen:
```
<h1>Header</h1>
Tail
```
Diego, i'm aware this changes after your incoming branch. Will take care of remapping the helpers, the Unit Test will be super helpful not to miss this!
Thanks gentlemen!
> Prettifier: Fixing Blocklevel Element Trailing Newline

- Aztec/Classes/TextKit/MediaAttachment.swift
- Aztec/Classes/TextKit/TextStorage.swift
- Aztec/Classes/TextKit/TextView.swift
- Example/Example/EditorDemoController.swift
Fixes #434 
This PR address two issues:
1. The #434 issue when changing a image src to a non available/incorrect source the image is not updated.
1. When the image or video don't have a src or poster attribute
Both issues are sorted by using a placeholder image to represent them when no media image is available
To test:
Scenario 1:
- Scroll to the image on the demo
- Tap on it
- Change the source of the image to an invalid image
- Make sure the placeholder image shows in place
- Repeat the process but with a valid image
- Check that the image shows up.
Scenario 2:
- Switch to HTML mode
- Remove src from the image tag and poster from the video shortcode
- Switch to visual mode
- Check if the …
> Fix media unavailable issues

- Aztec/Classes/GUI/FormatBar/FormatBar.swift
In this PR we're enforcing the FormatBarItem Buttons to acquire the **full height** of their container views. Prior to this PR, the Buttons were getting a ~ 20x20 size, which made it quite hard to press.
- Verify how the Format Bar looks like on: [SE, iPhone Plus, iPad]
- Toggle Vertical / Horizontal Orientations
- Run a smoke test over the format bar actions.
--
I've tinted the actual button's colors to red, and took few screenshot (prior to this patch, and how it looks afterwards), so that it's easier to spot the 'pressable' areas.
**P.s.:** do not worry, the final version won't look red-dish!
--
--
--
--
-
> FormatBar: Buttons should acquire full height

- Aztec.xcodeproj/project.pbxproj
- Aztec/Classes/Libxml2/DOM/Data/ElementNode.swift
- Aztec/Classes/Libxml2/DOM/Logic/NSAttributedStringToNodes.swift
- Aztec/Classes/Libxml2/DOMString.swift
- Aztec/Classes/TextKit/TextStorage.swift
In this PR we're bringing the tool we've implemented in the `return of the newlines` branch: **NSAttributedStringToNodes**, a tool meant to convert a NSAttributedString into it's HTML representation.
Ref. #492
1. Launch the demo project
2. Try (Simple) styling, and switch to HTML mode
3. Verify the generated HTML matches with the visual style (partially at least!!).
Note: This is a work in progress. Unit Tests + Code Simplification + Proper newline support coming up next.
cc @diegoreymendez  @SergioEstevao
> NSAttributedString to HTML: Phase A

- Aztec.xcodeproj/project.pbxproj
- Aztec/Classes/Converters/HTMLNodeToNSAttributedString.swift
- Aztec/Classes/Formatters/StandardAttributeFormatter.swift
- Aztec/Classes/Libxml2/DOM/Data/ElementNode.swift
- Aztec/Classes/Libxml2/DOMString.swift
- Aztec/Classes/TextKit/TextStorage.swift
- Aztec/Classes/TextKit/TextView.swift
- Aztec/Classes/TextKit/VideoAttachment.swift
- AztecTests/TextViewStubAttachmentDelegate.swift
- AztecTests/TextViewTests.swift
- Example/Example/EditorDemoController.swift
- Example/Example/SampleContent/content.html
- Example/Tests/ShortcodeProcessorTests.swift
Fixes #165  
This PR add support for editing VideoAttachment properties after they are added to the editor. It also makes the changes to be reflected on the HTML.
To test:
- Open the demo controller
- Check if the video display correctly
- Insert a new video using the add media button on the toolbar
- Check that video is introduced correctly and that after the fake upload process is finished, the src URL is set correctly.
> Support updates on video elements

- Example/Example/EditorDemoController.swift
This PR ports this awesome [WPiOS PR](https://github.com/wordpress-mobile/WordPress-iOS/pull/7281) submitted by our beloved @frosty.
From now on, the scrollbar won't appear floating at the middle of nowhere.
1. Launch the Editor
2. Verify that the scrollbar is on the righter-most edge
Thanks sir!
> Adjust text container inset so scrollbar appears at edge of view

- Aztec.xcodeproj/project.pbxproj
- Aztec/Classes/Libxml2/DOM/Data/ElementNode.swift
- Aztec/Classes/NSAttributedString/HTML/HTMLAttributeRepresentation.swift
- Aztec/Classes/NSAttributedString/HTML/HTMLElementRepresentator.swift
- Aztec/Classes/NSAttributedString/HTML/HTMLRepresentation.swift
- AztecTests/NSAttributedString/HTML/HTMLAttributeRepresentationTests.swift
- AztecTests/NSAttributedString/HTML/HTMLElementRepresentationTests.swift
Fixes part of #492.
Adds an HTMLRepresentation protocol, and two classes implementing it so we can attach HTML representation information to `NSAttributedString`.
Simlpy run the unit tests in the following two files:
- HTMLAttributeRepresentationTests.
- HTMLElementRepresentationTests.
> Introducing HTMLRepresentation

- Aztec/Classes/Extensions/NSAttributedString+Lists.swift
- Aztec/Classes/Extensions/NSRange+Helpers.swift
- Aztec/Classes/Extensions/String+RangeConversion.swift
- Aztec/Classes/Libxml2/DOM/Data/ElementNode.swift
- Aztec/Classes/Libxml2/DOM/Logic/DOMEditor.swift
- AztecTests/Extensions/NSAttributedStringListsTests.swift
- AztecTests/Formatters/BlockquoteFormatterTests.swift
- AztecTests/Formatters/TextListFormatterTests.swift
This PR contains no new code. We're just backporting all of the NSAttributedString and NSRange new helpers, developed in the New Lines branch
Run a smoke test over the sample app, and verify it works as before (in the working branch!!)
thanks in advance!
> Backporting AttributedString Helpers

- Aztec/Classes/Converters/NSAttributedStringToNodes.swift
- Aztec/Classes/Libxml2/DOM/Data/Attribute.swift
- Aztec/Classes/Libxml2/DOM/Data/ElementNode.swift
- AztecTests/Converters/NSAttributedStringToNodesTests.swift
In this PR we're implementing Merge-to-Left: as we parse different Paragraphs, we're now merging N and N-1 nodes, as long as `canMergeChildren`'s `Node` (new helper) returns true.
Pendings:
- Newlines Logic
- Merge Explicit Unit Tests
- (And of course!) revisit the Merge Logic
Ref #492
1. Verify the Unit Tests and make sure *NSAttributedStringToNodesTests* are green.
2. Try inserting a List with multiple items, and verify the `LI` items get grouped together under the same `OL / UL`
> HTML Generation: Merging to Left!

- Aztec/Classes/Constants/Metrics.swift
- Aztec/Classes/Formatters/BlockquoteFormatter.swift
- Aztec/Classes/Formatters/HeaderFormatter.swift
- Aztec/Classes/Formatters/TextListFormatter.swift
- Aztec/Classes/TextKit/LayoutManager.swift
- Aztec/Classes/TextKit/ParagraphStyle.swift
This PR refactor the way formatters applies styles to the paragraphs.
Instead of directly changing values on the ParagraphStyle, the formatters only set the corresponding property to set the style, and then the ParagraphStyle itself decides how this should be applied.
This allows a better separation of the style metrics and the formatters. It also permits better combination of styles like Headers+Blockquotes or List+Blockquotes.
To test:
- Check if the the properties are still applied properly on the paragraphs
- Check if using the toolbar to set paragraph styles still work correctly
> Refactor style application

- AztecTests/TextStorageTests.swift
In this (super small PR) we're updating a Unit Test condition. In order to test it, please, verify `testBlockquoteToggle2` is green.
Ref #492 
1. Type `Hello`
2. Enter newline
3. Toggle Blockquote
4. Type `World`
Verify that the generated HTML looks like: `Hello <blockquote>World</blockquote>`. No newline in beteween!
> Fix: testBlockquoteToggle2 Test

- Aztec/Classes/Converters/NSAttributedStringToNodes.swift
- Aztec/Classes/Extensions/NSAttributedString+Lists.swift
- Aztec/Classes/Formatters/TextListFormatter.swift
- Aztec/Classes/TextKit/Header.swift
- Aztec/Classes/TextKit/LayoutManager.swift
- Aztec/Classes/TextKit/ParagraphStyle.swift
- Aztec/Classes/TextKit/TextList.swift
Fixes #512 
This PR just renames the `textLists` property in `ParagraphStyle` to `lists`
To test:
- See if the demo content shows correctly
- Select text with a list on it
- Tap copy
- And paste to another part
- See if all went well.
- See if unit tests are not affected
> Rename the textLists attribute of ParagraphStyle to lists.

- Aztec/Classes/TextKit/TextStorage.swift
- AztecTests/TextViewTests.swift
This PR removes some preprocessing for paragraphs that is no longer needed.
To test:
- run the demo app and see that all shows up correctly.
- check if unit tests are ok.
> Remove preprocessing of paragraphs.

- Aztec.xcodeproj/project.pbxproj
- Aztec/Classes/Converters/HTMLNodeToNSAttributedString.swift
- Aztec/Classes/Converters/NSAttributedStringToNodes.swift
- Aztec/Classes/Libxml2/DOM/Data/ElementNode.swift
- Aztec/Classes/NSAttributedString/HTML/HTMLAttributeRepresentation.swift
- Aztec/Classes/NSAttributedString/HTML/HTMLElementRepresentator.swift
- Aztec/Classes/NSAttributedString/Styles/UnsupportedHTML.swift
- AztecTests/Converters/HMTLNodeToNSAttributedStringTests.swift
Best Issue Title *Ever*. In this PR we're implementing a new NSAttributedString attribute, responsible of holding references to the HTML Entities, present in the original HTML, that aren't directly editable, but should be maintained.
Unit Tests coming up in a different PR.
Ref. #521 
2. Switch to HTML mode
3. Enter `<span class="i am"><span class="evil>YEAH!</span></span>`
4. Switch back to Rich Mode
5. Switch back to HTML mode
Verify that the SPAN entities are there.
> Supporting Unsupported HTML

- Aztec/Classes/GUI/FormatBar/FormatBar.swift
This PR retains the expanded / collapsed state of the format bar between usages.
To test:
* Open an editor, expand the toolbar.
* Leave the editor, come back to the editor – check the toolbar is still expanded.
* Collapse the toolbar, leave the editor, come back to the editor – check the toolbar is still collapsed.
Needs review: @SergioEstevao
> FormatBar: Remember expansion state between usages

- Aztec/Classes/GUI/FormatBar/FormatBar.swift
Simple, does what it says in the title. The format bar now has a divider on the bottom as well as the top. This helps to visually separate it from the heading / list tables below.
To test:
* Build and run the demo app, check you can see the divider and it looks correct.
Needs review: @SergioEstevao
> FormatBar: Add bottom divider

- Aztec/Classes/GUI/FormatBar/FormatBar.swift
- Example/Example/EditorDemoController.swift
This PR makes a couple of small tweaks to the way format bars are used in the demo. Instead of creating one per text view, we're now sharing one between them. I've also made a few changes to the way items are disabled in the bar.
To test:
* Open the sample editor and test tapping between the different text views – title and rich text view. In the title view, all buttons in the toolbar should be disabled.
* In the rich text view, try toggling to HTML mode, and back again. In HTML mode, only the HTML button should stay enabled. When you toggle it back off, all buttons should become enabled again.
Needs review: @SergioEstevao
> FormatBars: Consolidating multiple bars

- Aztec/Classes/GUI/FormatBar/FormatBar.swift
- Aztec/Classes/GUI/FormatBar/FormatBarDelegate.swift
- Example/Example/EditorDemoController.swift
- Example/Example/OptionsTableView.swift
Follows on from #527. This PR displays the Header and List pickers as popovers on iPad. We're doing it at any size class, because it looks fine even when the view is compact, and even if the app is narrow the keyboard is still full width.
It's not my favourite implementation ever, but I feel like popovers are only a stop gap. I'd prefer to use custom views in the future and not actually 'present' another view controller. Let me know what you think.
To test:
* Run the demo app on iPad, and try using the heading and list menus. They should reflect the current state, and dismiss if you tap away from them or interact with the format bar. 
* They should work correctly no matter what size the app is at, and they should dismiss if you rotate the device.
Needs review: @SergioEstevao or …
> FormatBar: Add popovers for pickers on iPad

- Aztec/Classes/GUI/FormatBar/FormatBar.swift
- Aztec/Classes/GUI/FormatBar/FormatBarDelegate.swift
- Example/Example/EditorDemoController.swift
This PR adds a delegate method to the FormatBar to inform of changes to the overflow items visibility.
Required for https://github.com/wordpress-mobile/WordPress-iOS/issues/7408
To test:
* Check the code
* Build and run the demo app and open the editor with sample content
* Ensure a message gets logged to the console when you expand / hide the overflow items in the format bar.
Needs review: @SergioEstevao
> FormatBarDelegate: Added overflow toggle state change callback

- Aztec/Classes/GUI/FormatBar/FormatBar.swift
This PR fixes a small visual bug when the format bar was shown in an initially expanded state, where the overflow toggle button wasn't being rotated.
To test:
* Run the sample app, open the editor
* Expand the bar, notice the toggle flips to a vertical orientation
* Exit the editor
* Re-open the editor, and scroll to the end of the format bar. The toggle should still be in a vertical orientation. If you tap it, it should rotate to horizontal when the items are hidden.
* (Prior to this PR, when you reopened the editor, the toggle would be in the horizontal position and no animation would take place)
Needs review: @SergioEstevao can I bug you again?
> FormatBar: Fix overflow toggle orientation on first appearance

- Aztec/Classes/TextKit/LayoutManager.swift
Closes #546
1. Toggle HTML Mode
2. Write:
```
<ol>
<li><strong>Revenue:</strong> &#xA0;&#x1F4B0;</li>
<li><strong>Growth:</strong> &#xA0;&#x1F4C8;</li>
<li><strong>Engagement:</strong> &#xA0;&#x1F48D;</li>
</ol>
```
3. Switch to Rich
4. Verify the bullets are actually there!
> LayoutManager: Wiring the *right* analyzer

- Aztec/Classes/Extensions/Character+Name.swift
- Aztec/Classes/Libxml2/Converters/In/InNodeConverter.swift
Fixes #550 
To test:
- Edit the demo content .html file.
- Add a single line with non-encoded nbsp (`U+00A0`) characters between chunks of text.
- Run the app and load the demo with content.
Please DM me for a sample string, as it seems copying it here makes the string lose its `nbsp`s.
> No longer removes non-encoded nbsp; characters from input.

- Aztec/Classes/TextKit/LayoutManager.swift
Fixes #549
1. Enter the following HTML
```
<ol>
<li>Asdasd &#x1F1E6;&#x1F1E9;</li>
<li>&#x1F1E6;&#x1F1F4;</li>
<li>&#x1F1E6;&#x1F1F2;</li>
</ol>
```
2. Switch to Rich Mode
3. Verify everything looks as expected!
Isn't *Obliterating* an awesome word?
> LayoutManager: MarkerItem breaks with Emoji Fonts

- Aztec/Classes/TextKit/LayoutManager.swift
- Aztec/Classes/TextKit/ParagraphStyle.swift
This PR draws a background similar to block quote for pre elements.
It copies the style used in Calypso
To test:
- Scroll to the text with the header Pre Formatted code
- Check if the background is correctly drawn.
> Draw HTML Pre background.

- Aztec.xcodeproj/project.pbxproj
- Aztec/Classes/Converters/HTMLNodeToNSAttributedString.swift
- Aztec/Classes/Converters/NSAttributedStringToNodes.swift
- Aztec/Classes/Extensions/Character+Name.swift
- Aztec/Classes/Extensions/String+EndOfLine.swift
- Aztec/Classes/Formatters/Base/ParagraphAttributeFormatter.swift
- Aztec/Classes/Libxml2/Converters/In/InNodeConverter.swift
- Aztec/Classes/Libxml2/Converters/Out/OutHTMLConverter.swift
- Aztec/Classes/Libxml2/DOM/Data/StandardElementType.swift
- Aztec/Classes/TextKit/LayoutManager.swift
- Aztec/Classes/TextKit/TextView.swift
- AztecTests/Converters/NSAttributedStringToNodesTests.swift
- AztecTests/StringEndOfLineTests.swift
- AztecTests/TextViewTests.swift
Fixes #553 
To test:
* Launch the Demo with data, and make sure the lists look fine.
* Launch the empty Demo, and insert a list.
* Pressing shift + enter should no longer break paragraphs, and produce `<br>` elements in the HTML.
> Shift + enter no longer breaks paragraphs.

- Aztec/Classes/TextKit/MediaAttachment.swift
Fixes #545 
To test:
- Start the demo app with empty content
- Toggle a list
- Insert an image
- Check if the image is draw correctly inside the aztec textview
> Images drawn inside the editor when lists are applied

- Aztec/Classes/TextKit/TextStorage.swift
- Aztec/Classes/TextKit/TextView.swift
- AztecTests/TextStorageTests.swift
- AztecTests/TextViewTests.swift
- Example/Example/EditorDemoController.swift
This PR refactor the code to insert media attachments to a central method. This has the following advantages:
- central place for insertion code of attachment
- undo/redo implemented in a single place for attachment
- notification of changes done in a single place for attachment
Another feature added to match calypso is that you can now select a range of text and press + to replace it with a image or video.
If this is ok  a follow up of this PR could also refactor the following insertions:
- Horizontal Ruler Attachment
- More Attachment
- Comment Attachment
- Raw HTML Attachment
To test:
- Make sure the tests are running and passing
- Insert image and videos on the content
- Try to insert image or videos by selecting a range first
> Refactor insertion of Media attachments to use single insert method.

- Aztec/Classes/GUI/FormatBar/FormatBar.swift
- Example/Example/MoreAttachmentRenderer.swift
This PR makes a few improvements to right-to-left support for the format bar. Previously, the overflow toggle was hidden, so it was impossible to show the extra items in the bar. Now it should be visible and usable:
There is still an issue where the items in the bar are left aligned instead of right aligned, but I haven't been able to get to the bottom of that yet. At least, with this PR, the entire bar becomes usable. Hopefully we can address the alignment in a future PR.
Needs review: @jleandroperez
> FormatBar: A couple of RTL improvements

- Aztec/Classes/TextKit/TextView.swift
Fixes #564 
To test:
- Start the app
- Go to demo
- Insert a link on a zero length range
- Tap undo
- Check that link is gone.
Note: I found that undo of typing attributes on text that is empty after undo is not working properly. but that will need a separate PR
> Use the correct range for undo.

- Aztec/Classes/Converters/NSAttributedStringToNodes.swift
- Aztec/Classes/Libxml2/DOM/Data/ElementNode.swift
- Aztec/Classes/Libxml2/DOM/Data/Node.swift
- AztecTests/Converters/NSAttributedStringToNodesTests.swift
This PR also contains the changes introduced in #560:
- NSAttributedStringToNodes Internal API has been updated, so that Elements are first extracted, and Branches assembled 'by hand'
- Sort + Merge algorithm has been implemented, so that we minimize fragmentation (Left to Right analysis).
- Plus: Since i was around, added support to serialize Pre elements (+ Unit Tests!!)
1. Run the unit tests
2. Run a smoke test over the Out Converter
3. Add a `Pre` element, verify it gets serialized properly
4. Try snippets that should generate fragmentation. Few samples below!
```
<u><b>Bold</b>Underlined<i>Italics</i></u>
```
```
<u><i>1</i></u>
<u><b><i>2</i></b></u>
<u><b>3</b></u>
<u><b>4</b></u>
```
> Obliterating Fragmentation: Mark I + II

- Aztec/Classes/TextKit/MediaAttachment.swift
Fixes #545 
To test:
- Start the empty demo app
- Insert one image on the content
- On the same line insert another image
- Check that both image show up 
- add a list style
- Check that both image show up inside the textview bounds
-  add a block quote style
- Check that both image show up inside the textview bounds
> Fix image drawing on paragraphs with list and/or block quotes

- Aztec/Classes/TextKit/TextStorage.swift
- Aztec/Classes/TextKit/TextView.swift
- AztecTests/TextStorageTests.swift
- AztecTests/TextViewStubAttachmentDelegate.swift
- AztecTests/TextViewTests.swift
- Example/Example/EditorDemoController.swift
Refs: #317 
This continues the refactor of attachment methods on TextView to make them use a single method.
This make it easier to control undo/redo and delegate callbacks.
To test:
- Make sure unit tests are running ok
- On the demo app try to insert comment/more and horizontal ruler
- Undo redo those actions.
> Refactor attachment insert part 2

- Aztec/Classes/GUI/FormatBar/FormatBar.swift
- Example/Example/EditorDemoController.swift
This PR adds keyboard shortcuts to the editor
To test:
- Run the test app on the iPad
- On the editor tap on the CMD key
- See if shorchuts show in screen
- Try the shortcuts and see if they are working correctly.
> Add keyboard shortcuts.

- Aztec/Classes/TextKit/TextView.swift
- AztecTests/TextViewTests.swift
Refs #485 
This PR makes sure the typing attributes are applied when inserting attachments (media, more, hr) to the content.
To test:
- Insert a image on the start of the content
- Write just after image and see if the text has the correct style.
> Make sure attributes are applied to attachment insertions/replacements.

- Aztec/Classes/TextKit/MediaAttachment.swift
- Aztec/Classes/TextKit/TextView.swift
Fixes #570 
This PR adds code to detect touch only then actual image representation of attachment is pressed.
To test:
- Check the original issue steps to reproduce it
> Only detect touches on media if the actual image is tapped.

- Aztec/Classes/Extensions/UIFont+Emoji.swift
- AztecTests/TextViewStubAttachmentDelegate.swift
- AztecTests/TextViewTests.swift
Refs #485 
This PR adds another check for alternative emoji font when not using the standard system font (San Francisco UI)
To test:
- Make sure unit tests are ok
- Insert an emoji anywhere in the text
- Make sure that characters written after have the correct style
> Add an extra check for alternative emoji font.

- Aztec/Classes/TextKit/TextStorage.swift
- Aztec/Classes/TextKit/TextView.swift
- AztecTests/TextStorageTests.swift
- AztecTests/TextViewTests.swift
This PR implements the capability of undo redo when removing an attachment by pressing on it and select the option remove.
To test:
- open the demo with content
- scroll to the coyote image
- Tap on it
- Tap again
- Select Remove Media
- Check if image was removed
- Tap Undo 
- Check if image comes back again.
> Implement undo and redo when removing attachments by code.

- WordPress-Aztec-iOS.podspec
Closes #577 
This issue resulted from the Removal of Gridicons done here: https://github.com/wordpress-mobile/AztecEditor-iOS/pull/559
The resources where not added to the pod, so this made application that used the pod crash when trying to access a resource.
To test:
- The easiest way to test this is to try this version directly on the main WPiOS app.
Note: @diegoreymendez because we are using CocoaPods should convert the Example app to use CocoaPods instead of Carthage? This will make it easier to find this kind of issue.
> Add resources to pod spec file.

- Aztec/Classes/GUI/FormatBar/FormatBar.swift
- Aztec/Classes/GUI/FormatBar/FormatBarItem.swift
I hope this is okay coming into the release branch, but it's just a tiny fix to the colours of the format bar items. Previously disabled items had the wrong tint colour (iOS was adding its own adjustments), and we weren't including the overflow toggle button when setting colors.
To test:
* Build and run, open Aztec. Enter HTML mode, and check:
* The disabled items and the overflow toggle (`...`) should match in color
* They should match the 'after' color in the screenshot above.
Needs review: @SergioEstevao 
> Fix format bar colors

- Aztec/Classes/Extensions/Character+Name.swift
- Aztec/Classes/Formatters/Implementations/TextListFormatter.swift
- Aztec/Classes/TextKit/TextView.swift
Backports #584 into Beta 6
1. Launch an Empty Document
2. Add an Ordered / Unordered List
3. Hit `Tab` and verify a new indentation level is added
4. Repeat and verify up to `7` indentation levels are added
5. Try `Shift Tab` and verify an indentation level is removed
6. Try the Shake gesture, and verify the Undo OP works as expected
> Backport: Support for Tab + Shift Tab

- Aztec/Classes/Extensions/String+EndOfLine.swift
- Aztec/Classes/TextKit/TextView.swift
Fixes #594 
**Test 1:**
Build and run the unit tests.
**Test 2:**
- Run the empty demo.
- Create a list.
- Press shift + enter while the carete is both at end-of-file and end-of-list.
- Make sure the list style is not removed.
> Shift + ENTER no longer breaks lists at EoF.

- Aztec/Classes/Libxml2/DOM/Data/ElementNode.swift
- Aztec/Classes/Libxml2/DOM/Data/Node.swift
- Aztec/Classes/Libxml2/DOM/Data/StandardElementType.swift
- Aztec/Classes/Libxml2/DOM/Data/TextNode.swift
- AztecTests/TextViewTests.swift
Fixes some obscure issues when editing HTML outside of block-level elements.
**To test:**
1. Using the HTML input:
```text
<br><br><h1>Test</h1>
```
2. Switch to visual mode and back.
Expected output: same as the input (no `<br>` nodes should be removed).
> Fixes some obscure issues when editing HTML outside of block-level elements.

- Aztec/Classes/TextKit/MediaAttachment.swift
- Aztec/Classes/TextKit/TextStorage.swift
- Aztec/Classes/TextKit/TextView.swift
- Aztec/Classes/TextKit/VideoAttachment.swift
- AztecTests/TextStorageTests.swift
- AztecTests/TextViewStubAttachmentDelegate.swift
- Example/Example/EditorDemoController.swift
This is the first PR in a series of (upcoming) Attachment-Y updates. We're doing a bit of a cleanup in the `TextViewAttachmentDelegate`:
- The method `textView:attachment:imageAtURL:onSuccess:onFailure:` was returning an *image placeholder*
- We also had a specific method to retrieve the placeholder: `textView:placeholderForAttachment`
The `-> UIImage` placeholder has been removed from the first method, and thus, we're routing all of the placeholder-Y requirements via it's specific method.
- Ensure the Unit Tests run correctly
- Verify that the Editor Demo properly displays the Video / Image placeholders
cc @diegoreymendez @SergioEstevao 
> TextViewAttachmentDelegate: Cleanup

- Aztec/Classes/TextKit/TextView.swift
Touch Detection for non MediaAttachment's is broken (since `attachmentAtPoint` is overriding the attachment's width/height with zero, and thus, incorrectly returning nil). In this brief PR we're patching this behavior!
Fixes #619
2. Switch to HTML Edition
3. Enter `<table>Here</table>`
4. Switch to Rich Mode
5. Press over the `[TABLE]` attachment
As a result, the Unknown HTML Editor should show up onscreen.
Needs Review: @SergioEstevao
> Fixing Regular Attachment's Touch Detection (Non Media!)

- Aztec/Classes/TextKit/HTMLAttachment.swift
- Aztec/Classes/TextKit/TextStorage.swift
- Aztec/Classes/TextKit/TextView.swift
- AztecTests/TextStorageTests.swift
- AztecTests/TextViewTests.swift
- Example/Example/EditorDemoController.swift
In this PR we're simplifying the Attachments API. Attachment Edition + Undo is coming up in another PR, for simplicity's sake.
2. Switch to HTML Mode
3. Enter `Test <table>Something</table> Test`
4. Switch to Rich Mode
5. Press the `[TABLE]` legend
6. Verify that the Unknown HTML Editor is onscreen
7. Update the HTML so it reads as `<testtest>Something</testtest>`
8. Verify that the document properly displays `[TESTTEST]` instead of `TABLE`.
2. Insert an image
3. Press over the image and edit it's properties
4. Verify the image properly reflects the new properties
> Attachments: Interface Cleanup

- Aztec.xcodeproj/project.pbxproj
- Aztec/Classes/Extensions/NSAttributedString+Strip.swift
- Aztec/Classes/TextKit/ImageAttachment.swift
- Aztec/Classes/TextKit/MediaAttachment.swift
- Aztec/Classes/TextKit/TextView.swift
- Aztec/Classes/TextKit/VideoAttachment.swift
- AztecTests/TextViewTests.swift
In this brief PR we're disabling the Copy of attribute sthat can't be archived, as a temporary workaround for issue #627.
Please note that two required initializers have been added to VideoAttachment and ImageAttachment, respectively. This was done because it was the source of a secondary Copy-Y crash, triggered with the exact same steps.
Fixes #627
1. Launch the Demo Editor with sample text
2. Select the entire document
3. Hit Copy
4. Go to the Empty Editor
5. Hit Paste
Aztec shouldn't crash in any step.
> Copy + Paste: Stripping Attributes that don't support NSCoding

- Aztec/Classes/TextKit/TextView.swift
Fixes #440
2. Insert a Blockquote
3. Verify that the Cursor is visible
> Fix: Missing Cursor after Inserting Blockquote

- Aztec/Classes/Constants/Metrics.swift
- Aztec/Classes/TextKit/LayoutManager.swift
- Aztec/Classes/TextKit/ParagraphProperty/TextList.swift
- Aztec/Classes/TextKit/ParagraphStyle.swift
- Example/Example/SampleContent/content.html
Fixes #449 
This PR adds support for drawing block quotes inside lists.
To test:
- Run the demo app with sample content
- Scroll to the place where lists are mixed with block quotes and see if the presentation is done correctly
- Open the empty demo app
- write something
- Tap on list formatting
- Tap on block quote formatting
- Check if presentation is correct.
> Draw block quotes inside lists

- Aztec/Classes/TextKit/HTMLAttachment.swift
- Aztec/Classes/TextKit/ImageAttachment.swift
- Aztec/Classes/TextKit/MediaAttachment.swift
- Aztec/Classes/TextKit/TextView.swift
- Aztec/Classes/TextKit/VideoAttachment.swift
- Example/Example/EditorDemoController.swift
In this PR we're implementing a (hopefully) cool API that will allow us to edit attachments, while getting Undo Support + Re-Layout after edition, for free.
```
textView.edit(attachment) { updated in
updated.property = newValue
}
```
Closes #630
--
1. Launch the Editor Demo (with Sample Text)
2. Scroll all the way down
3. Tap and edit the `[TABLE]` Attachment
4. Make sure the `[TABLE]` tag gets renamed, if you happen to change the root tag
5. Verify the generated HTML looks as expected.
6. Perform the Shake Gesture and hit Undo
7. Verify everything got to it's former state
1. Launch the Editor Demo (with Sample Text)
2. Edit few Image Properties (alignment / size)
3. Verify the generated HTML looks as expected
4. Peform the Shake Gesture …
> Attachments: Undo Support

- Aztec/Classes/Extensions/String+HTML.swift
- Aztec/Classes/Libxml2/Converters/Out/OutHTMLConverter.swift
- AztecTests/Extensions/StringHTMLTests.swift
- AztecTests/TextKit/TextStorageTests.swift
- AztecTests/TextKit/TextViewTests.swift
Fixes #632
1. Run the Unit Tests!
2. Verify that Japanese / Non Latin characters don't get encoded anymore
Thanks in advance sir!!
> Fix: Stop encoding non-latin characters

- Aztec.xcodeproj/project.pbxproj
- Aztec/Classes/Extensions/Array+Helpers.swift
- Aztec/Classes/Formatters/Implementations/BlockquoteFormatter.swift
- Aztec/Classes/Formatters/Implementations/HTMLParagraphFormatter.swift
- Aztec/Classes/Formatters/Implementations/HeaderFormatter.swift
- Aztec/Classes/Formatters/Implementations/PreFormatter.swift
- Aztec/Classes/Formatters/Implementations/TextListFormatter.swift
- Aztec/Classes/TextKit/LayoutManager.swift
- Aztec/Classes/TextKit/ParagraphStyle.swift
- AztecTests/Extensions/ArrayHelperTests.swift
- AztecTests/Extensions/NSAttributedStringListsTests.swift
- AztecTests/TextKit/TextViewTests.swift
In this PR we're adding logic so that **Nested Text Lists** get grouped together. Instead of producing:
```
OL > LI > Blockquote > OL > LI
```
We should produce:
```
OL > LI > OL > LI > Blockquote
```
Fixes #633 
1. Verify that the Unit Tests are happy
2. Launch the Empty Editor
2.1. Toggle Ordered List
2.2. Toggle Blockquote
2.3. Hit Tab
3. Verify that the produced HTML looks as expected.
> Fixing Blockquote within Nested List Indentation

- Aztec/Classes/Converters/NSAttributedStringToNodes.swift
- Aztec/Classes/Formatters/Implementations/LinkFormatter.swift
- AztecTests/TextKit/TextViewTests.swift
Fixes #654 
To test:
- Open the empty demo app
- Switch to HTML mode and write this: `<a href=\"\\http:\\badlink&?\">link</a>`
- Switch to visual mode and see if the app doesn't crash.
> Fix link formatter

- README.md
Removes some redundancy in the documentation.
The removed section had information that's also present in section "Running the Example App".
Feel free to merge if approved.
> Removes some redundancy in the documentation.

- Aztec.xcodeproj/project.pbxproj
- Aztec/Classes/Converters/HTMLNodeToNSAttributedString.swift
- Aztec/Classes/Converters/NSAttributedStringToNodes.swift
- Aztec/Classes/Formatters/Implementations/HTMLDivFormatter.swift
- Aztec/Classes/Formatters/Implementations/HTMLParagraphFormatter.swift
- Aztec/Classes/TextKit/ParagraphProperty/HTMLDiv.swift
- Aztec/Classes/TextKit/ParagraphProperty/HTMLParagraph.swift
- Aztec/Classes/TextKit/ParagraphStyle.swift
- AztecTests/Converters/HTMLNodeToNSAttributedStringTests.swift
- AztecTests/Converters/NSAttributedStringToNodesTests.swift
In this PR we're implementing both, HTMLDiv and HTMLDivFormatter, plus, adding new unit tests.
From now on, DIV elements will no longer be stored by means of UnsupportedHTML instances.
Ref. #658
Run the unit tests!
> Implements HTMLDiv Formatter

- Aztec/Classes/Converters/HTMLNodeToNSAttributedString.swift
- Aztec/Classes/Libxml2/DOM/Data/StandardElementType.swift
This PR does some code cleanup that'll be useful for #667.
- Removes an unused and duplicated method.
- Moves some conversion code to `HTMLNodeToNSAttributedString`.
- Documents the methods that were moved.
Just run the unit tests.
> Code cleanup before enforcing paragraphs.

- Aztec/Classes/Converters/HTMLNodeToNSAttributedString.swift
- Aztec/Classes/Converters/NSAttributedStringToNodes.swift
- Aztec/Classes/NSAttributedString/Styles/UnsupportedHTML.swift
- AztecTests/Converters/HTMLNodeToNSAttributedStringTests.swift
- AztecTests/Converters/NSAttributedStringToNodesTests.swift
- AztecTests/TextKit/UnsupportedHTMLTests.swift
In this PR we're updating the UnsupportedHTML property:
- UnsupportedHTML is now immutable. Win: subranges are enforced to require a new copy, whenever a new UnsupportedHTML entity shows up.
- UnsupportedHTML now contains an array of HTMLElementRepresentation. We were, previously, storing an ElementNode with an entire subtree, which was the source of multiple Tree Generation issues.
- Multiple UnitTests added + fixed!
Ref #658
Run the unit tests and make sure everything is happy!
> UnsupportedHTML: Multiple Updates

- Aztec/Classes/Converters/NSAttributedStringToNodes.swift
- AztecTests/Converters/HTMLNodeToNSAttributedStringTests.swift
This PR extracts attributes associated to empty paragraphs, which, otherwise, would be lost.
Fixes #673
Run the unit tests!
> Extracting Elements from Empty Paragraphs html within empty paragraphs

- Aztec/Classes/Libxml2/DOM/Data/ElementNode.swift
- AztecTests/Converters/HTMLNodeToNSAttributedStringTests.swift
The DIV element is considered non mergeable. As a result, Aztec currently has the following behavior:
Input: `<div><p>Hello</p><p>World</p></div>`
Output: `<div><p>Hello</p></div><div><p>World</p></div>`
In this PR we're marking the **div** element as mergeable, and thus, preventing such partitioning.
Ref #658
Run the unit tests!
> Fixing div partitioning

- Aztec/Classes/TextKit/MediaAttachment.swift
- Example/Example/EditorDemoController.swift
In this PR we're implementing a limit to the Image Download Retry Mechanism. After 3 failed attempts, we shall no longer retry (we were previously retrying an infinite number of times).
Fixes #675
1. Add an invalid image (`<img src="https://someinvalid.url/with-an-invalid-resource">`
2. Verify the image disappears shortly after
3. Add a valid image (`<img src="https://kurzee.files.wordpress.com/2017/07/img_3287.jpg"">`
4. Verify the image remains onscreen
cc @diegoreymendez  @SergioEstevao 
P.s: YES Brent's blog was the first image that showed up.
> Media: Preventing Infinite Loop (Just the retry, we love Cupertino though)

- Aztec/Classes/TextKit/MediaAttachment.swift
- Aztec/Classes/TextKit/TextStorage.swift
- Aztec/Classes/TextKit/TextView.swift
- Updated MediaAttachmentDelegate's method signature. Swift 3 style!
- Updated few method's signature(s). Again, Swift 3 style.
- Moved Nested Types to an extension
- Updated visibility modifiers
- Wired guard let when possible
Ref. #682
- Verify the unit tests are still green!
- Run a smoke test over Media. 
**Note:** No logic was changed, just code reorganization, and few minor touches!
> MediaAttachment: Cleanup

- Aztec/Classes/Libxml2/Converters/In/InNodeConverter.swift
- AztecTests/Importer/HTMLToAttributedStringTests.swift
I've managed to reproduce Crash #655 with the following snippet:
```
<script>(adsbygoogle = window.adsbygoogle || []).push({});</script>
```
Libxml is parsing all of the text inside `<script>` tags as CData nodes (which lack the **name** field, cause of the crash). In this PR we're adding a switch case, so that CData nodes are handled as Text Nodes.
Fixes #655
- Verify the unit tests are green!
*P.s.:* I've added the **NeXT** milestone, as discussed. Feel free to rename it, if you manage to come up with a cooler name.
> Fix: InNodeConverter Missing Switch Case

- Scripts/carthage_script.sh
This (brief) PR nukes the Carthage Logfile, which isn't really needed.
- Nuke `Example/Carthage/*`
- Run the sample app from within Xcode
- Verify that the script still runs!
> Carthage Script: Nuking logfile

- Aztec/Classes/TextKit/TextView.swift
- Example/AztecExample.xcodeproj/xcshareddata/xcschemes/AztecExample.xcscheme
- Example/Example/EditorDemoController.swift
Fixes #641 
To test:
- Start the demo app.
- Select a range of text where an image or video exists.
- Tap on the link button on the toolbar
- Check that the link text option doesn't show
- Change the url or write a new url
- Tap on Insert Link
- Switch to HTML mode and see if link is applied around the image/video
> Links over images

- Example/AztecExample.xcodeproj/xcshareddata/xcschemes/AztecExample.xcscheme
Disables the UI tests, since they weren't properly maintained up to this point, and are all failing.
There's already an issue to re-enable them.
> Disables the UI tests.

- Aztec/Classes/GUI/FormatBar/FormatBar.swift
- Aztec/Classes/GUI/FormatBar/FormatBarDelegate.swift
- Aztec/Classes/GUI/FormatBar/FormatBarItem.swift
- Example/Example/EditorDemoController.swift
This PR is part of the format bar updates required for https://github.com/wordpress-mobile/WordPress-iOS/issues/7703.
In particular, it updates the format bar to use plain `String`s for bar item identifiers instead of `FormattingIdentifier`s specifically. This allows us to support a wider range of options for format bar
buttons – the buttons required for media insertion don't have associated formatting identifiers, so instead we can just provide strings.
The format bar itself never really made use of the fact that the identifiers were `FormattingIdentifier`s, only the code outside of the bar did. We can still use `FormattingIdentifier`s to manage the formatting items, but the bar doesn't need to care that we're doing so.
I'll have a PR coming up for WPiOS so that it'll work correctly with …
> Update FormatBar to use Strings as identifiers

- Aztec/Classes/GUI/FormatBar/FormatBar.swift
- Aztec/Classes/GUI/FormatBar/FormatBarDelegate.swift
- Example/Example/EditorDemoController.swift
Implements #699
Our designs for the new media picker toolbar in WordPress for iOS require us to set a custom button on the trailing end of the format bar:
This PR adds a new `trailingItem` property that can be used to set a custom item on the right end of the bar. It also changes the way the leftmost item is set to use a similar `leadingItem` property instead of a subarray of bar items.
To test:
* Ensure that the toolbar behaves as it did before.
* In the demo app, you can add a custom trailing button in the `createToolbar` method of `EditorDemoController.swift`, by adding the following code just before the `return`:
```
let trailingItem = UIButton(type: .custom)
trailingItem.setTitle("Testing", for: .normal)
trailingItem.setTitleColor(.black, for: .normal)
trailingItem.titleLabel?.font = …
```
> FormatBar: Customise left and right items

- Example/Example/EditorDemoController.swift
- Example/Example/SampleContent/content.html
First part of providing a solution for #281.
The truth is that shortcodes support is not very relevant for Aztec, as shortcodes are not standard HTML.
That said, this PR offers an example solution to handle WordPress' `[caption]` shortcode.
> Adds CAPTION shortcode processing to the Example app.

- Aztec.xcodeproj/project.pbxproj
- Aztec/Classes/Formatters/Implementations/HeaderFormatter.swift
- Aztec/Classes/TextKit/ParagraphProperty/Header.swift
- Aztec/Classes/TextKit/ParagraphStyle.swift
- AztecTests/Formatters/HeaderFormatterTests.swift
- Example/Example/EditorDemoController.swift
In this PR we're updating the HeaderFormatter so that the default Font Size is preserved whenever a Header Style is applied / updated, and restored whenever the style gets effectively removed.
Fixes #677
1. Verify the unit tests are happy
2. Launch the empty editor
3. Type `Pristine` + newline
4. Toggle H1
5. Type `Hello` + newline + `World`
6. Verify that the `World` word gets rendered in the exact same size as `Pristine`
cc @diegoreymendez  + @SergioEstevao 
> HeaderFormatter: Restoring the default font size upon removal

- Aztec/Classes/Extensions/NSRange+Helpers.swift
- Aztec/Classes/Extensions/String+RangeConversion.swift
- Aztec/Classes/TextKit/HTMLStorage.swift
- AztecTests/Extensions/UIColorHexParserTests.swift
- AztecTests/TextKit/TextViewStubAttachmentDelegate.swift
- AztecTests/TextKit/TextViewTests.swift
- NSRange+Equatable implementation now is only available for Swift <3.2
- Nuked two unused Range helpers that were causing build errors
- Fixed a couple UIColor warnings
- Closures that (used to look like) `(Void) -> Void` are now enforced to be `() -> Void`
- Wired a missing `Image Provider` that was causing a crash
- Verify that the unit tests are okay in Xcode 8 + 9
- Run a smoke test over Aztec
cc @diegoreymendez @SergioEstevao
> Fixing Xcode 9 Build Errors

- Aztec/Classes/GUI/FormatBar/FormatBar.swift
- Example/Example/EditorDemoController.swift
Refs https://github.com/wordpress-mobile/WordPress-iOS/issues/7763 in WPiOS
This PR adds animation when switching the format bar's `defaultItems` and `overflowItems` collections. 
To ensure a smooth transition, I've made the the `defaultItems` and `overflowItems` properties read-only and added a new `setDefaultItems(_:overflowItems:)` method to set them both at the same time.
To test:
* Check out the associated WPiOS integration branch: https://github.com/wordpress-mobile/WordPress-iOS/tree/feature/media-format-bar-animations
* Open Aztec
* Tap the + button in the format bar. The new media buttons should animate in.
* Tap the X to cancel out of media insertion mode. The text formatting buttons should animate in.
* Ensure the animations look correct both when the bar's overflow items are …
> Format Bar: Animate item changes

- Aztec/Classes/Extensions/String+EndOfLine.swift
- Aztec/Classes/TextKit/TextView.swift
- AztecTests/StringEndOfLineTests.swift
Our **isEndOfParagraph** helper, actually, should be named **isEndOfLine**, since it checks if a given position is the beginning AND end of a line (condition which doesn't imply End of Paragraph!).
Verify that the unit tests run correctly.
Thanks!
> String+EndOfLine: Renaming Helper

- Aztec.xcodeproj/project.pbxproj
- Aztec/Classes/Formatters/Implementations/HeaderFormatter.swift
- Aztec/Classes/Libxml2/Converters/In/CSSParser.swift
- Aztec/Classes/Libxml2/Converters/In/InAttributeConverter.swift
- Aztec/Classes/Libxml2/DOM/Data/Attribute.swift
- Aztec/Classes/Libxml2/DOM/Data/CSSAttribute.swift
- Aztec/Classes/NSAttributedString/Attributes/HTMLRepresentation.swift
- Aztec/Classes/NSAttributedString/Conversions/AttributedStringSerializer.swift
- Aztec/Classes/NSCoding/Coding.swift
- Aztec/Classes/TextKit/ParagraphProperty/Header.swift
- AztecTests/Formatters/HeaderFormatterTests.swift
- AztecTests/HTML/Conversions/CSSParserTests.swift
- AztecTests/HTML/Nodes/ElementNodeTests.swift
- AztecTests/TextKit/HTMLRepresentationTests.swift
- AztecTests/TextKit/UnsupportedHTMLTests.swift
- Example/Example/EditorDemoController.swift
Several changes to support CSS styling.  Brings #285 forward.
This PR moves us towards CSS support by:
- Adding class `CSSParser`.
- Integrating the CSS parsing step as part of the HTML parsing.
- Adding support for copying and pasting CSS attributes.
Also not directly related:
- Renames `CSSProperty` to `CSSAttribute`, for a more precise naming.
- Reorganizes the element -> formatters map, so that the same formatters can be reused for attributes if necessary.
- Introduces the `Coding` protocol and the `NSCodingProxy` class so we can implement `NSCoding` in `enum`s and `struct`s.  This will bring our code closer to the new Coding features in Swift 4.
**Test 1:**
1. Write some HTML with attributes (and CSS attributes).
2. Switch to visual mode.
3. Copy the text.
4. Paste it.
5 Switch to …
> Base modifications for CSS Support

- Aztec/Classes/TextKit/LayoutManager.swift
- Aztec/Classes/TextKit/TextView.swift
In this PR we're implementing a mechanism that allows us to determine the Extra Line Fragment's Typing attributes.
This is required in order to draw the Background of empty Blockquote Line Fragments.
Fixes #718
2. Insert a Blockquote
3. Type `1` + **Shift + Enter** + `2`
4. Press Arrow Down
5. Hit **delete** Twice
6. Press Arrow UP
7. Type `3`
As a result, you should have, onscreen, a Blockquote with two lines. First line should read `31`, and the second line should be empty (yet, it's background should be properly rendered).
> Preventing incorrect style removal

- Aztec.xcodeproj/project.pbxproj
Remove Gridicons dependency for Carthage
To Test: 
1. add `github "azone/AztecEditor-iOS" "develop"` to your `Cartfile`
2. execute `carthage update AztecEditor-iOS --platform iOS` _Please follow https://github.com/Carthage/Carthage/blob/master/README.md_
3. add `$(SDKROOT)/usr/include/libxml2/` to **Header Search Paths** in **Build Settings**
4. do `import Aztec` in your code and run
> Remove Gridicons dependency

- README.md
Fixes #734 
Following @azone 's contribution in https://github.com/wordpress-mobile/AztecEditor-iOS/pull/733, this PR adds some extra information to make it easier to integrate Aztec into third party Apps through Carthage.
**To test:**
1. Create an empty Xcode project to integrate Aztec to.
2. Follow the new instructions in README.md and make sure they're clear enough.
IMPORTANT: make sure you add `import Aztec` somewhere in your project's sources and build it to make sure Aztec was properly integrated.
> Adds documentation to integrate Aztec with Carthage.

- Aztec/Classes/TextKit/TextStorage.swift
- AztecTests/TextKit/TextStorageTests.swift
This PR ensures Font Consistency whenever
Fixes #708
1. Launch Aztec
2. Toggle H1
3. Enter a line of text
4. Toggle H2
5. Enter another line of text
6. Place the cursor at the beginning of the second line
7. Hit backspace
As a result, you should have a single line of text. **Font size** should be the same for the entire string.
Verify that the HTML generated looks as expected + verify that the unit tests are green!
> Fixing Font upon text deletion

- Aztec/Classes/Extensions/UIFont+Traits.swift
Removes an assert that was really triggered by normal usage of the library.  There's a default behavior in place to make sure the app handles the situation graciously.
> Removes an assert.

- Aztec/Classes/TextKit/TextView.swift
- AztecTests/TextKit/TextViewTests.swift
iOS 11's `insertText` / `deleteBackward`'s inner workings result into loosing the typingAttributes. This fix is analog to the one introduced via #725.
Fixes #749
1. Verify that the unit tests pass
2. Launch Aztec > Empty document
3. Toggle Bold
4. Type Here + Newline
5. Toggle Italics
6. Type Theree + Backspace twice
7. Type e
8. Verify that the new `e` character is in italics.
> iOS 11: Delete Backwards Workaround

- Aztec.xcodeproj/project.pbxproj
- Aztec/Classes/TextKit/TextView.swift
- AztecTests/TextKit/TextViewStubDelegate.swift
- AztecTests/TextKit/TextViewTests.swift
- Example/Example/EditorDemoController.swift
In this PR we're fixing a glitch in which the Format Bar would loose sync with the actual Attributed String styles.
Fixes #748
1. Empty document
2. Toggle bold
3. Type `Bold` + Newline
4. Toggle italics
5. Type `Italics`
As a result, after typing the first character (Step 5), the *Italics* format bar indicator does NOT get dehighlighted.
> iOS11: Format Bar Glitch

- Aztec/Classes/Formatters/Implementations/HeaderFormatter.swift
Fixes #755
1. Launch the Emtpy Editor
2. Type `Something` + newline
3. Press over the `H` format bar button, and pick the **Default** font
4. Type `Else`
Verify that the size of the font in (2) and (4) do match.
> HeaderFormatter: Restoring default font size for .none header type

- Example/Example/EditorDemoController.swift
This PR prevents an undesired vertical scrolling glitch, when switching to a custom Input View (ie. Header Level picker).
Fixes #756 
1. Emtpy Document
2. Type enough text to cause vertical scrolling
3. Place the cursor at the bottom of the document
4. Press `H` / `List`'s format bar buttons
Verify that the vertical offset doesn't flicker at all.
> Keyboard Switch: Fixing Vertical Padding Glitch

- Aztec/Classes/TextKit/TextView.swift
This issue fixes #750 and #761.
We're wrapping our iOS 11 workarounds so that they're only executed in iOS 11 +.
We're fixing autocorrect so that it will no longer lose the font styles.
1. Empty editor
2. Enable Bold
3. Type "This is "
4. Enable Italic
5. Start typing the word "Italic" without fully writing it.
6. Select the "Italic" autocomplete suggestion and make sure the styles are maintained after the word is inserted.
> Autocorrect no longer loses styles & iOS 11 workarounds contained.

- Aztec/Classes/TextKit/TextView.swift
This PR updates the Attachments Gesture Recognizer, so that touches that fall beyond an image attachment aren't even accepted.
Fixes #765
2. Insert an image
3. Verify that you're still able to press over the attachment, and access it's options
4. Enter some text
5. Verify that iOS's Magnifier shows up after a long press
> TextView: Attachments Recognizer no longer receiving all touches

- Aztec/Classes/TextKit/TextStorage.swift
- Aztec/Classes/TextKit/TextView.swift
- AztecTests/TextKit/TextStorageTests.swift
- AztecTests/TextKit/TextViewStubAttachmentDelegate.swift
- Example/Example/EditorDemoController.swift
In this PR we're allowing for `nil` MediaAttachment(s) URL. This will allow us to remove the `placeholder://` workaround that has served us well, but is behind a [WordPress iOS Issue](https://github.com/wordpress-mobile/WordPress-iOS/issues/7973) in which Drag + Drop images won't immediately be displayed.
1. Try adding new images
2. Verify nothing breaks
3. Verify that the unit tests still pass
> Updating Attachments Delegate's API

- Aztec/Classes/GUI/FormatBar/FormatBar.swift
- Example/Example/UnknownEditorViewController.swift
- Removed unused variable
- Updated a closure signature to match the new standard
I'm afraid it seems not possible to get rid of the remaining warning (appears to be a Swift 3.2 Compiler glitch). Will probably go away whenever we jump over Swift 4.
- Verify that the unit tests are green!
Thanks!
> Fixing Xcode9 Warnings

- Aztec/Classes/Formatters/Implementations/BlockquoteFormatter.swift
- Aztec/Classes/NSAttributedString/Conversions/AttributedStringParser.swift
- Aztec/Classes/NSAttributedString/Conversions/AttributedStringSerializer.swift
- Aztec/Classes/TextKit/LayoutManager.swift
- Aztec/Classes/TextKit/ParagraphStyle.swift
- Aztec/Classes/TextKit/TextView.swift
Fixes #547 
Paragraph spacing is now customizable per-app.  It's also nicer by default.
**Test 1:**
Launch the editor with content and make sure it looks about right.
**Test 2:**
Launch an empty editor and start creating paragraphs, lists, block quotes.  Also use ENTER + SHIFT to create new lines in the same paragraph.
Make sure the spacing looks nicer than before and that it's consistent.
Each list item is a different paragraph, so the spacing for lists is a bit off.  This will be handled in an upcoming PR.
> Makes paragraph spacing customizable.

- Aztec/Classes/TextKit/HTMLStorage.swift
In this PR we're adding a missing initializer, which is the cause of #771.
iOS 11 has changed the way paste works. As far as we can tell, the system instantiates a secondary UITextView + an entire TextKit stack, during the Paste OP.
Unsurprisingly, this is the actual cause of the [ghost image visible in this video](https://cloudup.com/csK0LoMHHNJ). As a workaround, we're setting a ridiculously small "Default Font", so that whenever the system itself instantiates a **HTMLStorage** entity, the font would be so small it won't even get rendered.
Apologies.
Fixes #771
1. Launch Aztec's `Editor Demo` (populated w/text)
2. Switch to HTML mode
3. Copy all of the contents
4. Paste
As a result, verify that Aztec does not crash.
> HTMLStorage: Adds missing initializer

- Aztec/Classes/Extensions/NSAttributedString+Attachments.swift
- Aztec/Classes/TextKit/MediaAttachment.swift
In this PR we're:
- Preserving the UIImage scale upon un-archival
- Not overriding a MediaAttachment's **image** with a placeholder, unless we've got an actual URL to request.
Fixes #722
1. Launch the editor with sample content.
2. Copy all the sample content.
3. Go to the empty editor.
4. Paste the copied sample content.
Verify that the pasted images do load.
> Fixing Image Paste Glitch

- Aztec/Classes/TextKit/LayoutManager.swift
- Aztec/Classes/TextKit/ParagraphStyle.swift
- Aztec/Classes/TextKit/TextStorage.swift
- Example/Example/EditorDemoController.swift
Fixes #778.
Provides better spacing customization for lists.
While not perfect (the spacing between the beginning / end of lists and other paragraphs is off) this is the best approximation we can offer without going into a much greater effort.
2. Start writing several paragraphs.
3. Start a list.  Add items, delete them.
4. Double ENTER to finish the list... make sure the spacing is consistent.
5. Switch to HTML mode and back, and make sure the spacing is not broken.
> Improves spacing support for lists.

- Aztec/Classes/Extensions/NSAttributedString+HTMLInitializer.swift
- Aztec/Classes/NSAttributedString/Conversions/AttributedStringSerializer.swift
- Aztec/Classes/TextKit/ParagraphStyle.swift
- Aztec/Classes/TextKit/TextStorage.swift
- Aztec/Classes/TextKit/TextView.swift
- AztecTests/Extensions/NSAttributedStringHTMLInitializerTests.swift
- AztecTests/NSAttributedString/Conversions/AttributedStringSerializerTests.swift
- AztecTests/TextKit/TextStorageTests.swift
- AztecTests/TextKit/TextViewTests.swift
- Example/Example/EditorDemoController.swift
While we had some support for paragraph customization, this PR make it fully accessible for third party apps.
- No longer uses `PragraphStyle.default` as Aztec's default.
- Relies on values provided to the view on initialization for defaults.  This ensures we can have different defaults for different `TextView`s within the same App.
- Several properties in `ParagraphStyle` are now open, so that Apps can customize them.
- `ParagraphStyle.default` is no longer cached, and is instead instantiated every time.  This is because `ParagraphStyle` is mutable and having a single cached instance means it'll be probably modified by the App.
- `ParagraphStyle.default` can no longer be set.
- Simplifies `AttributedStringSerializer`'s initializer considerably.
1. Go to [this …
> Improves paragraph style customization support.

- Aztec/Classes/Formatters/Implementations/ImageFormatter.swift
- Aztec/Classes/Formatters/Implementations/VideoFormatter.swift
- AztecTests/TextKit/TextViewTests.swift
This PR is an attempt to allow removal of attributes on Media attachments.
For example if we have this html:
`<img src="http://wordpress.com/logo.png" data-wp="ID">`
And then I want to remove the `data-wp` using the `extraAttributes` property on `MediaAttachment` I was unable to do it because it was being stored on the HTMLRepresentation of that element and saved back to the HTML.
The test method added on the PR show this clearer.
The change I'm proposing is to not save the original HTMLRepresentation for Media Attachments because they already have a mechanism to save all the attributes in them.
I'm open to other suggestion to solve this issue.
> Remove attributes on attachments

- Aztec/Classes/TextKit/LayoutManager.swift
- Aztec/Classes/TextKit/TextView.swift
In this PR we're adding three new TextView properties:
- blockquoteBorderColor
- blockquoteBackgroundColor
- preBackgroundColor
Because of the `dynamic` keyword, the three new properties are compatible with Apple's `UIAppearance()` mechanism. This allows us to do the following:
- Customize a specific instance:  `textView.blockquoteBackgroundColor = .green`
- Customize **all** of Aztec's instances: `TextView.appearance().blockquoteBackgroundColor = .green`
Apple's `appearance()` mechanism also allows for customization when contained in a specific ViewController, or define the UX for a specific set of traits.
1. Open `EditorDemoViewController.swift`
2. Paste this snippet in viewDidLoad `textView.blockquoteBackgroundColor = .green`
3. Launch Aztec
4. Insert a Blockquote
Verify that the …
> Customizable Blockquote Style

- Aztec/Classes/TextKit/TextStorage.swift
- Aztec/Classes/TextKit/TextView.swift
Fixes keyboard auto-correction crash issue(if the view is inherited from TextView)
To test(recur):
1. Open Aztec.xcworkspace
2. Create new view inherited from TextView
3. Replace TextView to the view just created
4. Type any english words
6. Press space button in keyboard
7. If not crash, press again.
Device: iPhone 7, OS version: iOS 11
> Fix keyboard auto-correction crash issue(if the view is inherited from TextView)

- Aztec/Classes/TextKit/TextView.swift
Avoiding to call ensureRemovalOfParagraphAttributesAfterSelectionChange method if TextView have marked text
Fixes #801 
To test:
1. Add block-quote
2. Switch input method to Chinese
3. Input Chinese but do not confirm
> Avoiding to call ensureRemovalOfParagraphAttributesAfterSelectionChange method if TextView have marked text

- Aztec.xcodeproj/project.pbxproj
- Aztec/Classes/Extensions/UIImage+Resize.swift
- Aztec/Classes/TextKit/MediaAttachment.swift
- Example/Example/EditorDemoController.swift
- Example/Example/SampleContent/content.html
This PR contains changes needed to address https://github.com/wordpress-mobile/WordPress-iOS/issues/8063 (also see [this comment](https://github.com/wordpress-mobile/WordPress-iOS/issues/8063#issuecomment-340917766)).
The following things are what is changing here:
* There is no longer a circle drawn around the `overlayImage`
* Borders can now be drawn around overlays (_default is off_). The `Appearance ` struct now contains `overlayBorderWidth` and `overlayBorderColor` which, when set, will draw borders around the image along with the standard overlay.
* The `shouldHideBorder` property was added so borders can be turned completely off even if the Border `Appearance` values are set. This is useful for the times you want to display an overlay but no border...e.g. failed uploads or other …
> MediaAttachment overlay design updates

- Aztec/Classes/Extensions/String+EndOfLine.swift
- Aztec/Classes/Extensions/String+RangeConversion.swift
- Aztec/Classes/Extensions/UIColor+Parsers.swift
- Aztec/Classes/Libxml2/Converters/In/CSSParser.swift
- Aztec/Classes/Libxml2/DOM/Data/TextNode.swift
- Aztec/Classes/NSAttributedString/Conversions/AttributedStringSerializer.swift
- Aztec/Classes/TextKit/HTMLStorage.swift
- Aztec/Classes/TextKit/TextStorage.swift
- Aztec/Classes/TextKit/TextView.swift
- AztecTests/Extensions/StringParagraphTests.swift
- AztecTests/StringRangeConversionTests.swift
- AztecTests/TextKit/TextViewTests.swift
In this PR we're removing all of the `String` **.characters** references.
- Verify that the unit tests are green
- Verify that the Swift 3.2 warnings are gone
cc @diegoreymendez + @SergioEstevao 
> Swift 3.2: Removing .characters references

- Aztec/Classes/TextKit/ParagraphProperty/Header.swift
To test:
Configuration header size:
```swift
Header.HeaderType.fontSizeMap[.h1] = 24
Header.HeaderType.fontSizeMap[.h2] = 20
Header.HeaderType.fontSizeMap[.h3] = 18
Header.HeaderType.fontSizeMap[.h1] = 16
Header.HeaderType.fontSizeMap[.h2] = 14
Header.HeaderType.fontSizeMap[.h3] = 12
```
> Make header's font size customizable

- Aztec.xcodeproj/xcshareddata/xcschemes/Aztec.xcscheme
- Aztec/Classes/TextKit/VideoAttachment.swift
- Example/AztecExample.xcodeproj/xcshareddata/xcschemes/AztecExample.xcscheme
- Example/Example/EditorDemoController.swift
Fixes #813 
To test:
- Start the empty demo app
- Add a new media video object
- Tap on it
- Tap on another media
- See that the icon on the video resets to the play button.
- Activate the error mode by switch the `errorMode` variable to true on the `EditorDemoController`
- Repeat the steps above.
> Make sure VideoAttachment always have the play icon by default.

- Aztec/Classes/TextKit/TextStorage.swift
Fixes #811 
To test:
1. Open editor
2. Press return
3. Turn Heading on (h1 or h2, ...)
4. Input any Chinese characters and confirm
5. Continue input Chinese characters and confirm
> Fixed Chinese input issue in header 1~6

- Aztec/Classes/TextKit/HTMLStorage.swift
Fixes #709 
It seems we were missing a call to `edited()`.
1. Launch the app
2. Type anything using the Japanese keyboard.
3. Switch to HTML mode and edit some more.
4. Switch back to visual mode and make sure all Japanese characters are properly rendered throughout the session.
> Fixes an issue with non english characters.

- Aztec/Classes/TextKit/HTMLStorage.swift
Fixes #709 for Beta 14 (It's the same fix as #824 but for Beta 14).
It seems we were missing a call to `edited()`.
1. Launch the app
2. Type anything using the Japanese keyboard.
3. Switch to HTML mode and edit some more.
4. Switch back to visual mode and make sure all Japanese characters are properly rendered throughout the session.
> Japanese text issues for 1.0.0-beta.14.

- Aztec/Classes/NSAttributedString/Conversions/AttributedStringParser.swift
- Aztec/Classes/TextKit/ImageAttachment.swift
- Example/Example/AttachmentDetailsViewController.storyboard
- Example/Example/AttachmentDetailsViewController.swift
- Example/Example/EditorDemoController.swift
Fixes #830 
To test:
- Open the demo app
- Add an image
- Switch to HTML
- Check if the full attribute is applied
> Image output html css for size full

- Example/AztecUITests/AztecUITests.swift
- Example/AztecUITests/XCTest+Extensions.swift
Fixed the getHTMLContent function - now scrolls the toolbar to tap the appropriate button.
Is whether or not the toolbar is expanded by default a device setting? Would probably enable that by default for the demo as it makes this easier.
Added `<p>` and `</p>` tags to get tests to pass. If this behaviour changes, these tests will need to be updated. Comments out two tests that need more change (and are maybe surfacing bugs).
Uncommented out the list tests, minor changes to get those working.
Stripping out all whitespace characters between tags as we should not IMO be testing that. Open to feedback here.
To test: Open example app, and run the tests. Confirm that they pass.
> Fix ui tests

- Aztec/Classes/TextKit/TextView.swift
Fixes #812
To test:
1. enter one line characters
2. enter another line characters
3. set line one to heading 1~6, block-quote or list
4. shake device and undo
5. loop step 4
> TextView: fix undo issue for H1~6, block-quote, ordered list and unordered list

- Aztec/Classes/Formatters/Implementations/HeaderFormatter.swift
- Aztec/Classes/TextKit/TextStorage.swift
- Aztec/Classes/TextKit/TextView.swift
Fixes #811 
Alternative solution to #820 
Resolves a workaround and improves the code used to change the font size to make it more resilient.
1. Launch the editor
2. Press enter
3. Activate H1
4. Type something with the Chinese keyboard
5. Press enter to accept the marked text
6. Press enter again to go to the next line
7. Type something else.
8. Backspace just before what you wrote in point 7, so it goes up to the H1 line.
Make sure the H1 font is applied to the line you just moved up.
1. Launch the editor
2. Press enter
3. Activate H1
4. Type something with the Chinese keyboard
5. Press enter to accept the marked text
6. Keep writing.
Make sure all new characters are still visible.
> Resolves some issues with Chinese characters in the editor.

- Aztec/Classes/Extensions/NSAttributedString+Attachments.swift
- Aztec/Classes/Libxml2/DOM/Data/ElementNode.swift
- Aztec/Classes/NSAttributedString/Conversions/AttributedStringSerializer.swift
- AztecTests/HTML/Nodes/ElementNodeTests.swift
This PR introduces no new functionality. We're:
1. Encapsulating the **linkedImage** parsing mechanism, into it's own method
2. Moving the `textAttachment` constant over to a String extension, for convenience
3. Adding a small method to ElementNode (and few unit tests!)
1. Verify that the unit tests are green
2. Add a linked image `<a href="www.wordpress.com"><img src="www.something.com/img"></a>`
3. Try toggling back and forth, and verity that the HTML is preserved
> Linked Image Mechanism: Cleanup!

- Aztec/Classes/NSAttributedString/Conversions/AttributedStringParser.swift
- Aztec/Classes/NSAttributedString/Conversions/AttributedStringSerializer.swift
- Aztec/Classes/TextKit/ImageAttachment.swift
- Example/Example/AttachmentDetailsViewController.swift
- Example/Example/EditorDemoController.swift
- Example/Example/SampleContent/content.html
This PR, refactor the implementation of links on images.
Instead of using a custom property on ImageAttachment and doing some special parsing, this kept the parsing clean, just parsing the elements normally.
Then when tapping on the img it detects if a link is surrounding just the image and edits that link if available.
To test:
- Open the empty demo
- Insert an image
- Switch to html and see if link is there
- Switch back to Visual mode
- Tap on the image
- Change the link
> Refactor implementation of  links on image

- Aztec/Classes/TextKit/TextView.swift
TextView missed some methods in Objective-C
> TextView: Export init, setHTML and getHTML methods to Objective-C

- Aztec/Classes/TextKit/TextView.swift
Customize default text color
To test:
1. Change `textView.textColor = UIColor.darkText` to `textView.textColor = UIColor.red` in demo
2. Run the demo
> TextView: Customizable default text color

- Aztec/Classes/TextKit/TextView.swift
Fixes #853 
To test:
1. Insert a link with title 你好 世界
2. Move caret to 你好 and edit the link
> TextView: fix link range issue

- Example/AztecUITests/HighPriorityIssuesTests.swift
- Example/AztecUITests/Pages/BasePage.swift
- Example/AztecUITests/Pages/EditorPage.swift
This test was relying on a hardcoded textfield height which is changing with different font sizes. Now it passing on all font sizes configurations.
> Make testLongTitle UI test font size agnostic

- Aztec/Classes/Formatters/Implementations/PreFormatter.swift
- Aztec/Classes/TextKit/ParagraphProperty/Header.swift
- Aztec/Classes/TextKit/TextView.swift
- Example/Example/EditorDemoController.swift
This PR adds basic support for Dynamic Type — using the new API introduced in iOS 11. 
Supporting this without using iOS 11 specific API is a rather large pain in the butt — there isn't a good way to programatically get correct metrics for arbitrary font — so we'd have to hardcode scaling factors for the system fonts and have clients provide those too, if they want to specify a custom font.
I'm not sure if clients should be able to opt out of this behavior by setting some property — I'd say being accessible by default is the correct thing to do, but that's open to discussion.
Fixes #478.
Before:
After (with the biggest Accesiblity size enabled):
> Basic Dynamic Type support

- Aztec/Classes/Formatters/Base/ParagraphAttributeFormatter.swift
- Aztec/Classes/NSAttributedString/Conversions/AttributedStringParser.swift
- Aztec/Classes/TextKit/TextStorage.swift
- AztecTests/TextKit/TextStorageTests.swift
Addresses a first part of #861 .
Outputs the writing direction to HTML.
1. Add the Arabic keyboard to your device.
2. Launch the editor.
3. Type a line in Arabic - make sure it's recognized as right-to-left text in visual mode.
4. Switch to HTML mode.
Make sure the paragraph or block level element has a `dir="rtl"` attribute.
Important: the conversion back to visual mode is not supported yet.
> Adds partial support for RTL languages.

- Aztec.xcodeproj/project.pbxproj
- Aztec/Classes/TextKit/ImageAttachment.swift
- Aztec/Classes/TextKit/MediaAttachment.swift
- Aztec/Classes/TextKit/TextView.swift
- Aztec/Classes/TextKit/VideoAttachment.swift
- Example/AztecExample.xcodeproj/project.pbxproj
- Example/Example/SampleContent/captions.html
- Example/Example/SampleContent/content.html
- Example/Example/ViewController.swift
In this PR we're adding `figcaption` rendering capabilities.
Closes #723
- **ImageAttachment** will, now, also serialize the `caption` field (NSCoder implementation).
- Updated **MediaAttachment** / **ImageAttachment** bounds calculation methods
- New **MediaAttachment.Appearance** property
- And of course, the actual Caption rendering mechanisms!
Our goal is for the figcaption to render as follows:
--
1. Launch the Demo App
2. Open the `Captions Demo`
Verify that all of the captions look as expected!
> Rendering Figcaptions!

- Example/AztecUITests/AztecUITests.swift
- Example/AztecUITests/FormattingTests.swift
- Example/AztecUITests/HighPriorityIssuesTests.swift
- Example/AztecUITests/ImagesTests.swift
- Example/AztecUITests/LinkTests.swift
- Example/Example/AppDelegate.swift
Attempt to disable animations to speed-up UI tests runs. Previous build time (on Travis) was ~28-35min.  
Some background: https://stackoverflow.com/a/40400175/712306
> Disable animations when running UI tests

- Aztec/Classes/ElementConverters/Implementations/FigureElementConverter.swift
- Aztec/Classes/NSAttributedString/Conversions/AttributedStringSerializer.swift
- AztecTests/TextKit/TextViewTests.swift
In this PR we're fixing Aztec's Unit Tests:
- Patched Video HTML Tag 'Expected' parameter order.
- **FigureElementConverter** was storing a `hrHtmlRepresentation`. Probably slipped in the initial implementation.
- Patched our **UnsupportedHTML** mechanism, which wasn't running anymore, due to the new **generic element converter**.
Verify that the unit tests are green again!
cc @diegoreymendez / @jklausa 
Thanks in advance gentlemen!
> Fixing Unit Tests

- Example/Example/EditorDemoController.swift
Limit the title to one line by using UITextField instead of UITextView. Also there is no need to have a separate UILabel for the placeholder text. We can make use of UITextField’s placeholder attribute.
Fixes #821
1. Launch the Sample App
2. Verify that the Title Field is not multiline
> Sample App: Single Title Line

- Aztec/Classes/NSAttributedString/Conversions/AttributedStringParser.swift
- Aztec/Classes/TextKit/ImageAttachment.swift
- AztecTests/NSAttributedString/Conversions/AttributedStringParserTests.swift
In this PR we're enhancing the AttributedStringParser, so that ImageAttachments get their **width** and **height** properly serialized, whenever the size is set to (anything) but `.none / .full`.
Needs Review: @diegoreymendez / @SergioEstevao 
Closes #883
Motivation for this PR is [this WPiOS issue](https://github.com/wordpress-mobile/WordPress-iOS/issues/8384#issuecomment-354154635).
**TL;DR version:** `WordPress.com/wp-admin`'s post editor doesn't pick up the size's CSS classes. Instead, it relies on explicit width / height fields, in order to render images in their 'actual final size'.
In this PR we're explicitly setting the image's size, so that wp-admin behaves in a WYSIWYG fashion.
1. Run the unit tests. Verify they're green!
2. Add an attachment. Change it's size to `None / Full`, …
> ImageAttachment: Explicit Width and Height

- Aztec.xcodeproj/project.pbxproj
- Aztec/Classes/Libxml2/Converters/In/HTMLParser.swift
- Aztec/Classes/Libxml2/DOM/Data/ElementNode.swift
- Aztec/Classes/Processor/HTMLAttributes.swift
- Aztec/Classes/TextKit/ImageAttachment.swift
- Aztec/Classes/TextKit/TextView.swift
- AztecTests/Processor/HTMLAttributesTests.swift
- Example/AztecExample.xcodeproj/project.pbxproj
- Example/Example/CaptionShortcodePostProcessor.swift
- Example/Example/CaptionShortcodePreProcessor.swift
- Example/Example/EditorDemoController.swift
- Example/Example/ShortcodeProcessor.swift
- Example/Tests/CaptionShortcodePostProcessorTests.swift
- Example/Tests/CaptionShortcodePreProcessorTests.swift
- Example/Tests/ShortcodeProcessorTests.swift
In this PR we're adding support for **caption** shortcode processing:
- **CaptionShortcodePreProcessor:** Converts `[caption]` shortcode into `<figure><img><figcaption>` structures
- **CaptionShortcodePostProcessor:** Converts `<figure><img><figcaption>` back into `[caption]` shortcodes.
Closes #879 
Run `CaptionShortcodePreProcessorTests` and `CaptionShortcodePostProcessorTests` and verify all of the tests are green (**AztecExample.app**).
Verify that the **caption** shortcode works as expected:
1. Input:
```
<figure><img src="."><figcaption><b>Test</b></figcaption></figure>
```
2. Output:
```
[caption]<img src=\".\"><b>Test</b>[/caption]
```
> Figcaption Shortcode Support

- Aztec/Classes/GUI/FormatBar/FormatBar.swift
Fixes https://github.com/wordpress-mobile/WordPress-iOS/issues/8413.
I apologise that the fix is a `dispatch async`, but I tried a number of things and couldn't come up with another way to fix this. Essentially, we resize the toolbar as necessary when the safe area insets change, but for some reason in the situation described in the original ticket the system doesn't adjust the position of the bar to match its new height unless we dispatch it.
**To test:**
* Follow the steps in the original issue, and check that the format bar appears in the correct vertical position.
> FormatBar: Fix vertical position after updating for safe area insets

- Aztec/Classes/TextKit/TextStorage.swift
- Aztec/Classes/TextKit/TextView.swift
- AztecTests/TextKit/TextStorageTests.swift
- AztecTests/TextKit/TextViewStubAttachmentDelegate.swift
- Example/Example/EditorDemoController.swift
Fixes #891
This PR changes the interface of delegate callback when attachments are deleted, instead of only passing back the identifier the full attachment object is being sent.
To test:
- Open the editor demo app
- Delete media attachment and see if all works ok.
> Change attachment delete delegate interface to return the full attachment

- Aztec/Classes/TextKit/TextView.swift
- Example/Example/EditorDemoController.swift
Fixes #899 
This PR adds a new parameter to the refresh attachment method to allow only mark the attachment for redisplay instead of a full layout step that makes the textview scroll up and down.
To test:
- Start with the empty editor
- Write a paragraph with text
- Add three images after the paragraph.
- After those are "uploaded", and a fourth one.
- While the "upload/progress" is going on scroll to the top and edit the first paragraph
- Check that the doesn't scroll up and down while uploaded is going on.
> Refresh layout display only when progress is changed.

- Aztec/Classes/NSAttributedString/Conversions/AttributedStringParser.swift
- Aztec/Classes/TextKit/ImageAttachment.swift
- AztecTests/NSAttributedString/Conversions/AttributedStringSerializerTests.swift
- AztecTests/TextKit/TextStorageTests.swift
- AztecTests/TextKit/TextViewTests.swift
- Example/AztecUITests/ImagesTests.swift
- Example/Example/EditorDemoController.swift
Fixes #890
This PR changes the alignment setting on images to be by default `none` it also make sure that all alignments are written in the serialiser.
One thing that come up to my mind is: should we have a value for the alignment enum called "not defined" for cases where no alignment is set on HTML? it will be visually equivalent to none but it will tell us if no value was available  the original HTML and that we don't need to write anything.
To test:
- Open the editor app on empty demo mode
- Insert an image
- Switch to HTML and see if alignm class setting is `alignnone`
- Switch to visual tap on the image and change alignment to center
- Switch to HTML mode and see if align class setting is `aligncenter`
- Do the same for right and left alignments.
> Align center not being saved

- Aztec/Classes/TextKit/TextView.swift
Fixes https://github.com/wordpress-mobile/WordPress-iOS/issues/6904
This PR detects URLs on the pasteboard during a paste operation, and creates a link with the currently selected text if there is any. This should match the way Calypso works.
**To test:**
* Copy a URL to the pasteboard – for example, hit the Share button in Safari and copy the link
* Select some text in Aztec and hit paste in the popup menu
* The selected text should become a link
* If you try pasting onto an empty line (no text selected), the existing paste handling code should just insert the URL.
* Ensure pasting other items still works as expected. I found if I tried to copy an image directly out of Safari I couldn't always paste it as I might expect to, but that seems to be a pre-existing issue. Sometimes the URL …
> TextView: Allow linking text with a pasted URL

- Aztec.xcodeproj/project.pbxproj
- Aztec/Classes/Extensions/NSAttributedString+Attachments.swift
- Aztec/Classes/Extensions/NSMutableAttributedString+ParagraphProperty.swift
- Aztec/Classes/TextKit/ParagraphStyle.swift
- AztecTests/NSAttributedString/Conversions/AttributedStringParserTests.swift
- AztecTests/NSMutableAttributedStringParagraphProperty.swift
- AztecTests/ParagraphStyleTests.swift
Fixes #917 through method swizzling.
`NSParagraphStyle.isEqual()` now properly compares using `isEqual()` against `ParagraphStyle` objects.
Added two unit tests that trigger the problem.
Run the unit tests multiple times and make sure they never fail.
> NSParagraphStyle's isEqual now compares correctly against ParagraphStyle.

- Aztec/Classes/TextKit/ParagraphStyle.swift
Fixes an issue we introduced in #917 that was making a unit test fail.
More specifically: the comparison of `ParagraphStyle` objects was always failing.
Just run the unit tests.
> Fixes the isEqual method we swizzled.

- .travis.yml
- Aztec.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
Updates Travis to use Xcode 9.3.
**To verify:**
Simply check that this PR has been verified correctly by Travis.
> Fix Travis: Xcode 9.3 support and more.

- Aztec/Classes/EditorView/EditorView.swift
- Example/Example/EditorDemoController.swift
This PR fixes the following issues on the editor view controller demo:
- Bounce scroll on the end of the post was breaking up
- Scroll Indicator positions when going up and down and switching between keyboard mode and several layout modes (landscape, portrait, multitask ipad modes)
- Add placeholder for title label
- Allow title view to grow to accommodate longer titles
To test:
- Open the post with content and test the following works ok
- Scroll to start and end of content causing bounce
- Write on title to make it grow or shrink and see if interface works
- Rotate the device and test on all orientations (check scroll position and if able to scroll to the top and bottom of content)
- Test on multitask modes of iPad
> Fix editor layout and scroll

- Aztec/Classes/ElementConverters/Implementations/FigureElementConverter.swift
- Aztec/Classes/Libxml2/DOM/Data/ElementNode.swift
- Aztec/Classes/Libxml2/DOM/Data/Node.swift
- Aztec/Classes/Libxml2/DOM/Data/StandardElementType.swift
- Aztec/Classes/Libxml2/DOM/Data/TextNode.swift
- Aztec/Classes/NSAttributedString/Conversions/AttributedStringSerializer.swift
- AztecTests/TextKit/TextStorageTests.swift
- AztecTests/TextKit/TextViewTests.swift
- Example/AztecExample.xcodeproj/project.pbxproj
- Example/Example/SampleContent/gutenberg.html
- Example/Example/ViewController.swift
Fixes #939.  Comments before block-level elements no longer cause data loss issues.
The initial PR and unit tests were provided by @SergioEstevao.  I reopened the PR here to make sure the review history looks clean.  I also modified the unit tests to only affect what's fixed in this PR.
There's a failing unit test that's coming from develop and outside the scope of this PR.  The test is:
`testHeaderStyleDoesNotComeBackFromNonExistanceWheneverDeleteBackwardResultsInEmptyParagraphBeforeHeaderStyle`
Just run the unit tests, and make sure all (except the failing test mentioned above) succeed.
> Data lost near comments.

- Aztec/Classes/TextKit/TextView.swift
- AztecTests/TextKit/TextViewTests.swift
Fixes #943.  A unit test was failing due to recent changes..
In this PR we:
- [Define a list of single-line paragraph formatters](https://github.com/wordpress-mobile/AztecEditor-iOS/compare/issue/943-failing-unit-test?expand=1#diff-8d8015f3f021c0252c1569e4965dce80R144).
- [Generalize the method that removes single-line paragraph styles](https://github.com/wordpress-mobile/AztecEditor-iOS/compare/issue/943-failing-unit-test?expand=1#diff-8d8015f3f021c0252c1569e4965dce80R1811).
- [Modularize the code a bit](https://github.com/wordpress-mobile/AztecEditor-iOS/compare/issue/943-failing-unit-test?expand=1#diff-8d8015f3f021c0252c1569e4965dce80R1830).
- [Roll back a recent change that didn't make much sense](https://github.com/wordpress-mobile/AztecEditor-iOS/compare/issue/943-failing-unit-test?e …
> Fixes unit tests, fixes newline inside single-line paragraph attributes.

- Aztec/Classes/EditorView/EditorView.swift
- Example/AztecExample.xcodeproj/xcshareddata/xcschemes/AztecExample.xcscheme
- Example/Example/EditorDemoController.swift
This PR:
- [Fixes a bug](https://github.com/wordpress-mobile/AztecEditor-iOS/issues/956) that was causing HTML mode to have its layout broken as shown in the animation below.
- [Implements `UITextImput` in EditorView](https://github.com/wordpress-mobile/AztecEditor-iOS/compare/develop...try/fix-source-view?expand=1#diff-8c6bb98a814743991581ef39e0b91050R163) to avoid having to use the contained views directly.  We'll gradually move towards making the contained views private.
**Test 1:**
- Run the unit tests.
**Test 2:**
- Open the empty editor
- Type anything in the rich editor's body.
- Switch to HTML mode, and make sure the source view layout is fine.
**Test 3:**
- Test the editor freely, manually.  Add styles, change contents, etc.
> Fixed EditorView's HTML source layout.

- Aztec.xcodeproj/project.pbxproj
- Aztec/Classes/Renderers/CommentAttachmentRenderer.swift
- Aztec/Classes/Renderers/HTMLAttachmentRenderer.swift
- Example/AztecExample.xcodeproj/project.pbxproj
- WordPressEditor/WordPressEditor.xcodeproj/project.pbxproj
- WordPressEditor/WordPressEditor/Classes/Renderers/SpecialTagAttachmentRenderer.swift
In this PR:
- We're moving our standard renderers into the `Aztec` and `WordPressEditor` targets.
- We're updating the local version of those renderers, to the latest version from WPiOS.
Next steps will be to integrate this into WPiOS and remove the duplicated renderers from it.  This will also enable us to implement a custom Gutenberg renderer for self-closed blocks.
- Run the unit tests.
- Try the editor out and make sure comments, more-comments and unsupported HTML is rendered correctly.
> Integrates renderers into Aztec libraries.

- Aztec/Classes/TextKit/TextView.swift
- AztecTests/TextKit/TextViewTests.swift
This PR fixes an issue where an auto completion of text was being done using smaller or larger text than the original. For example replacing the word Love for the emoji ❤️ .
I added a unit test to future proof this scenario
To test:
- Open the empty editor demo
- Type the word Cheers
- Select the word
- Activate the emoji keyboard (tap on the globe symbol)
- see if on the autocompletion shows an emoji 
- tap on the autocompletion with the emoji
- see if it not crashes.
> Fix replacement range on auto replaces for different sized text.

- Aztec/Classes/Libxml2/DOM/Data/Element.swift
- Aztec/Classes/Libxml2/DOM/Data/ElementNode.swift
- Aztec/Classes/NSAttributedString/Conversions/AttributedStringParser.swift
- WordPressEditor/WordPressEditor/Classes/Plugins/WordPressPlugin/Gutenberg/GutenbergAttributeNames.swift
- WordPressEditor/WordPressEditor/Classes/Plugins/WordPressPlugin/Gutenberg/GutenbergInputHTMLTreeProcessor.swift
- WordPressEditor/WordPressEditorTests/WordPressPlugin/WordPressPluginTests.swift
Fixes #977 
This PR makes the following changes:
- Make the definition of mergeable elements configurable from the outside of the library
- Add Gutenblocks to the list of mergeable blocks
- Add a special rule for Gutenblocks merge where this can only happen when they have elements that are mergeable them selfs.
To test:
- Run unit tests to make sure all are green.
> Make Gutenberg blocks mergeable

- Example/Example/SampleContent/gutenberg.html
- WordPressEditor/WordPressEditor.xcodeproj/project.pbxproj
- WordPressEditor/WordPressEditor/Classes/Plugins/WordPressPlugin/Gutenberg/CommentNode+Gutenberg.swift
- WordPressEditor/WordPressEditor/Classes/Plugins/WordPressPlugin/Gutenberg/GutenbergAttributeNames.swift
- WordPressEditor/WordPressEditor/Classes/Plugins/WordPressPlugin/Gutenberg/GutenbergOutputHTMLTreeProcessor.swift
- WordPressEditor/WordPressEditorTests/WordPressPlugin/Gutenberg/GutenbergInputHTMLTreeProcessorTests.swift
- WordPressEditor/WordPressEditorTests/WordPressPlugin/WordPressPluginTests.swift
WordPressEditor now supports Gutenberg self-closing blocks.
Fixes #959 
Fixes #968
The problem we had is that Aztec doesn't recognize attachments as block-level style representations.  So it wraps Gutenberg blocks inside `<p>` tags.
The ideal solution would be to rewrite the logic for the output HTML serialization from scratch.
The proposed solution in this PR is to post-process the HTML to remove the self-closing Gutenberg blocks from the wrapping `<p>` tags.  It's ugly and hacky, but it's the only easy way I found to get this working in a reasonable amount of time.
Manual testing for now.  I'll be adding automated testing for all of our Gutenberg compatibility code soon.
> Fixes gutenberg self-closing blocks.

- WordPressEditor/WordPressEditor/Classes/Plugins/WordPressPlugin/Calypso/VideoShortcode/VideoShortcodeProcessor.swift
- WordPressEditor/WordPressEditorTests/Processors/ShortcodeProcessorTests.swift
This PR updates the code of the video processor in order to serialize the output the correct way.
It also updates the unit test to use the actual processor classes that are being used on the main app.
To test:
- Just make sure that the unit tests are green!
> Fix VideoPress processors

- Aztec/Classes/NSAttributedString/Conversions/AttributedStringSerializer.swift
- AztecTests/TextKit/TextStorageTests.swift
Fixes #886 
To test:
- Open the editor on HTML mode and write ```<strong>WordPress<strong> <em>App</em>```
- Switch to Visual Mode
- Make sure the space between WordPress and App is kept.
> Fix single spaces are being removed

- Aztec.xcodeproj/project.pbxproj
- Aztec/Classes/ElementConverters/Input/Implementations/GenericElementConverter.swift
- Aztec/Classes/Formatters/Implementations/LiFormatter.swift
- Aztec/Classes/Formatters/Implementations/TextListFormatter.swift
- Aztec/Classes/NSAttributedString/Conversions/AttributedStringParser.swift
- Aztec/Classes/TextKit/ParagraphProperty/HTMLLi.swift
- Aztec/Classes/TextKit/TextView.swift
- AztecTests/NSAttributedString/Conversions/AttributedStringParserTests.swift
- AztecTests/TextKit/TextStorageTests.swift
- AztecTests/TextKit/TextViewTests.swift
Fixes #984 #578 
This PR makes ```<li>``` elements to be translated to proper Paragraph Property with associated HTML representation.
This on one side creates some extra complexity on handling the lists when being used on the editor by user actions, but on the other side remove "special" processing on parsing and serialising of this elements from HTML to AttributedString and back.
This PR  also saves and serializes any element attributes set on the ```<li>``` elements.
To test:
- Make sure unit test are passing
- On both Gutenberg and regular HTML sample test around lists to see if all works ok.
> Fix LI attributes lost

- Aztec/Classes/Libxml2/DOM/Data/Element.swift
- Aztec/Classes/NSAttributedString/Conversions/AttributedStringParser.swift
- Aztec/Classes/TextKit/TextView.swift
- AztecTests/TextKit/TextViewTests.swift
- Example/Example/SampleContent/content.html
This PR changes the logic for merging `PRE` slightly so that it maintains the separation of paragraphs and lines.
> Makes PRE mergeable while maintaining newlines.

- Aztec/Classes/Libxml2/DOM/Data/Element.swift
- Aztec/Classes/Libxml2/DOM/Data/ElementNode.swift
- Aztec/Classes/Libxml2/DOM/Data/Node.swift
- Aztec/Classes/Libxml2/DOM/Data/TextNode.swift
- Aztec/Classes/NSAttributedString/Conversions/AttributedStringParser.swift
- AztecTests/NSAttributedString/Conversions/AttributedStringParserTests.swift
This PR improves the merging logic slightly.
It was initially intended to resolve #993, but turned out not to, since code blocks are not block-level elements.  Still this PR contains a few improvements I'd like to bring in.
1. We now have a method to [make it easier to check the raw-textNode content of nodes](https://github.com/wordpress-mobile/AztecEditor-iOS/compare/issue/993-code-blocks-broken?expand=1#diff-3b717148f487c5d830376809f559962cR199).
2. It has [better support for `<pre>` elements in the merging logic](https://github.com/wordpress-mobile/AztecEditor-iOS/compare/issue/993-code-blocks-broken?expand=1#diff-3691618ea04c6533e3ab78931758dc50R183).
3. It adds [a unit test for `<pre>` elements](https://github.com/wordpress-mobile/AztecEditor-iOS/compare/issue/993-code-blocks-broken?e …
> Improves merging logic.

- Aztec/Classes/Libxml2/DOM/Data/Element.swift
- Aztec/Classes/Libxml2/DOM/Data/ElementNode.swift
- Aztec/Classes/Libxml2/DOM/Data/Node.swift
- Aztec/Classes/Libxml2/DOM/Data/TextNode.swift
- Aztec/Classes/NSAttributedString/Conversions/AttributedStringParser.swift
- AztecTests/NSAttributedString/Conversions/AttributedStringParserTests.swift
- WordPressEditor/WordPressEditor/Classes/Plugins/WordPressPlugin/Gutenberg/CommentNode+Gutenberg.swift
- WordPressEditor/WordPressEditor/Classes/Plugins/WordPressPlugin/Gutenberg/GutenbergInputHTMLTreeProcessor.swift
- WordPressEditor/WordPressEditor/Classes/Plugins/WordPressPlugin/Gutenberg/GutenbergOutputHTMLTreeProcessor.swift
- WordPressEditor/WordPressEditorTests/WordPressPlugin/Gutenberg/GutenbergInputHTMLTreeProcessorTests.swift
This PR proposed an alternative fix to #996.
Unfortunately the initial proposal worked fine for a single tag, but failed when removing a tag from a larger post (sample content).
This PR proposes a more solid parsing mechanism to avoid problems with missing tags.  Opening tags without a closing match are output as regular comments.
The solution proposed in this PR changes the delimiter parsing logic entirely, to a much more robust mechanism.
One of the things that pushed me to push this is that I realized today that the previous mechanism would have failed miserably with Gutenberg block embedding other blocks (which will be a requirement moving forward).
Try removing any closing or opening tag from the Gutenberg sample content.
Also try using this content in the empty editor, in HTML mode: …
> Improve gb closing logic

- Aztec/Classes/Libxml2/DOM/Data/ElementNode.swift
- WordPressEditor/WordPressEditor.xcodeproj/project.pbxproj
- WordPressEditor/WordPressEditor/Classes/Extensions/String+RegEx.swift
- WordPressEditor/WordPressEditor/Classes/Plugins/WordPressPlugin/Gutenberg/GutenbergAttributeDecoder.swift
- WordPressEditor/WordPressEditor/Classes/Plugins/WordPressPlugin/Gutenberg/GutenbergAttributeEncoder.swift
- WordPressEditor/WordPressEditor/Classes/Plugins/WordPressPlugin/Gutenberg/GutenbergAttributeNames.swift
- WordPressEditor/WordPressEditor/Classes/Plugins/WordPressPlugin/Gutenberg/GutenbergInputHTMLTreeProcessor.swift
- WordPressEditor/WordPressEditor/Classes/Plugins/WordPressPlugin/Gutenberg/GutenbergOutputHTMLTreeProcessor.swift
- WordPressEditor/WordPressEditor/Classes/Plugins/WordPressPlugin/Gutenberg/GutenpackAttachmentToElementConverter.swift
- WordPressEditor/WordPressEditor/Classes/Plugins/WordPressPlugin/Gutenberg/GutenpackConverter.swift
- WordPressEditor/WordPressEditorTests/WordPressPlugin/Gutenberg/GutenbergInputHTMLTreeProcessorTests.swift
- WordPressEditor/WordPressEditorTests/WordPressPlugin/WordPressPluginTests.swift
Fixes a bug that was causing paragraphs to merge when they shouldn't.
Fixes #1005 
This is what the original issue looked like:
- [Added unit tests](https://github.com/wordpress-mobile/AztecEditor-iOS/pull/1006/files#diff-40513c251786f2880b02c4f1f38730f3R40) that can automatically detect this issue if it ever arised again.
- [Reorganizes the code a bit](https://github.com/wordpress-mobile/AztecEditor-iOS/pull/1006/files#diff-8f0997fe69197252915ff1a894213dfdR6) since to fix this issue I have to reuse some of the code we already have from [a new location](https://github.com/wordpress-mobile/AztecEditor-iOS/pull/1006/files#diff-48ee906bc2164480c9dfa48c13d0f995R6).
- Also fixes a bug with [how we were handling unicode characters](https://github.com/wordpress-mobile/AztecEditor-iOS/pull/1006/fi …
> Fixes a bug that was causing paragraphs to merge.

- Aztec/Classes/Formatters/Implementations/PreFormatter.swift
- AztecTests/Formatters/PreFormaterTests.swift
Addresses part of #993 .
Gutenberg code block delimiters are being removed by our WordPressEditor library.  This PR ensures that the delimiters are maintained.
It also adds a unit test to make sure there are no regressions.
This issue does NOT address the fractioning of the `<code>` tags.
- Launch the empty Gutenberg / Calypso demo editor.
- Switch to HTML and paste this
```html
<pre class="wp-block-code"><code>testing
test.   ing
testing some more</code></pre>
```
- Switch to visual mode and back to HTML mode and make sure the Gutenberg code block delimiters are not removed.
> Gutenberg code block delimiters are no longer removed.

- Aztec/Classes/TextKit/TextStorage.swift
Fixes # 
https://github.com/wordpress-mobile/WordPress-iOS/issues/9887
To test:
- On an iPad or an iPad simulator, launch Photos, then go Home. 
- Launch WordPress and start a new post. Swipe up from the bottom, revealing the dock.
- Long press and drag the photo app to the right or left side of the WordPress app. Wait for photos to outline its window and let go.
- In Photos > album view, long press a photo and drag it to WordPress, in the main post body area. When you see a green plus icon in the corner of the photo, let go of the photo to drop it into the post. Wait for it to upload.
- Using the toolbar, tap the plus button to add media. Select an image to add.
- Publish the post.
- Visit /wp-admin/ and find the published post. Use the code view to verify that the `size-full` CSS class …
> Fixes drag and drop images do not get `size-full` CSS class upon posting

- WordPressEditor/WordPressEditor.xcodeproj/project.pbxproj
- WordPressEditor/WordPressEditor/Classes/Extensions/String+RegEx.swift
- WordPressEditor/WordPressEditorTests/Extensions/StringRegExTests.swift
A description of this issue can be found here: https://github.com/wordpress-mobile/WordPress-iOS/issues/9941
Before reviewing this PR, let's make sure https://github.com/wordpress-mobile/AztecEditor-iOS/pull/1021 is merged, since this branch includes some of the changes from it.
1. Open the Calypso / Gutenberg editor.
2. Switch to HTML mode and paste just: `a\u{0309}`
3. Switch back to visual mode.  If it didn't crash, we're good.
> Fixes a crashing issue with regexes and Mn-class unicode characters.

- Aztec/Classes/TextKit/TextView.swift
Fixes an issue that was causing the default text color to sometimes change.
We no longer copy use `textColor` as the default text color property for `Aztec.TextView`.  The text color can be set through the default attributes directly.
This fix moves us towards resolving #1024.
This is how it looked originally:
In order to test this properly, you need to copy the "Overview" paragraph shown in this GIF (try to match the copied range), from [the WordPress Wikipedia page](https://en.wikipedia.org/wiki/WordPress).
Then follow the steps shown below and make sure the text is not all blue as it was originally.
> Fixes an issue that was causing the default text color to sometimes change.

- Aztec/Classes/Extensions/UIPasteboard+Helpers.swift
- Aztec/Classes/TextKit/TextStorage.swift
- Aztec/Classes/TextKit/TextView.swift
This PR improves drastically our support for pasting HTML content in Aztec.
Moves forward #1024.
Fixes #1020.
In this PR I:
- Cleaned up the `UIPasterboard+Helpers.swift` code a bit.
- Converted some calculated properties into methods, since the `Data` -> `NSAttributedString` conversion is most likely `O(n)` at least.
- Reordered some methods alphabetically, to make it easier to look them up.
- Added some extra methods to `UIPasteboard` for handling URLs and HTML.
- Improved the pasting logic and cleaned up its code a bit.
- Added a method to be able to replace ranges in the attributed string with new HTML content.
Here's an example of how this looks:
The pasted HTML can contain a lot of information (CSS inline styles, IDs, etc).
We'll add a customization step in the plugin so that each …
> Better support for pasting HTML in Aztec.

- Aztec/Classes/TextKit/TextView.swift
- AztecTests/TextKit/TextViewTests.swift
"Paste and Match" has been renamed to "Paste without Formatting".
There's also a minor refactor in the code, to make it simpler and to make sure links are stripped when pasting without formatting.
**EDIT:** "Paste without Formatting" didn't have undo support.  I've just added it.
Fixes #1028 
**Test 1:**
- Open the plain HTML standard demo.
- Copy any styled text.
- Move to caret to any other position.
- Paste.
Make sure the original style is maintained in the pasted text.
**Test 2:**
Repeat test 1 but copy styled text from Safari.
**Test 3:**
- Open the plain HTML standard demo.
- Copy any styled text.
- Move to caret to any other position.
- Paste without Formatting.
Make sure the formatting from the caret position is used for the pasted text.
**Test 4:**
Repeat test 3 but copy styled …
> Improve pasting label

- Aztec/Classes/Constants/HTMLConstants.swift
- Aztec/Classes/Formatters/Implementations/LinkFormatter.swift
- Aztec/Classes/TextKit/TextView.swift
- AztecTests/TextKit/TextViewTests.swift
- Example/Example/EditorDemoController.swift
- Example/Example/SampleContent/content.html
Refs: https://github.com/wordpress-mobile/WordPress-iOS/pull/10059 and https://github.com/wordpress-mobile/WordPress-iOS/issues/7670
This PR adds support for the target attribute on `a` elements.
This is implemented using the already existing HTMLRepresentation element.
To test:
- Open the demo app.
- Select the links provided in the sample content
- Tap on the link button
- see if the target shows correctly
- Edit the target and change the value
- Switch to HTML 
- Check the value is updated correctly.
> Implements editing of target attribute in .A elements

- AztecTests/TextKit/TextViewTests.swift
- WordPressEditor/WordPressEditor.xcodeproj/project.pbxproj
- WordPressEditor/WordPressEditor/Classes/Extensions/ImageAttachment+WordPress.swift
- WordPressEditor/WordPressEditor/Classes/Plugins/WordPressPlugin/Calypso/GalleryShortcode/GalleryAttachmentToElementConverter.swift
- WordPressEditor/WordPressEditor/Classes/Processors/ShortcodeProcessor.swift
- WordPressEditor/WordPressEditorTests/Extensions/ImageAttachmentWordPressTests.swift
- WordPressEditor/WordPressEditorTests/Extensions/MediaAttachmentWordPressTests.swift
- WordPressEditor/WordPressEditorTests/Extensions/VideoAttachmentWordPressTests.swift
- WordPressEditor/WordPressEditorTests/WordPressPlugin/Calypso/CaptionShortcode/CaptionShortcodeInputProcessorTests.swift
- WordPressEditor/WordPressEditorTests/WordPressPlugin/Calypso/GalleryShortcode/GalleryAttachmentToElementConverterTests.swift
- WordPressEditor/WordPressEditorTests/WordPressPlugin/Calypso/GalleryShortcode/GalleryElementToTagConverterTests.swift
- WordPressEditor/WordPressEditorTests/WordPressPlugin/Gutenberg/GutenblockTests.swift
Adds more unit tests.
Fixes an issue in ImageAttachment+WordPress that was causing the `class` attribute to never be removed.
Moves forward #1032 
Just run the unit tests and make sure they don't fail.
> Adds more unit tests.

- Aztec/Classes/Constants/HTMLConstants.swift
- Aztec/Classes/Formatters/Implementations/LinkFormatter.swift
Fixes #1041 
To test:
- Check that inserted or update link always set the `rel=noopener` attribute
> Add no opener attribute when adding targets.

- Aztec/Classes/Libxml2/DOM/Data/ElementNode.swift
- WordPressEditor/WordPressEditorTests/WordPressPlugin/Gutenberg/GutenbergInputHTMLTreeProcessorTests.swift
Fixes #1052.
1. Run the unit tests.
2. Paste this in HTML mode and switch to visual.  Make sure the test at the bottom is not lost:
```html
a
<figure class="wp-block-image alignright"><img src="https://wordpress.org/gutenberg/files/2017/12/Dropcap.png" height="234" alt="" width="312"></figure>
This text will be lost
```
> Fixes a data loss issue.

- Aztec.xcodeproj/project.pbxproj
- Aztec/Classes/Libxml2/DOM/Data/CSSAttribute.swift
- Aztec/Classes/Libxml2/DOM/Data/CSSAttributeType.swift
- Aztec/Classes/Libxml2/DOM/Logic/CSS/BoldCSSAttributeMatcher.swift
- AztecTests/New Group/AttributesToStringAttributes/BoldElementAttributeConverterTests.swift
- AztecTests/New Group/AttributesToStringAttributes/ItalicElementAttributeConverterTests.swift
- AztecTests/New Group/AttributesToStringAttributes/UnderlineElementAttributeConverterTests.swift
This PR adds some standard, convenience CSS attributes as static members of `CSSAttribute`.
It follows the same principle used for `UIColor.red` and other colors.
This PR also adds some unit tests for previously added code.
> Adds standard CSS attributes. Adds unit tests.

- Aztec/Classes/Libxml2/DOM/Data/Element.swift
- Aztec/Classes/NSAttributedString/Conversions/HTMLConverter.swift
- Aztec/Classes/TextKit/TextView.swift
Fixes #1066 
As @aerych mentioned, pasting from the Notes App was working correctly on WPv10.8.1.
The aztec changes for that release was from `1.0.0-beta.25.1` to `1.0.2` (I believe).
The important PR that seems to have broken pasting from Notes app is #1026 (Better support for pasting HTML).
The down side of that change is that now, pasting from Notes will be translated into HTML, and that HTML brings a series of tags that are not recognized by Aztec, like `<head>`, `<meta>`, `<style>` and `<body>`.
In particular, the `<body>` tag brings all the content, but since the tag is not recognized, the content is replaced with the `[BODY]` placeholder.
Ideally, we would add support for all those tags (I guess?), but it would be to handle rendering full page HTML code ready to be rendered in a …
> Proposal to fix pasting from Notes App

- Aztec/Classes/Libxml2/DOM/Data/Attribute.swift
- Aztec/Classes/TextKit/MediaAttachment.swift
- Aztec/Classes/TextKit/ParagraphProperty/HTMLParagraph.swift
- Aztec/Classes/TextKit/ParagraphProperty/ParagraphProperty.swift
- Aztec/Classes/TextKit/TextView.swift
This PR resolves most Xcode 10 warnings.
Unfortunately unit tests can still fail in Xcode 10 so, we'll need more work to make Aztec compatible with it.
1. You can still run the unit tests and make sure the ones failing are not because of these changes.
2. Open the sample posts, switch to HTML mode and back and make sure nothing is odd.
> Resolves most Xcode 10 warnings.

- Aztec/Classes/NSAttributedString/Conversions/AttributedStringParser.swift
- AztecTests/NSAttributedString/Conversions/AttributedStringParserTests.swift
- Example/AztecExample.xcodeproj/project.pbxproj
- Example/Example/SampleContent/gallery.html
- Example/Example/ViewController.swift
Fixes [WPiOS: 10355](https://github.com/wordpress-mobile/WordPress-iOS/issues/10355)
The issue happens when parsing NSAttributedStrings back to HTML:
Having this kind of input:
```html
<li class="blocks-gallery-item">
<figure>
<figcaption>caption</figcaption>
</figure>
</li>
```
we were having back this HTML code:
```html
<ul class="wp-block-gallery columns-3 is-cropped">
<li class="blocks-gallery-item">
<figure>
</figure>
</li>
<li class="blocks-gallery-item">
<figure>
<figcaption>caption</figcaption>
</figure>
</li>
</ul>
```
The `li` tag was splitting the content of `figure ` tag.
This kind of `figure` tags inside a list is the way `Gutenberg-gallery` is constructed, so we are having troubles displaying and saving them on the mobile app.
The common behavior of Aztec is to not merge …
> Better compatibility with gutenberg gallery

- Aztec.xcodeproj/project.pbxproj
- Aztec/Classes/Extensions/String+CharacterName.swift
- Aztec/Classes/Plugin/Plugin.swift
- Aztec/Classes/Plugin/PluginManager.swift
- Aztec/Classes/TextKit/TextView.swift
- Aztec/Classes/TextKit/TextViewPasteboardDelegate.swift
- WordPressEditor/WordPressEditor.xcodeproj/project.pbxproj
- WordPressEditor/WordPressEditor/Classes/Plugins/WordPressPlugin/Calypso/Embeds/WordPressPasteboardDelegate.swift
- WordPressEditor/WordPressEditor/Classes/Plugins/WordPressPlugin/WordPressPlugin.swift
- WordPressEditor/WordPressEditor/Classes/Processors/EmbedURLProcessor.swift
- WordPressEditor/WordPressEditorTests/Processors/EmbedURLProcessorTests.swift
- WordPressEditor/WordPressEditorTests/WordPressPlugin/WordPressPluginTests.swift
Currently, when pasting a URL that could be transformed into an embed (such as a YouTube link), it’ll be turned into an `<a>` tag instead, which is frustrating for several users we're talking to. This solves the issue in the simplest possible way, which may not be the best long-term, so this should probably be treated as a proof-of-concept for a fix, rather than the fix itself (unless everyone likes the direction). 
This pull request pre-empts the URL transformation of links if there’s no text selected (for instance, the user might actually want to make some text like “click here” be the link to the YouTube video, and we want the link transformation to work in that case). This allows a pasteboard that contains only a URL to be evaluated for whether it can be embedded, and if it can, it …
> Proposal to fix pasting embeds

- Aztec/Classes/Libxml2/DOM/Data/Node.swift
- Aztec/Classes/Libxml2/DOM/Data/TextNode.swift
- Aztec/Classes/NSAttributedString/Conversions/AttributedStringSerializer.swift
- WordPressEditor/WordPressEditor/Classes/Plugins/WordPressPlugin/Gutenberg/GutenpackAttachmentRenderer.swift
Resolves some issues with the MORE Gutenberg block.
Moves forward: https://github.com/wordpress-mobile/WordPress-iOS/issues/10371
This PR also sneaks in some unrelated changes here: https://github.com/wordpress-mobile/AztecEditor-iOS/pull/1077/files#diff-b8006fa672b42a2ab3040720285a175dL6
They're just documentation updates and should be harmless.  Apologies for the mix up.
In the Gutenberg empty editor, pasting the following HTML:
```html
<p>This is text</p>
<p>This is more text</p>
```
Then switching to visual and back to HTML, would generate this output.
```html
<p>This is text</p>
This is more text
```
This PR solves this specific issue.
> Resolves some issues with more gutenberg blocks.

- Aztec.xcodeproj/project.pbxproj
- Aztec/Classes/Converters/ElementsToAttributedString/Base/AttachmentElementConverter.swift
- Aztec/Classes/Converters/ElementsToAttributedString/Base/ElementConverter.swift
- Aztec/Classes/Converters/ElementsToAttributedString/Implementations/BRElementConverter.swift
- Aztec/Classes/Converters/ElementsToAttributedString/Implementations/CiteElementConverter.swift
- Aztec/Classes/Converters/ElementsToAttributedString/Implementations/FigcaptionElementConverter.swift
- Aztec/Classes/Converters/ElementsToAttributedString/Implementations/FigureElementConverter.swift
- Aztec/Classes/Converters/ElementsToAttributedString/Implementations/GenericElementConverter.swift
- Aztec/Classes/Converters/ElementsToAttributedString/Implementations/HRElementConverter.swift
- Aztec/Classes/Converters/ElementsToAttributedString/Implementations/ImageElementConverter.swift
- Aztec/Classes/Converters/ElementsToAttributedString/Implementations/VideoElementConverter.swift
- Aztec/Classes/Libxml2/DOM/Data/ElementNode.swift
- Aztec/Classes/NSAttributedString/Conversions/AttributedStringParser.swift
- Aztec/Classes/NSAttributedString/Conversions/AttributedStringSerializer.swift
- AztecTests/New Group/ElementToAttributedString/GenericElementConverterTests.swift
- AztecTests/TextKit/TextStorageTests.swift
- AztecTests/TextKit/TextViewTests.swift
- WordPressEditor/WordPressEditor/Classes/Plugins/WordPressPlugin/Calypso/GalleryShortcode/GalleryElementConverter.swift
- WordPressEditor/WordPressEditor/Classes/Plugins/WordPressPlugin/Gutenberg/GutenblockConverter.swift
- WordPressEditor/WordPressEditor/Classes/Plugins/WordPressPlugin/Gutenberg/GutenpackConverter.swift
- WordPressEditor/WordPressEditorTests/WordPressPlugin/Calypso/GalleryShortcode/GalleryElementConverterTests.swift
- WordPressEditor/WordPressEditorTests/WordPressPlugin/WordPressPluginTests.swift
Fixes #1078 
This issue provides a mechanism for making sure data isn't lost on HTML elements without actual contents.
**Test 1:**
Run the newly added unit test.
**Test 2:**
As reported [here](https://github.com/wordpress-mobile/AztecEditor-iOS/issues/1078).
1. Open the empty Gutenberg demo.
2. Paste the following HTML content:
```html
<div style="height:100px" aria-hidden="true" class="wp-block-spacer"></div>
```
3. Switch to visual and back.
Make sure the content is still there.
> Fixes a bug that was causing certain HTML contents to be lost.

- Aztec/Classes/Extensions/String+HTML.swift
- AztecTests/TextKit/TextViewTests.swift
- WordPressEditor/WordPressEditorTests/WordPressPlugin/WordPressPluginTests.swift
Non breaking spaces were being removed by `WordPressEditor` and were not being properly encoded when switching back to HTML mode in Aztec.
1. Open either the Aztec or WordPressEditor empty demo.
3. Write several `&nbsp;`s, in multiple lines, or one after the other.
4. Switch to visual mode and back to HTML mode.
Make sure the `&nbsp;`s are still there and properly encoded for HTML.
Props to @charliescheer for finding this issue and reporting it.
> Non breaking spaces are no longer removed by WordPressEditor.

- Aztec.xcodeproj/project.pbxproj
- Aztec/Classes/Converters/ElementsToAttributedString/Implementations/ImageElementConverter.swift
- Aztec/Classes/Converters/ElementsToAttributedString/Implementations/VideoElementConverter.swift
- Aztec/Classes/Extensions/Array+Attribute.swift
- Aztec/Classes/NSAttributedString/Conversions/AttachmentToElementConverter/ImageAttachmentToElementConverter.swift
- Aztec/Classes/NSAttributedString/Conversions/AttachmentToElementConverter/VideoAttachmentToElementConverter.swift
- Aztec/Classes/TextKit/MediaAttachment.swift
- AztecTests/Renderers/CommentAttachmentRendererTests.swift
- AztecTests/Renderers/HTMLAttachmentRendererTests.swift
- AztecTests/TextKit/TextViewTests.swift
- Example/Example/AttachmentDetailsViewController.swift
- Example/Example/EditorDemoController.swift
- WordPressEditor/WordPressEditor/Classes/Extensions/ImageAttachment+WordPress.swift
- WordPressEditor/WordPressEditor/Classes/Extensions/MediaAttachment+WordPress.swift
- WordPressEditor/WordPressEditor/Classes/Extensions/VideoAttachment+WordPress.swift
- WordPressEditor/WordPressEditor/Classes/Plugins/WordPressPlugin/Calypso/GalleryShortcode/GalleryAttachmentToElementConverter.swift
- WordPressEditor/WordPressEditor/Classes/Plugins/WordPressPlugin/Calypso/GalleryShortcode/GalleryElementConverter.swift
- WordPressEditor/WordPressEditorTests/Extensions/ImageAttachmentWordPressTests.swift
- WordPressEditor/WordPressEditorTests/Extensions/MediaAttachmentWordPressTests.swift
- WordPressEditor/WordPressEditorTests/Extensions/VideoAttachmentWordPressTests.swift
- WordPressEditor/WordPressEditorTests/WordPressPlugin/Calypso/GalleryShortcode/GalleryAttachmentToElementConverterTests.swift
Fixes all unit tests.
This PR:
- Removes two unit tests since the offer dubious value, and are hard to maintain ([here](https://github.com/wordpress-mobile/AztecEditor-iOS/pull/1083/files#diff-b34007032479e80681066243a95e3dedL50) and [here](https://github.com/wordpress-mobile/AztecEditor-iOS/pull/1083/files#diff-4d3fa99b1de29afdcfa965e25df61a09L55)).
- Changes [the extra attributes in `MediaAttachment`](https://github.com/wordpress-mobile/AztecEditor-iOS/pull/1083/files#diff-02f978663f7d3e9a329ad11de178526fR31) so that they're ordered.  This change is what forced most of the other changes you see in this PR.
- Also changes [the reduction of HTML class values](https://github.com/wordpress-mobile/AztecEditor-iOS/pull/1083/files#diff-cc023a7c6bf6a6207feecd14bc7d7e0eR42) so that it's ordered …
> Fixes all unit tests in Xcode 10.

- Aztec/Classes/EditorView/EditorView.swift
This is a very simple PR that fixes `setHTML()` and `getHTML` in `EditorView`.
This doesn't have an impact right now since the demo never starts in HTML mode, and it doesn't impact WPiOS either since it's not currently using `EditorView`, but the previous logic was flawed anyway.
While not a priority fix, I noticed the logic flaw while working in other issues and wanted to fix it quickly.
Run the unit tests and make sure all is fine.
> Improves the HTML setter and getter for EditorView.

- WordPressEditor/WordPressEditor/Classes/Processors/EmbedURLProcessor.swift
- WordPressEditor/WordPressEditorTests/Processors/EmbedURLProcessorTests.swift
Adds test cases to ensure this continues to work
**To test:**
- The added unit tests have examples of links that weren't working before – ensuring the unit tests pass should be sufficient testing
> Fix bugs with m.youtube URLs and IDs with dashes

- Aztec/Classes/EditorView/EditorView.swift
- Aztec/Classes/TextKit/TextView.swift
This PR fixes the undo stack being reset when switching editing modes.
By resolving this issue we will be able to properly record when the content has changes by asking the undo manager directly.
The undo stack is different in visual mode and HTML mode.  Atomic edits are only recorded in the mode you're in when they're registered.
The editing mode you're not in will only record a big change when switching.
**Test 1:**
- Open any of the editor demos with content.
- Undo
Make sure the initial content is never removed.
**Test 2:**
- Open an empty editor demo.
- Write whatever you want.
- Copy and paste content.
- Apply styles.
- Switch to HTML mode.
- Do some more edits.
- Switch back to visual.
- Undo as much as you want, and Redo.
Make sure it all works.
> Undo is no longer reset when switching editing modes.

- Aztec/Classes/Formatters/Implementations/CiteFormatter.swift
- Aztec/Classes/TextKit/TextView.swift
This moves forward #1090.  The issue is not completely solved as it's a complex combination of several issues.  This PR just fixes an initial part of it.
This PR makes sure `<cite>` elements are removed when the blockquote style is removed.
1. Open the empty standard HTML demo.
3. Paste:
```html
<blockquote>
<p>Some quote</p>
<cite>by Me</cite>
</blockquote>
```
4. Switch back to visual mode and toggle the blockquote in the cite line.
5. Switch back to HTML mode and make sure the `<cite>` tag is removed.
> Fix blockquote cite's removal.

- Aztec/Classes/Extensions/NSAttributedString+Analyzers.swift
- Aztec/Classes/TextKit/TextView.swift
Moves forward #1090.
This PR fixes part of the logic that takes care of persisting custom attributes while typing.  Previously we were forcing the typing attributes to be maintained while typing, which means there was no way to turn some styles off (such as `<cite>` and `<code>`).
While this improves how those styles are maintained as we type and move through the document, there are still issues with how blockquotes are expanded in visual mode:
- Gutenberg blockquotes are still breaking.
- Multi-line cites still need fixing.
- While cite is currently being removed, the italic styling it enables is not.
1. Open the empty standard HTML editor.
3. Paste:
```html
<blockquote>
<p>Some quote</p>
<cite>by Me</cite>
</blockquote>
```
4. Switch to visual mode.
5. Place the …
> Fix persistence of custom string attributes.

- Aztec/Classes/Formatters/Base/FontFormatter.swift
- Aztec/Classes/Formatters/Implementations/FigcaptionFormatter.swift
- Aztec/Classes/Formatters/Implementations/FigureFormatter.swift
- Aztec/Classes/TextKit/TextView.swift
Moves forward #1090.
Pressing enter while in visual-mode, in a line that has both `<blockquote>` and `<cite>`, will cause the blockquote to be closed and the styles removed.
If the user wants a multi-line citation, they can use the SHIFT + ENTER combo.
The code changes are not as clean as I'd like, because our current way to access formatter causes a lot of code duplication, but this is a quick fix to keep the ball rolling.
Follow the steps shown in the demo above.
> Blockquote + cite is now ended when pressing ENTER.

- Aztec/Classes/GUI/FormatBar/FormattingIdentifier.swift
- Aztec/Classes/TextKit/TextView.swift
- AztecTests/TextKit/TextViewTests.swift
- Example/Example/EditorDemoController.swift
This is just a quick maintenance PR to try and organize the formatters code a bit, and try to make it easier to maintain and extend.  This will be used in upcoming PRs.
Format identifiers can now be extended.  This is just a quick maintenance PR.
Make sure the library and example app build fine.
Make sure the unit tests build and run fine.
> Formatter identifiers are now extensible

- Aztec/Classes/Converters/ElementsToAttributedString/Implementations/FigcaptionElementConverter.swift
- Aztec/Classes/Formatters/Base/AttributeFormatter.swift
- Aztec/Classes/Formatters/Base/FontFormatter.swift
- Aztec/Classes/Formatters/Implementations/FigcaptionFormatter.swift
- Aztec/Classes/Formatters/Implementations/FigureFormatter.swift
- Aztec/Classes/Formatters/Implementations/HeaderFormatter.swift
- Aztec/Classes/TextKit/TextView.swift
- AztecTests/Formatters/HeaderFormatterTests.swift
- AztecTests/NSAttributedString/Conversions/AttributedStringParserTests.swift
- AztecTests/NSAttributedString/Conversions/AttributedStringSerializerTests.swift
Formatters had a property named `placeholderAttributes` which once had a purpose, but currently has none.
This is a small maintenance PR that will be followed up with a simplification of formatters.  This is a small step towards fixing #1090.
To do so, I'll unify all registered formatters in a single spot in `Aztec.TextView`.
Make sure the example app runs fine.
Make sure the unit tests run fine.
> Remove the placeholderAttributes formatter property.

- Aztec/Classes/Formatters/Implementations/HTMLParagraphFormatter.swift
- Aztec/Classes/Formatters/Implementations/HeaderFormatter.swift
This is needed for Gutenberg's RNAztecView.
Implemented in this PR https://github.com/wordpress-mobile/react-native-aztec/pull/98
This will be merged if the previously mentioned PR is approved with the proposed solution, or if any other solution need these changes.
To test:
- Check that there are no build errors.
> Adding public access level HeaderFormatter

- WordPressEditor/WordPressEditor/Classes/Plugins/WordPressPlugin/Gutenberg/GutenbergOutputHTMLTreeProcessor.swift
- WordPressEditor/WordPressEditorTests/WordPressPlugin/Gutenberg/GutenbergInputHTMLTreeProcessorTests.swift
- WordPressEditor/WordPressEditorTests/WordPressPlugin/Gutenberg/GutenbergOutputHTMLTreeProcessorTests.swift
Fixes #1111.
Fixes a crashing bug in GutenbergOutputHTMLTreeProcessor.
Also adds a unit test to prevent a regression.
Run the newly added unit test.
If you run the same test after changing `prefix()` to `prefix(upTo:)` you'll notice it'll crash.
> Fixes a crashing bug in GutenbergOutputHTMLTreeProcessor.

- WordPress-Aztec-iOS.podspec
- WordPress-Editor-iOS.podspec
- WordPressEditor/WordPressEditor/Classes/Plugins/WordPressPlugin/Gutenberg/GutenbergOutputHTMLTreeProcessor.swift
- WordPressEditor/WordPressEditorTests/WordPressPlugin/Gutenberg/GutenbergInputHTMLTreeProcessorTests.swift
- WordPressEditor/WordPressEditorTests/WordPressPlugin/Gutenberg/GutenbergOutputHTMLTreeProcessorTests.swift
Reverts wordpress-mobile/AztecEditor-iOS#1114
I reverted this as I merged too quickly. Opening it to merge correctly this time.
> Revert "Revert "Merge Release/1.3.3 into develop""

- Aztec/Classes/Converters/ElementsToAttributedString/Implementations/HRElementConverter.swift
- Aztec/Classes/Converters/ElementsToAttributedString/Implementations/VideoElementConverter.swift
- Aztec/Classes/TextKit/TextStorage.swift
- WordPressEditor/WordPressEditor/Classes/Plugins/WordPressPlugin/Gutenberg/GutenpackConverter.swift
- WordPressEditor/WordPressEditorTests/WordPressPlugin/WordPressPluginTests.swift
Fixes a bug that was causing self-closing blocks to be stripped from posts.
Example self-closing block:
```html
```
1. Launch the Gutenberg editor demo.
2. Go to HTML and paste the example self-closing block provided above.
3. Switch to visual mode.  The self-closing block will have a visual representation.
4. Switch to HTML mode, the self-closing block should still be there.
Feel free to play with variants of this test.
> Fixes a bug that was stripping self-closing blocks.

- Aztec.xcodeproj/project.pbxproj
- Aztec/Classes/Converters/ElementsToAttributedString/Implementations/GenericElementConverter.swift
- Aztec/Classes/Converters/StringAttributesToAttributes/Implementations/BoldStringAttributeConverter.swift
- Aztec/Classes/Extensions/NSAttributedStringKey+Aztec.swift
- Aztec/Classes/Formatters/Implementations/HeaderFormatter.swift
- Aztec/Classes/Formatters/Implementations/ShadowBoldFormatter.swift
- Aztec/Classes/TextKit/ParagraphProperty/Header.swift
- Aztec/Classes/TextKit/TextView.swift
- AztecTests/Formatters/ShadowBoldFormatterTests.swift
Fixes: https://github.com/wordpress-mobile/gutenberg-mobile/issues/351
This PR updates the style of Heading block based on https://github.com/wordpress-mobile/gutenberg-mobile/issues/351#issuecomment-456522533 
WPiOS PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/10912
mobile-gutenberg PR: https://github.com/wordpress-mobile/gutenberg-mobile/pull/525
**Changes Made**
1. Heading font sizes are updated
2. Headings made bold by default
3. ShadowBoldFormatter is added to mimic bolding on already bold headings, it uses shadow attribute to mimic the extra boldness.
**The Problem**
We want to use bold font with Heading blocks by default. However, we don't want to generate bold output in the html unless user intentionally selects B option from toolbar. That makes it a bit challenging …
> Make heading styling distinguishable from paragraph

- CODE-OF-CONDUCT.md
Adds the same Code of Conduct we're using in WordPress-iOS, to Aztec.
Moves ahead #1125
> Adds the Code of Conduct to Aztec.

- Aztec/Classes/Converters/ElementsToAttributedString/Implementations/GenericElementConverter.swift
- Aztec/Classes/Converters/StringAttributesToAttributes/Implementations/BoldStringAttributeConverter.swift
- Aztec/Classes/Libxml2/DOM/Data/Element.swift
- Aztec/Classes/Libxml2/DOM/Data/ElementNode.swift
- AztecTests/New Group/StringAttributesToAttributes/BoldStringAttributeConverterTests.swift
There was an issue with a bold converter that was causing `b` tags to convert to a combination of `b` and `strong` tags.  This PR fixes that.
Fixes https://github.com/wordpress-mobile/AztecEditor-iOS/issues/1137
Additionally, this PR simplifies the `equivalentNames` calculated properly to work directly with `Elements` and to remove some extra code that wasn't needed.
1. Open the empty editor demo.
3. Type `<b>Hello!</b>`.
4. Switch to visual and back to HTML mode.
Make sure the bold tag hasn't been duplicated with a `strong` tag.
> Fix bold converting issue.

- Aztec.xcodeproj/project.pbxproj
- Aztec/Classes/Converters/StringAttributesToAttributes/Implementations/BoldStringAttributeConverter.swift
- Aztec/Classes/Converters/StringAttributesToAttributes/Implementations/ItalicStringAttributeConverter.swift
- Aztec/Classes/Converters/StringAttributesToAttributes/Implementations/UnderlineStringAttributeConverter.swift
- Aztec/Classes/Converters/StringAttributesToAttributes/Utility/HTMLStyleToggler.swift
- Aztec/Classes/Extensions/Dictionary+AttributedStringKey.swift
- AztecTests/New Group/StringAttributesToAttributes/ItalicStringAttributeConverterTests.swift
It propagates the same changes across different attribute converters (`em` and `u`).
It also adds unit tests for the case of `em` and `i`.  Running those tests in `develop` should fail.
This PR builds up on the fix in https://github.com/wordpress-mobile/AztecEditor-iOS/pull/1138.
Run the provided tests in develop and make sure the first one fails.
Run the tests in this PR and make sure none fail.
1. Open the empty editor.
3. Type `<i>Hello!</i>`.
4. Switch to visual mode and back to HTML mode.
Make sure the final conversion doesn't have an extra `em` tag.
1. Open the empty editor.
3. Type `<b>Hello!</b>`.
4. Switch to visual mode and back to HTML mode.
Make sure the final conversion doesn't have an extra `strong` tag.
1. Open the empty …
> Standardize string-attribute-conversion logic.

- Aztec/Classes/TextKit/TextView.swift
- AztecTests/TextKit/TextViewTests.swift
Removes several workarounds we had added for iOS 11 support.
This PR also fixes a unit test that had bad logic (that was being "hidden" by the iOS 11 workarounds).
This PR should offer us the advantage of improving performance in Aztec slightly, since we're running less code at each keystroke.
Format bar style desynch: https://github.com/wordpress-mobile/AztecEditor-iOS/pull/753
Delete Backwards workaround: https://github.com/wordpress-mobile/AztecEditor-iOS/pull/752
Losing styles after typing 1 character: https://github.com/wordpress-mobile/AztecEditor-iOS/issues/725
1. Download the oldest iOS 11 simulator you can find.
2. Run the unit tests.
3. Run the app and test the issues reported above.
Repeat test 1 in iOS 12.
> Removes iOS 11 formatting workarounds

- .circleci/config.yml
- Scripts/build.sh
This removes the Travis config and does some related cleanup.
To test:
- CircleCI checks are still green.
> Remove Travis CI configuration

- .circleci/config.yml
There were some failures on CircleCI last week due to the specs repo being out of date when validating `WordPress-Editor-iOS.podspec`. This ensures it is always updated.
Note that it is not needed for `WordPress-Aztec-iOS` as that has no dependencies.
To test:
- See that the checks are green and that the repo is updated (it will also run slower as a result).
> CircleCI: Update Specs repo when validating WordPress-Editor-iOS.podspec

- WordPress-Aztec-iOS.podspec
- WordPress-Editor-iOS.podspec
This PR merges release/1.5.0 into master. 
Note that  WordPress-Aztec-iOS pod has been already pushed to Cocoapods trunk in order to allow the validation of WordPress-Editor-iOS.
To test:
1. Verify that CI tests pass.
> Release v. 1.5.0

- WordPressEditor/WordPressEditor/Classes/Plugins/WordPressPlugin/WordPressInputCustomizer.swift
- WordPressEditor/WordPressEditor/Classes/Plugins/WordPressPlugin/WordPressOutputCustomizer.swift
Fixes #1160 
This PR make sure the shortcode video processors are run in Aztec Gutenberg mode.
To test:
1. Open an Gutenberg empty demo and switch to HTML mode.
2. Paste the following: ```[video src="https://videos.files.wordpress.com/kUJmAcSf/bbb_sunflower_1080p_30fps_normal.mp4" ]```
3. Switch to visual mode
4. The video of the shorcode is displayed.
5. Switch back to HTML and check the shortcode is there.
> Use video shortcodes  processors  on Gutenberg.

- Aztec/Classes/Extensions/String+EndOfLine.swift
- Aztec/Classes/Libxml2/DOM/Data/ElementNode.swift
- AztecTests/TextKit/TextViewTests.swift
Fixes #1159
This PR implements a fix to support empty list elements like this: `<ul><li></li></ul>`
To test:
- Open an empty demo 
- Switch to HTML and add this: `<ul><li></li></ul>`
- Switch to Visual and see if the element is displayed.
> Empty list

- Aztec/Classes/TextKit/TextView.swift
- AztecTests/TextKit/TextViewTests.swift
Fixes https://github.com/wordpress-mobile/WordPress-iOS/issues/8826
**Before**
- Launch the WP app on a simulator, immediately after doing Hardware > Erase all Content and Settings (and thus has a clean pasteboard)
- Copy some text out of an Aztec post
- App will crash due to out-of-bounds exception
**After**
- Launch the test WP app as before (don't forget to Erase all Content and Settings)
- Copy some text out of Aztec post
- App will not crash
You could also run the updated Unit Tests – they demonstrate the issue in a more reliable way – the steps above didn't cause the crash _every_ time for some reason – it may have to do with content synced between the simulator and the host computer? 🤔
> Fix a crash when system pasteboard is empty

- Aztec/Classes/TextKit/TextView.swift
Refactor TextView key commands to make key commands publicly and independently accessible.
This is needed to override `override open var keyCommands: [UIKeyCommand]? ` using the key commands defined internally by Aztec, without depending on the array indexing of them.
This PR has no change in logic.
To test:
- All unit tests should pass.
- Smoke test the example app.
- Test steps in `gutenberg-mobile` PR: https://github.com/wordpress-mobile/gutenberg-mobile/pull/889
> Refactor TextView key commands.

- WordPress-Aztec-iOS.podspec
- WordPress-Editor-iOS.podspec
- WordPressEditor/WordPressEditor/Classes/Extensions/String+RegEx.swift
- WordPressEditor/WordPressEditorTests/WordPressPlugin/Calypso/AutopRemovep/AutoPProcessorTests.swift
Fixes https://github.com/wordpress-mobile/WordPress-iOS/issues/11515
WPiOS related PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/11529
The original issue describes the introduction of `e>` characters when saving a post.
I was able to reproduce this issue under these conditions:
- Any two pair of tags where the first tag holds text (as the `blockquote` tag)
- Both tags separated by a new line.
- The first tags contains a utf16 character as part of its content (as `—`).
In this case, the range used to insert `</blockquote>` when inserting the p tags was shifted by that character, inserting it earlier, and leaving the last two characters behind (`e>`).
The issue was that even though `newString` is a copy of the original string, the range created by `let matchRange = …
> Fix AutoPProcessor for Swift 5

- Aztec.xcodeproj/project.pbxproj
- Aztec/Classes/Extensions/NSBundle+AztecBundle.swift
- Aztec/Classes/GUI/Assets.swift
- WordPress-Aztec-iOS.podspec
This makes the changes needed for the Aztec pod to be installed as a static or dynamic framework (with or without `use_frameworks!`). Currently, it does not work correctly when installed statically as the `.xcassets` file can conflict with the host app. The Editor pod already works fine (it doesn't have an `xcassets` file).
The changes are as follows:
- Use `resource_bundles` to move resources to `WordPress-Aztec-iOS.bundle`. This keeps the pod's resources separate from the main app.
- Replace all uses of `Bundle(for:..)` with the new `Bundle.aztecBundle` helper.
This will allow us to proceed with https://github.com/wordpress-mobile/WordPress-iOS/pull/11559.
To test:
- Run the example app and confirm it looks fine (the image place holder and video play button should be shown correctly).
> Compatibility with both CocoaPods dynamic and static frameworks

- Aztec/Classes/Extensions/NSBundle+AztecBundle.swift
@SergioEstevao spotted an issue with my changes in https://github.com/wordpress-mobile/AztecEditor-iOS/pull/1182 when Aztec is integrated in WPiOS as a static framework.
It turns out there was a slight typo in the bundle helper. it works correctly now.
To test:
- Point WPiOS to this branch.
- Test that a post with a video loads correctly (it shows the play button).
> Fix typo in NSBundle path

- WordPress-Aztec-iOS.podspec
- WordPress-Editor-iOS.podspec
Merge Release/1.6.3 into master.
Includes fix from https://github.com/wordpress-mobile/AztecEditor-iOS/pull/1187
> Merge Release/1.6.3 into master

- Aztec/Classes/NSAttributedString/Conversions/AttributedStringParser.swift
- AztecTests/NSAttributedString/Conversions/AttributedStringParserTests.swift
Make the implementation of the strikethrough formatting to use the `<s>` element by default.
This will help with GB compatibility.
To test:
- Open an empty demo
- Select the option Strikethrough on the toolbar
- type some words
- Switch to HTML
- Make sure `<s>` was used.
- Switch to a demo with content
- Check on the demo content if the Strikethrough elements activate the toolbar.
> Make default HTML elements to represent striketrough to be s

- Aztec.xcodeproj/project.pbxproj
- Aztec/Classes/Converters/ElementsToAttributedString/Base/ElementConverter.swift
- Aztec/Classes/Converters/ElementsToAttributedString/Implementations/BRElementConverter.swift
- Aztec/Classes/Converters/ElementsToAttributedString/Implementations/CiteElementConverter.swift
- Aztec/Classes/Converters/ElementsToAttributedString/Implementations/FigcaptionElementConverter.swift
- Aztec/Classes/Converters/ElementsToAttributedString/Implementations/FigureElementConverter.swift
- Aztec/Classes/Converters/ElementsToAttributedString/Implementations/GenericElementConverter.swift
- Aztec/Classes/Converters/ElementsToAttributedString/Implementations/HRElementConverter.swift
- Aztec/Classes/Converters/ElementsToAttributedString/Implementations/ImageElementConverter.swift
- Aztec/Classes/Converters/ElementsToAttributedString/Implementations/LIElementConverter.swift
- Aztec/Classes/Converters/ElementsToAttributedString/Implementations/VideoElementConverter.swift
- Aztec/Classes/Extensions/String+Paragraph.swift
- Aztec/Classes/Libxml2/DOM/Data/TextNode.swift
- Aztec/Classes/NSAttributedString/Conversions/AttributedStringSerializer.swift
- AztecTests/New Group/ElementToAttributedString/GenericElementConverterTests.swift
- AztecTests/TextKit/TextStorageTests.swift
- WordPressEditor/WordPressEditor/Classes/Plugins/WordPressPlugin/Gutenberg/GutenblockConverter.swift
- WordPressEditor/WordPressEditor/Classes/Plugins/WordPressPlugin/Gutenberg/GutenpackConverter.swift
- WordPressEditor/WordPressEditorTests/WordPressPlugin/Calypso/GalleryShortcode/GalleryElementConverterTests.swift
Fixes #1180 
This PR addresses the issues reported on the ticket above by creating a dedicated LIConverter in order to check when to add a intrinsic representation for the <li> before or after the children.
The main logic here is that if the Li element has children elements that are nested lists and no text defined we need to add "\n" to the content in order for the marker to be shown.
To test:
- If you set the HTML like this: 
```
<ul>
<li>One</li>
<li>
<ul>
<li>Two</li>
</ul>
</li>
</ul>
```
You should get something like this rendered:
Besides this test the remaining logic of lists should be retested:
- Create lists
- Indent element
- Change styles
- Remove list item
- Add new list item
> Fix nested lists rendering

- Aztec/Classes/TextKit/TextView.swift
- AztecTests/TextKit/TextViewTests.swift
Fixes #
This PR brings the fix for copy paste to develop.
To test:
- Copy some content from one of the demo content
- Paste it in another app, for example Notes or Reminders
- See that the content is pasted in plain text.
> Fix copy paste

- Aztec/Classes/TextKit/TextStorage.swift
- Aztec/Classes/TextKit/TextView.swift
- AztecTests/TextKit/TextViewTests.swift
This PR implements copy/cut of HTML out of Aztec TextView.
This is done by getting the HTML of the selected range and then adding it to the pasteboard.
To test:
- On the demo content copy or cut a selection that has HTML attributes (bold, italic, etc..)
- Paste it on another app that supports it. For example ~Pages~ GB web on Safari
- See that it was properly pasted.
> Add html to pasteboard when doing copy or cut.

- Aztec/Classes/Libxml2/DOM/Data/ElementNode.swift
Related #1157 
This PR is related to the issue above, but it implements a more generic approach where all block-level elements are kept even when they are empty and the only ones in the content.
To test:
- Open the empty demo app
- Switch to HTML and insert the following: ```<blockquote></blockquote>```
- Switch to Visual mode
- See if the blockquote element is displayed, you should see an empty quote
- Switch to HTML mode, and check the HTML is still there
> Make sure that standalone block elements are kept.

- Aztec/Classes/TextKit/TextView.swift
- Example/Example/EditorDemoController.swift
This PR allows the configuration of the textColor to affect the default color being used on the editor.
To test:
- Check if the textColor applied is being used.
- Try to change the color on the EditorDemoController class to see if the changes have effect.
> Allow configuration of text color

- Aztec/Classes/TextKit/TextStorage.swift
This PR just makes another method available to the outside to retrieve HTML from any attributed string.
To test:
- There is no change in the logic of aztec in any way so no tests needed.
- You can test the use of this method using this GB-mobile PR: https://github.com/wordpress-mobile/gutenberg-mobile/pull/1097
> Make available method to extract HTML from a string.

- Aztec/Classes/NSAttributedString/Conversions/HTMLConverter.swift
- Aztec/Classes/TextKit/TextStorage.swift
- Aztec/Classes/TextKit/TextView.swift
- AztecTests/TextKit/TextStorageTests.swift
Allows the replacement of last empty lines inserted by the serialisers to be replaced to a specific character.
This is special important on handling HTML that consistent in single empty list elements or quote elements where the style needs to be applied to empty lines.
To test:
- Just check if unit tests are running correctly
- You can test the use of this feature using this GB-mobile PR: https://github.com/wordpress-mobile/gutenberg-mobile/pull/1129
> Allow replacement of last empty line on Aztec

- Aztec/Classes/Extensions/UITextView+Delegate.swift
- Aztec/Classes/TextKit/TextView.swift
This changes introduces a flag to TextView to allow disabling notification of text changes that are cause because of code changes. For example when a setHTML is done by code, the TextView was sending a notification and evoking the delegate that a change in content happened.
This is special relevant on the Aztec wrapper to avoid a notification chain when setHTML is sent from the React/JS side and the component was immediately sending a notification of change back.
This will reduce the number of events being sent across the bridge from JS/Native and improved performance.
To test:
- Check the demo app/content to see if everything works fine when flag is enabled
- To check behaviour when flag in disabled you can use this PR in GB-mobile: …
> Notify changes on TextView only on user events

- Aztec/Classes/GUI/FormatBar/FormatBarItem.swift
- WordPress-Aztec-iOS.podspec
- WordPress-Editor-iOS.podspec
This PR exposes the color properties for `FormatBarItem`. This is required for implementing dark mode in WPiOS. You can test it with this WPiOS PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/12373
> Allow customisation of format bar colors

- Aztec/Classes/EditorView/EditorView.swift
- Aztec/Classes/TextKit/HTMLStorage.swift
- AztecTests/EditorView/EditorViewTests.swift
- AztecTests/TextKit/HTMLStorageTests.swift
- WordPress-Aztec-iOS.podspec
- WordPress-Editor-iOS.podspec
Refs. [WPiOS #12462](https://github.com/wordpress-mobile/WordPress-iOS/pull/12462)
This PR exposes the Editor html storage as let property in order to customize its colors due to the introduction of DarkMode. This is required for implementing dark mode in [WPiOS](https://github.com/wordpress-mobile/WordPress-iOS/pull/12462).
• Run the Unit Tests
• Run [WPiOS #12462](https://github.com/wordpress-mobile/WordPress-iOS/pull/12462)
> [Dark Mode] Expose editor html storage as property

- Aztec/Classes/Formatters/Implementations/UnderlineFormatter.swift
- Aztec/Classes/TextKit/TextView.swift
Fixes #1212 
To test:
- Open the demo app
- Select empty content
- write some text
- Apply the underline style with the toolbar
- Switch to HTML and check that the HTML uses the ```<span style="text-decoration: underline">``` element.
- Repeat but now apply the style using the shortcut menu by selecting the text and then tapping the BIU option in the context menu.
> Make underline action use a span and css by default.

- WordPress-Aztec-iOS.podspec
- WordPress-Editor-iOS.podspec
- WordPressEditor/WordPressEditor/Classes/ViewControllers/OptionsTableViewController/OptionsTablePresenter.swift
This allows to have a dark popovert presentation background color on Dark Mode.
In this way we fix a small glitch that appears when we have a black tableView background with a white `UIVisualEffectContentView`.
To test:
- Checkout and follow the instructions on https://github.com/wordpress-mobile/WordPress-iOS/pull/12616
> Making popovert presentation background color dynamic

- .circleci/config.yml
Adding a CircleCI job that will run `pod trunk push` on the podspec whenever the repo is tagged. This is already in use and tested on WordPressAuthenticator.
We can't really test this directly on the PR, but you can see it was tested here: https://github.com/wordpress-mobile/circleci-orbs/pull/38
> CircleCI: Publish pods when the repo is tagged

- .circleci/config.yml
This requires https://github.com/wordpress-mobile/circleci-orbs/pull/40 to be merged.
We have a problem with the CocoaPod publishing workflow for Aztec-iOS. `WordPress-Aztec-iOS.podspec` is a dependency of `WordPress-Editor-iOS.podspec`. This means that when the version numbers in the podspecs are bumped prior to making a new release, CI fails to validate `WordPress-Editor-iOS.podspec`  because it can't find the new version of `WordPress-Aztec-iOS`.
The solution is to make use of a reasonably recent addition to CocoaPods (https://github.com/CocoaPods/CocoaPods/pull/8536) which allows us to include local podspecs during validation and avoid searching the specs repo for `WordPress-Aztec-iOS`.
- See that CI is still green when validating against the local podspec.
1. Bump the version number …
> CircleCI: Use --include-podspecs when validating WordPress-Editor-iOS podspec to avoid publishing problems

- Aztec.xcodeproj/project.pbxproj
- Aztec/Classes/Extensions/NSMutableAttributedString+ReplaceAttributes.swift
- Aztec/Classes/Formatters/Implementations/CodeFormatter.swift
- Aztec/Classes/Formatters/Implementations/PreFormatter.swift
- Aztec/Classes/TextKit/FontProvider.swift
- Aztec/Classes/TextKit/LayoutManager.swift
- Aztec/Classes/TextKit/TextView.swift
- AztecTests/TextKit/TextViewTests.swift
- Example/Example/EditorDemoController.swift
This PR brings to TextView the following:
- The possibility to replace the defaultFont being used after the TextView is created
- Introduction of a FontProvider to allow configuration of fonts being used in the system
- Configuration of the default font being used for monospace 
To test:
- Run the sample app
- Check the demo content
- There is new button on the top right (+) press it and see if the default font changes in all the demo content.
> Allow configuration of default fonts used in TextView

- Aztec/Classes/TextKit/TextView.swift
I am proposing this change to address an issue I observed when implementing [alignment controls for paragraph blocks in gutenberg](https://github.com/wordpress-mobile/gutenberg-mobile/issues/1266). In particular, I observed that updating the alignment on empty views caused a number of display issues where either the cursor or the placeholder text (or both) would fail to reflect the selected alignment. More detail on these issues is discussed in the "Outstanding Issue #3: iOS Empty Views" section of [the gutenberg paragraph alignment PR's description](https://github.com/WordPress/gutenberg/pull/17577).
Before | After
--- | ---
In essence, the issue seems to be that the display of the views is not consistently being updated when the alignment field is updated. I tried calling either …
> Recalculate typing attributes on alignment update

- Aztec/Classes/TextKit/LayoutManager.swift
- Aztec/Classes/TextKit/TextView.swift
- Example/Example/EditorDemoController.swift
This PR changes the background colors for pre and quote elements to be optional.
This allows to make then nil and don't draw any specific color for them.
To test:
- See if Pre and Quotes are rendered properly.
> Make pre and quote background colors optional

- Aztec/Classes/TextKit/MediaAttachment.swift
- WordPressEditor/WordPressEditorTests/Extensions/MediaAttachmentWordPressTests.swift
Adds a property called `isLoaded` in `MediaAttachment`.
It returns `true` if the media is loaded, otherwise false.
To test:
The green build should be enough.
> Creates isLoaded property

- Aztec/Classes/TextKit/TextView.swift
- Aztec/Classes/TextKit/TextViewPasteboardDelegate.swift
- AztecTests/TextKit/TextViewTests.swift
- Example/Example/EditorDemoController.swift
Fixes #https://github.com/wordpress-mobile/WordPress-iOS/issues/12688
This PR implements three fixes to sort issues around text color:
- When copy/paste attributed string it makes sure that text color is set to default color if no color is set
- It also make sure that when all text is deleted the typing attributes are reset to default attributes that include the default color
- Make sure that the defaultColor is used for default attributes where converting from HTML mode.
To test:
- Copy paste text from other apps. Examples: Notes app, Tumblr in post edit mode, inside different sections of Aztec
- Open the demo app, put the cursor over the text with the red color, switch to HTML mode, and switch back to visual. Check that text is displayed in the correct color.
- Open the demo app, select …
> Fix copy/paste of attributed string from app without support for dark/light mode

- Aztec/Classes/Extensions/NSAttributedString+Lists.swift
- Aztec/Classes/Libxml2/DOM/Data/AttributeType.swift
- Aztec/Classes/NSAttributedString/Conversions/AttributedStringParser.swift
- Aztec/Classes/TextKit/LayoutManager.swift
- Aztec/Classes/TextKit/ParagraphProperty/TextList.swift
- AztecTests/Formatters/TextListFormatterTests.swift
- Example/Example/SampleContent/content.html
This PR adds visual support for the reversed and start properties in list.
It does three things:
- Add to TextList paragraph attributes properties for reversed and start
- Adds support for parsing of the attributes when reading the HTML
- Adds support to show visually the attributes effect on display
To test:
- Check that all  lists are showed correctly, specially the new ones with reversed and start attributes.
- Play around on HTML by changing the attributes of list to see if all is displayed correctly
- Test scenarios
- Ordered list without start and reversed
- Ordered list with reversed attribute: check if numbers are updated correctly has members are added
- Ordered list with start attributed: check if numbers start on the correct number indicated
- Ordered list …
> Implement start and reversed in lists.

- Aztec/Classes/TextKit/TextView.swift
Fixes: #1040 
Makes sure that when textColor is changed explicitely the defaultTextColor for HTML is updated accordingly.
To test:
- Change the value of textColor in EditorDemoController line 181
- Check that the color is applied to all text where no color is set in HTML
- Check that copy/paste without formatting from other apps get the color set in textColor
> Set default text color when text color is changed.

- Aztec/Classes/TextKit/LayoutManager.swift
- Example/AztecExample.xcodeproj/project.pbxproj
- Example/Example/SampleContent/content.html
- Example/Example/SampleContent/underline.html
- Example/Example/ViewController.swift
Fixes #https://github.com/wordpress-mobile/gutenberg-mobile/issues/1218
Change the range were underlines are drawn to avoid them to span to the end of a line. This is a workaround a bug from the Apple CoreText layout system where underlines that contain the `&nbsp` character expand to the end of the line.
<table>
<tr><td><b>Before</b></td><td><b>After</b></td></tr>
<tr><td><img src="https://user-images.githubusercontent.com/651601/75396157-c8f0bb00-58eb-11ea-8b9a-4025a2e2ea08.png" ></td><td><img src="https://user-images.githubusercontent.com/651601/75396228-ee7dc480-58eb-11ea-814c-bf8f1ae0f375.png" ></td></tr>
</table>
To test:
- Open the content `Underline NBSP`
- Check that underlines are draw correctly.
> Fix drawing of underlines when they have a nbsp and span to the end of a line.

- Aztec/Classes/TextKit/LayoutManager.swift
- CHANGELOG.md
- Example/AztecExample.xcodeproj/project.pbxproj
- Example/Example/SampleContent/content.html
- Example/Example/SampleContent/underline.html
- Example/Example/ViewController.swift
- WordPress-Aztec-iOS.podspec
- WordPress-Editor-iOS.podspec
Preparing release 1.17.0
To test:
Build the demo
Smoke test the demo content
Check if changelog and specs are correct.
> Prepare release 1.17.0

- Example/Cartfile.private
- Example/Cartfile.resolved
- Example/Example/EditorDemoController.swift
- Example/Example/MediaInserter.swift
- Example/Example/TextViewAttachmentDelegateProvider.swift
Update the example app to use Gridicons library version 1.0
To test:
- Just build and run locally.
- See if icons on the toolbar look correct on the demo app.
> Update gridicons to 1.0

- Aztec/Classes/TextKit/LayoutManager.swift
- CHANGELOG.md
- Example/Example/SampleContent/underline.html
- WordPress-Aztec-iOS.podspec
- WordPress-Editor-iOS.podspec
It looks the [underline fix](https://github.com/wordpress-mobile/AztecEditor-iOS/pull/1271) introduced a bug when drawing links that are at the end of the content.
This PR checks the condition where the fix is applied to avoid using it on the wrong scenarios.
To test:
- Open the NBSP demo content
- Move the cursor to the end of content ( last empty line)
- Press backspace
- Check that the underline is drawn to the end of the linked text
> Fix underline bug

- Aztec/Classes/Libxml2/Converters/In/HTMLParser.swift
- Aztec/Classes/Libxml2/Converters/In/InNodeConverter.swift
- Aztec/Classes/Libxml2/Converters/In/InNodesConverter.swift
- Aztec/Classes/Libxml2/DOM/Data/TextNode.swift
- Aztec/Classes/NSAttributedString/Conversions/HTMLConverter.swift
- AztecTests/TextKit/TextStorageTests.swift
- CHANGELOG.md
- WordPress-Aztec-iOS.podspec
- WordPress-Editor-iOS.podspec
Create an option in Aztec to allow configuration of the whitespace removal, also known as text sanitization.
This shouldn't affect the Aztec editor and the option should only be activated on special use cases, for example, the Gutenberg editor: https://github.com/wordpress-mobile/gutenberg-mobile/pull/2127
To test:
- See if all content still looks correct on the multiple demos
> Add option to disable collapsing of whitespaces.

- Aztec.xcodeproj/project.pbxproj
- Aztec/Classes/Converters/ElementsToAttributedString/Implementations/GenericElementConverter.swift
- Aztec/Classes/Converters/StringAttributesToAttributes/Implementations/SubscriptStringAttributeConverter.swift
- Aztec/Classes/Converters/StringAttributesToAttributes/Implementations/SuperscriptStringAttributeConverter.swift
- Aztec/Classes/Extensions/NSAttributedStringKey+Aztec.swift
- Aztec/Classes/Formatters/Base/StandardAttributeFormatter.swift
- Aztec/Classes/Formatters/Implementations/SubscriptFormatter.swift
- Aztec/Classes/Formatters/Implementations/SuperscriptFormatter.swift
- Aztec/Classes/Libxml2/DOM/Data/Element.swift
- Aztec/Classes/Libxml2/DOM/Logic/CSS/CSSAttributeMatcher.swift
- Aztec/Classes/NSAttributedString/Conversions/AttributedStringParser.swift
- CHANGELOG.md
- Example/Example/SampleContent/content.html
Adds support for superscript and subscript elements on Aztec.
To test:
- Check the Standard demo
- See if the demo superscript and subscript content show up correctly
- Play around with the elements
- Swift to HTML mode and see if the HTML is still correct
- Switch to Visual mode and see if all show correctly.
> Implement support for sup and sub HTML tags.

- Aztec/Classes/Libxml2/Converters/In/HTMLParser.swift
- AztecTests/TextKit/TextStorageTests.swift
Makes sure that collapsing/removal of whitespaces doesn't happen at the parser level
To test:
- Check if CI server tests are green.
> Fix collapse of white spaces when parsing HTML text.

- Aztec/Classes/TextKit/LayoutManager.swift
- CHANGELOG.md
- Example/Example/SampleContent/underline.html
- WordPress-Aztec-iOS.podspec
- WordPress-Editor-iOS.podspec
The fix needs to be applied every time there is any kind of newline
characters at the end of the character range.
Fixes #1275 
To test:
- Select the Underline NBSP demo
- Check that pressing Enter at the end of the lines does not make underlines expand across the whitespace of the line.
Like this:
> Apply range correction even if no nbsp is present.

- Aztec.xcodeproj/project.pbxproj
- Documentation/ReleaseProcess.md
Add a release document to the repo explaining the steps needed to create a new version.
To test:
- Review the document to see if all is correct.
> Add release documentation.

- Aztec/Classes/Extensions/UIColor+Parsers.swift
- WordPress-Aztec-iOS.podspec
- WordPress-Editor-iOS.podspec
**Fixes** https://github.com/wordpress-mobile/gutenberg-mobile/issues/2399
**Related PRs:**
`gutenberg` https://github.com/WordPress/gutenberg/pull/23289
`gutenberg-mobile` https://github.com/wordpress-mobile/gutenberg-mobile/pull/2404
~`WordPress-Android` https://github.com/wordpress-mobile/WordPress-Android/pull/12226~
~`WordPress-iOS` https://github.com/wordpress-mobile/WordPress-iOS/pull/14351~
Please see the testing and overview in https://github.com/wordpress-mobile/gutenberg-mobile/pull/2404
This simply exposes the helper method to prevent duplication in order to allow the conversion of colors from a hex string for link attributes.
> [Gutenberg] Correct Color for RichText links in Dark Mode - Expose helper method
